In [1]:
import pandas as pd

In [14]:
import numpy as np

In [10]:
dataset = pd.read_csv("recruitment_decision_tree.csv")

In [3]:
dataset.head()

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
0,1,Male,Yes,0.0,Graduate,No,5139,0.0,1.0,Urban,Y
1,2,Male,No,1.0,Graduate,No,4583,128.0,1.0,Rural,N
2,3,Male,No,0.0,Graduate,Yes,3000,66.0,1.0,Urban,Y
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
4,5,Male,Yes,0.0,Graduate,No,6000,141.0,1.0,Urban,Y

In [4]:
dataset.tail()

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
609,610,Female,Yes,0.0,Graduate,No,2900,71.0,1.0,Rural,Y
610,611,Male,No,3.0,Graduate,No,4106,40.0,1.0,Rural,Y
611,612,Male,No,1.0,Graduate,No,8072,253.0,1.0,Urban,Y
612,613,Male,No,2.0,Graduate,No,7583,187.0,1.0,Urban,Y
613,614,Female,Yes,0.0,Graduate,Yes,4583,133.0,0.0,Semiurban,N

In [6]:
dataset.head()

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
0,1,Male,Yes,0.0,Graduate,No,5139,0.0,1.0,Urban,Y
1,2,Male,No,1.0,Graduate,No,4583,128.0,1.0,Rural,N
2,3,Male,No,0.0,Graduate,Yes,3000,66.0,1.0,Urban,Y
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
4,5,Male,Yes,0.0,Graduate,No,6000,141.0,1.0,Urban,Y

In [21]:
pd.set_option('display.max_rows', 500)

In [22]:
dataset.head(500)

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
0,1,Male,Yes,0.0,Graduate,No,5139,0.0,1.0,Urban,Y
1,2,Male,No,1.0,Graduate,No,4583,128.0,1.0,Rural,N
2,3,Male,No,0.0,Graduate,Yes,3000,66.0,1.0,Urban,Y
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
4,5,Male,Yes,0.0,Graduate,No,6000,141.0,1.0,Urban,Y
5,6,Male,No,2.0,Graduate,Yes,5417,267.0,1.0,Urban,Y
6,7,Male,No,0.0,Not Graduate,No,2333,95.0,1.0,Urban,Y
7,8,Male,No,3.0,Graduate,No,3036,158.0,0.0,Semiurban,N
8,9,Male,No,2.0,Graduate,No,4006,168.0,1.0,Urban,Y
9,10,Male,No,1.0,Graduate,No,12841,349.0,1.0,Semiurban,N
10,11,Male,No,2.0,Graduate,No,3200,70.0,1.0,Urban,Y
11,12,Male,No,2.0,Graduate,NaN,2500,109.0,1.0,Urban,Y
12,13,Male,No,2.0,Graduate,No,3073,200.0,1.0,Urban,Y
13,14,Male,Yes,0.0,Graduate,No,1853,114.0,1.0,Rural,N
14,15,Male,No,2.0,Graduate,No,1299,17.0,1.0,Urban,Y
15,16,Male,Yes,0.0,Graduate,No,4950,125.0,1.0,Urban,Y
16,17,Male,Yes,1.0,Not Graduate,No,3596,100.0,NaN,Urban,Y
17,18,Female,Yes,0.0,Graduate,No,3510,76.0,0.0,Urban,N
18,19,Male,No,0.0,Not Graduate,No,4887,133.0,1.0,Rural,N
19,20,Male,No,0.0,Graduate,NaN,2600,115.0,1.0,Urban,Y
20,21,Male,No,0.0,Not Graduate,No,7660,104.0,0.0,Urban,N
21,22,Male,No,1.0,Graduate,No,5955,315.0,1.0,Urban,Y
22,23,Male,No,0.0,Not Graduate,No,2600,116.0,0.0,Semiurban,N
23,24,NaN,No,2.0,Not Graduate,No,3365,112.0,0.0,Rural,N
24,25,Male,No,1.0,Graduate,NaN,3717,151.0,NaN,Semiurban,N
25,26,Male,No,0.0,Graduate,Yes,9560,191.0,1.0,Semiurban,Y
26,27,Male,No,0.0,Graduate,No,2799,122.0,1.0,Semiurban,Y
27,28,Male,No,2.0,Not Graduate,No,4226,110.0,1.0,Urban,Y
28,29,Male,Yes,0.0,Not Graduate,No,1442,35.0,1.0,Urban,N
29,30,Female,Yes,2.0,Graduate,NaN,3750,120.0,1.0,Semiurban,Y
30,31,Male,No,1.0,Graduate,NaN,4166,201.0,NaN,Urban,N
31,32,Male,Yes,0.0,Graduate,No,3167,74.0,1.0,Urban,N
32,33,Male,Yes,1.0,Graduate,Yes,4692,106.0,1.0,Rural,N
33,34,Male,No,0.0,Graduate,No,3500,114.0,1.0,Semiurban,Y
34,35,Male,Yes,3.0,Graduate,No,12500,320.0,1.0,Rural,N
35,36,Male,No,0.0,Graduate,No,2275,NaN,1.0,Urban,Y
36,37,Male,No,0.0,Graduate,No,1828,100.0,0.0,Urban,N
37,38,Female,No,0.0,Graduate,No,3667,144.0,1.0,Semiurban,Y
38,39,Male,Yes,0.0,Graduate,No,4166,184.0,1.0,Urban,Y
39,40,Male,Yes,0.0,Not Graduate,No,3748,110.0,1.0,Semiurban,Y
40,41,Male,Yes,0.0,Graduate,No,3600,80.0,1.0,Urban,N
41,42,Male,Yes,0.0,Graduate,No,1800,47.0,1.0,Urban,Y
42,43,Male,No,0.0,Graduate,No,2400,75.0,NaN,Urban,Y
43,44,Male,No,0.0,Graduate,No,3941,134.0,1.0,Semiurban,Y
44,45,Male,No,0.0,Not Graduate,Yes,4695,96.0,1.0,Urban,Y
45,46,Female,Yes,0.0,Graduate,No,3410,88.0,1.0,Urban,Y
46,47,Male,No,1.0,Graduate,No,5649,44.0,1.0,Urban,Y
47,48,Male,No,0.0,Graduate,No,5821,144.0,1.0,Urban,Y
48,49,Female,No,0.0,Graduate,No,2645,120.0,0.0,Urban,N
49,50,Female,Yes,0.0,Graduate,No,4000,144.0,1.0,Semiurban,Y
50,51,Female,No,0.0,Not Graduate,No,1928,100.0,1.0,Semiurban,Y
51,52,Female,Yes,0.0,Graduate,No,3086,120.0,1.0,Semiurban,Y
52,53,Female,Yes,0.0,Graduate,No,4230,112.0,1.0,Semiurban,N
53,54,Male,No,2.0,Graduate,No,4616,134.0,1.0,Urban,N
54,55,Female,No,1.0,Graduate,Yes,11500,286.0,0.0,Urban,N
55,56,Male,No,2.0,Graduate,No,2708,97.0,1.0,Semiurban,Y
56,57,Male,No,0.0,Graduate,No,2132,96.0,1.0,Semiurban,Y
57,58,Male,No,0.0,Graduate,No,3366,135.0,1.0,Rural,N
58,59,Male,No,1.0,Graduate,No,8080,180.0,1.0,Urban,Y
59,60,Male,No,2.0,Not Graduate,No,3357,144.0,1.0,Urban,Y
60,61,Male,No,0.0,Graduate,No,2500,120.0,1.0,Urban,Y
61,62,Male,No,3.0,Graduate,No,3029,99.0,1.0,Urban,Y
62,63,Male,No,0.0,Not Graduate,Yes,2609,165.0,0.0,Rural,N
63,64,Male,No,1.0,Graduate,No,4945,NaN,0.0,Rural,N
64,65,Female,Yes,0.0,Graduate,No,4166,116.0,0.0,Semiurban,N
65,66,Male,No,0.0,Graduate,No,5726,258.0,1.0,Semiurban,N
66,67,Male,Yes,0.0,Not Graduate,No,3200,126.0,0.0,Urban,N
67,68,Male,No,1.0,Graduate,No,10750,312.0,1.0,Urban,Y
68,69,Male,No,3.0,Not Graduate,Yes,7100,125.0,1.0,Urban,Y
69,70,Female,Yes,0.0,Graduate,No,4300,136.0,0.0,Semiurban,N
70,71,Male,No,0.0,Graduate,No,3208,172.0,1.0,Urban,Y
71,72,Male,No,2.0,Not Graduate,Yes,1875,97.0,1.0,Semiurban,Y
72,73,Male,Yes,0.0,Graduate,No,3500,81.0,1.0,Semiurban,Y
73,74,Male,No,3.0,Not Graduate,No,4755,95.0,0.0,Semiurban,N
74,75,Male,No,3.0,Graduate,Yes,5266,187.0,1.0,Semiurban,Y
75,76,Male,Yes,0.0,Graduate,No,3750,113.0,1.0,Urban,N
76,77,Male,Yes,0.0,Graduate,No,3750,176.0,1.0,Urban,N
77,78,Male,No,1.0,Graduate,Yes,1000,110.0,1.0,Urban,N
78,79,Male,No,3.0,Graduate,No,3167,180.0,0.0,Semiurban,N
79,80,Male,No,3.0,Not Graduate,Yes,3333,130.0,NaN,Semiurban,Y
80,81,Female,Yes,0.0,Graduate,No,3846,111.0,1.0,Semiurban,Y
81,82,Male,No,1.0,Graduate,Yes,2395,NaN,1.0,Semiurban,Y
82,83,Female,No,2.0,Graduate,No,1378,167.0,1.0,Urban,N
83,84,Male,No,0.0,Graduate,No,6000,265.0,NaN,Semiurban,N
84,85,Male,No,1.0,Graduate,No,3988,50.0,1.0,Urban,Y
85,86,Male,Yes,0.0,Graduate,No,2366,136.0,1.0,Semiurban,Y
86,87,Male,No,2.0,Not Graduate,No,3333,99.0,NaN,Semiurban,Y
87,88,Male,No,0.0,Graduate,No,2500,104.0,1.0,Semiurban,Y
88,89,Male,Yes,0.0,Graduate,No,8566,210.0,1.0,Urban,Y
89,90,Male,No,0.0,Graduate,No,5695,175.0,1.0,Semiurban,Y
90,91,Male,No,0.0,Graduate,No,2958,131.0,1.0,Semiurban,Y
91,92,Male,No,2.0,Graduate,No,6250,188.0,1.0,Semiurban,Y
92,93,Male,No,2.0,Not Graduate,No,3273,81.0,1.0,Urban,Y
93,94,Male,Yes,0.0,Graduate,No,4133,122.0,1.0,Semiurban,Y
94,95,Male,Yes,0.0,Not Graduate,No,3620,25.0,1.0,Semiurban,Y
95,96,Male,Yes,0.0,Graduate,NaN,6782,NaN,NaN,Urban,N
96,97,Female,No,0.0,Graduate,No,2484,137.0,1.0,Semiurban,Y
97,98,Male,No,0.0,Graduate,No,1977,50.0,1.0,Semiurban,Y
98,99,Male,No,0.0,Not Graduate,No,4188,115.0,1.0,Semiurban,Y
99,100,Male,No,0.0,Graduate,No,1759,131.0,1.0,Semiurban,Y
100,101,Male,No,2.0,Not Graduate,No,4288,133.0,1.0,Urban,Y
101,102,Male,Yes,0.0,Graduate,No,4843,151.0,1.0,Semiurban,Y
102,103,Male,No,NaN,Graduate,No,13650,NaN,1.0,Urban,Y
103,104,Male,No,0.0,Graduate,No,4652,NaN,1.0,Semiurban,Y
104,105,Male,NaN,NaN,Graduate,No,3816,160.0,1.0,Urban,Y
105,106,Male,No,1.0,Graduate,No,3052,100.0,1.0,Urban,Y
106,107,Male,No,2.0,Graduate,No,11417,225.0,1.0,Urban,Y
107,108,Male,Yes,0.0,Not Graduate,NaN,7333,120.0,1.0,Rural,N
108,109,Male,No,2.0,Graduate,No,3800,216.0,0.0,Urban,N
109,110,Male,No,3.0,Not Graduate,No,2071,94.0,1.0,Semiurban,Y
110,111,Male,Yes,0.0,Graduate,No,5316,136.0,1.0,Urban,Y
111,112,Female,No,0.0,Graduate,NaN,2929,139.0,1.0,Semiurban,Y
112,113,Male,No,0.0,Not Graduate,No,3572,152.0,0.0,Rural,N
113,114,Female,Yes,1.0,Graduate,Yes,7451,NaN,1.0,Semiurban,Y
114,115,Male,Yes,0.0,Graduate,NaN,5050,118.0,1.0,Semiurban,Y
115,116,Male,No,1.0,Graduate,No,14583,185.0,1.0,Rural,Y
116,117,Female,No,0.0,Graduate,No,3167,154.0,1.0,Semiurban,Y
117,118,Male,No,1.0,Graduate,No,2214,85.0,NaN,Urban,Y
118,119,Male,No,0.0,Graduate,No,5568,175.0,1.0,Rural,N
119,120,Female,Yes,0.0,Graduate,No,10408,259.0,1.0,Urban,Y
120,121,Male,No,NaN,Graduate,No,5667,180.0,1.0,Rural,Y
121,122,Female,Yes,0.0,Graduate,No,4166,44.0,1.0,Semiurban,Y
122,123,Female,Yes,0.0,Graduate,No,2137,137.0,0.0,Semiurban,Y
123,124,Male,No,2.0,Graduate,No,2957,81.0,1.0,Semiurban,Y
124,125,Male,No,0.0,Not Graduate,No,4300,194.0,1.0,Rural,Y
125,126,Female,Yes,0.0,Graduate,No,3692,93.0,NaN,Rural,Y
126,127,NaN,No,3.0,Graduate,No,23803,370.0,1.0,Rural,Y
127,128,Male,Yes,0.0,Graduate,No,3865,NaN,1.0,Rural,Y
128,129,Male,No,1.0,Graduate,Yes,10513,160.0,0.0,Urban,N
129,130,Male,No,0.0,Graduate,No,6080,182.0,NaN,Rural,N
130,131,Male,Yes,0.0,Graduate,Yes,20166,650.0,NaN,Urban,Y
131,132,Male,Yes,0.0,Graduate,No,2014,74.0,1.0,Urban,Y
132,133,Male,Yes,0.0,Graduate,No,2718,70.0,1.0,Semiurban,Y
133,134,Male,No,0.0,Graduate,Yes,3459,25.0,1.0,Semiurban,Y
134,135,Male,Yes,0.0,Graduate,No,4895,102.0,1.0,Semiurban,Y
135,136,Male,No,3.0,Graduate,No,4000,290.0,1.0,Semiurban,N
136,137,Female,No,0.0,Graduate,No,4583,84.0,1.0,Rural,N
137,138,Male,No,2.0,Graduate,Yes,3316,88.0,1.0,Urban,Y
138,139,Male,Yes,0.0,Graduate,No,14999,242.0,0.0,Semiurban,N
139,140,Male,No,2.0,Not Graduate,No,4200,129.0,1.0,Rural,N
140,141,Male,No,2.0,Graduate,No,5042,185.0,1.0,Rural,N
141,142,Male,Yes,0.0,Graduate,No,5417,168.0,1.0,Urban,Y
142,143,Male,Yes,0.0,Graduate,Yes,6950,175.0,1.0,Semiurban,Y
143,144,Male,No,0.0,Graduate,No,2698,122.0,1.0,Semiurban,Y
144,145,Male,No,2.0,Graduate,No,11757,187.0,1.0,Urban,Y
145,146,Female,No,0.0,Graduate,No,2330,100.0,1.0,Semiurban,Y
146,147,Female,No,2.0,Graduate,No,14866,70.0,1.0,Urban,Y
147,148,Male,No,1.0,Graduate,No,1538,30.0,1.0,Urban,Y
148,149,Female,Yes,0.0,Graduate,No,10000,225.0,1.0,Rural,N
149,150,Male,No,0.0,Graduate,No,4860,125.0,1.0,Semiurban,Y
150,151,Male,Yes,0.0,Graduate,No,6277,118.0,0.0,Rural,N
151,152,Male,No,0.0,Graduate,Yes,2577,152.0,1.0,Rural,Y
152,153,Male,Yes,0.0,Graduate,No,9166,244.0,1.0,Urban,N
153,154,Male,No,2.0,Not Graduate,No,2281,113.0,1.0,Rural,N
154,155,Male,Yes,0.0,Graduate,No,3254,50.0,1.0,Urban,Y
155,156,Male,No,3.0,Graduate,No,39999,600.0,0.0,Semiurban,Y
156,157,Male,No,1.0,Graduate,No,6000,160.0,NaN,Rural,Y
157,158,Male,No,1.0,Graduate,No,9538,187.0,1.0,Urban,Y
158,159,Male,Yes,0.0,Graduate,NaN,2980,120.0,1.0,Rural,Y
159,160,Male,No,0.0,Graduate,No,4583,255.0,1.0,Semiurban,Y
160,161,Male,No,0.0,Not Graduate,No,1863,98.0,1.0,Semiurban,Y
161,162,Male,No,0.0,Graduate,No,7933,275.0,1.0,Urban,N
162,163,Male,No,1.0,Graduate,No,3089,121.0,0.0,Semiurban,N
163,164,Male,No,2.0,Graduate,No,4167,158.0,1.0,Rural,Y
164,165,Male,No,0.0,Graduate,No,9323,75.0,1.0,Urban,Y
165,166,Male,No,0.0,Graduate,No,3707,182.0,1.0,Rural,Y
166,167,Female,No,0.0,Graduate,No,4583,112.0,1.0,Rural,N
167,168,Male,No,0.0,Graduate,No,2439,129.0,1.0,Rural,Y
168,169,Male,Yes,0.0,Graduate,No,2237,63.0,0.0,Semiurban,N
169,170,Male,No,2.0,Graduate,No,8000,200.0,1.0,Semiurban,Y
170,171,Male,No,0.0,Not Graduate,NaN,1820,95.0,1.0,Rural,Y
171,172,NaN,No,3.0,Graduate,No,51763,700.0,1.0,Urban,Y
172,173,Male,No,3.0,Not Graduate,No,3522,81.0,1.0,Rural,N
173,174,Male,No,0.0,Graduate,No,5708,187.0,1.0,Semiurban,Y
174,175,Male,No,0.0,Not Graduate,Yes,4344,87.0,1.0,Semiurban,N
175,176,Male,No,0.0,Graduate,No,3497,116.0,1.0,Rural,Y
176,177,Male,No,2.0,Graduate,No,2045,101.0,1.0,Rural,Y
177,178,Male,No,3.0,Graduate,No,5516,495.0,0.0,Semiurban,N
178,179,Male,No,1.0,Graduate,No,3750,116.0,1.0,Semiurban,Y
179,180,Male,Yes,0.0,Not Graduate,No,2333,102.0,0.0,Urban,N
180,181,Male,No,1.0,Graduate,No,6400,180.0,0.0,Urban,N
181,182,Male,Yes,0.0,Graduate,No,1916,67.0,NaN,Rural,N
182,183,Male,No,0.0,Graduate,No,4600,73.0,1.0,Semiurban,Y
183,184,Male,No,1.0,Graduate,No,33846,260.0,1.0,Semiurban,N
184,185,Female,No,0.0,Graduate,No,3625,108.0,1.0,Semiurban,Y
185,186,Male,No,0.0,Graduate,Yes,39147,120.0,1.0,Semiurban,Y
186,187,Male,No,1.0,Graduate,Yes,2178,66.0,0.0,Rural,N
187,188,Male,No,0.0,Graduate,No,2383,58.0,NaN,Rural,Y
188,189,NaN,No,0.0,Graduate,Yes,674,168.0,1.0,Rural,Y
189,190,Male,No,0.0,Graduate,No,9328,188.0,1.0,Rural,Y
190,191,Male,Yes,0.0,Not Graduate,No,4885,48.0,1.0,Rural,Y
191,192,Male,Yes,0.0,Graduate,No,12000,164.0,1.0,Semiurban,N
192,193,Male,No,0.0,Not Graduate,No,6033,160.0,1.0,Urban,N
193,194,Male,Yes,0.0,Graduate,No,3858,76.0,1.0,Semiurban,Y
194,195,Male,Yes,0.0,Graduate,No,4191,120.0,1.0,Rural,Y
195,196,Male,No,1.0,Graduate,No,3125,170.0,1.0,Semiurban,N
196,197,Male,Yes,0.0,Graduate,No,8333,187.0,1.0,Rural,Y
197,198,Female,Yes,0.0,Not Graduate,No,1907,120.0,1.0,Urban,Y
198,199,Female,No,0.0,Graduate,No,3416,113.0,NaN,Semiurban,Y
199,200,Male,Yes,0.0,Graduate,Yes,11000,83.0,1.0,Urban,N
200,201,Male,No,1.0,Not Graduate,No,2600,90.0,1.0,Semiurban,Y
201,202,Male,Yes,2.0,Graduate,No,4923,166.0,0.0,Semiurban,Y
202,203,Male,No,3.0,Not Graduate,No,3992,NaN,1.0,Urban,N
203,204,Male,No,1.0,Not Graduate,No,3500,135.0,1.0,Urban,Y
204,205,Male,No,2.0,Not Graduate,No,3917,124.0,1.0,Semiurban,Y
205,206,Female,Yes,0.0,Not Graduate,No,4408,120.0,1.0,Semiurban,Y
206,207,Female,Yes,0.0,Graduate,No,3244,80.0,1.0,Urban,Y
207,208,Male,Yes,0.0,Not Graduate,No,3975,55.0,1.0,Rural,Y
208,209,Male,Yes,0.0,Graduate,No,2479,59.0,1.0,Urban,Y
209,210,Male,Yes,0.0,Graduate,No,3418,127.0,1.0,Semiurban,N
210,211,Female,Yes,0.0,Graduate,No,10000,214.0,1.0,Semiurban,N
211,212,Male,No,3.0,Graduate,No,3430,128.0,0.0,Semiurban,N
212,213,Male,No,1.0,Graduate,Yes,7787,240.0,1.0,Urban,Y
213,214,Male,No,3.0,Not Graduate,Yes,5703,130.0,1.0,Rural,Y
214,215,Male,No,0.0,Graduate,No,3173,137.0,1.0,Urban,Y
215,216,Male,No,3.0,Not Graduate,No,3850,100.0,1.0,Semiurban,Y
216,217,Male,No,0.0,Graduate,No,150,135.0,1.0,Rural,N
217,218,Male,No,0.0,Graduate,No,3727,131.0,1.0,Semiurban,Y
218,219,Male,No,2.0,Graduate,NaN,5000,72.0,0.0,Semiurban,N
219,220,Female,No,2.0,Graduate,No,4283,127.0,NaN,Semiurban,Y
220,221,Male,No,0.0,Graduate,No,2221,60.0,0.0,Urban,N
221,222,Male,No,2.0,Graduate,No,4009,116.0,1.0,Semiurban,Y
222,223,Male,Yes,0.0,Graduate,No,2971,144.0,1.0,Semiurban,Y
223,224,Male,No,0.0,Graduate,No,7578,175.0,1.0,Semiurban,Y
224,225,Male,No,0.0,Graduate,No,6250,128.0,1.0,Semiurban,Y
225,226,Male,No,0.0,Graduate,No,3250,170.0,1.0,Rural,N
226,227,Male,No,NaN,Not Graduate,Yes,4735,138.0,1.0,Urban,N
227,228,Male,No,2.0,Graduate,No,6250,210.0,1.0,Semiurban,Y
228,229,Male,NaN,NaN,Graduate,No,4758,158.0,1.0,Semiurban,Y
229,230,Male,Yes,0.0,Graduate,Yes,6400,200.0,1.0,Rural,Y
230,231,Male,No,1.0,Graduate,No,2491,104.0,1.0,Semiurban,Y
231,232,Male,No,0.0,Graduate,NaN,3716,42.0,1.0,Rural,Y
232,233,Male,Yes,0.0,Not Graduate,No,3189,120.0,1.0,Rural,Y
233,234,Female,Yes,0.0,Graduate,No,8333,280.0,1.0,Semiurban,Y
234,235,Male,No,1.0,Graduate,No,3155,140.0,1.0,Semiurban,Y
235,236,Male,No,1.0,Graduate,No,5500,170.0,1.0,Rural,Y
236,237,Male,No,0.0,Graduate,NaN,5746,255.0,NaN,Urban,N
237,238,Female,Yes,0.0,Graduate,Yes,3463,122.0,NaN,Urban,Y
238,239,Female,Yes,1.0,Graduate,No,3812,112.0,1.0,Rural,Y
239,240,Male,No,1.0,Graduate,No,3315,96.0,1.0,Semiurban,Y
240,241,Male,No,2.0,Graduate,No,5819,120.0,1.0,Rural,Y
241,242,Male,No,1.0,Not Graduate,No,2510,140.0,1.0,Urban,N
242,243,Male,Yes,0.0,Graduate,No,2965,155.0,1.0,Urban,Y
243,244,Male,No,2.0,Graduate,Yes,6250,108.0,1.0,Rural,Y
244,245,Male,No,0.0,Not Graduate,No,3406,123.0,1.0,Semiurban,Y
245,246,Male,Yes,0.0,Graduate,Yes,6050,120.0,1.0,Urban,N
246,247,Male,No,2.0,Graduate,No,9703,112.0,1.0,Urban,Y
247,248,Male,No,1.0,Not Graduate,No,6608,137.0,1.0,Urban,Y
248,249,Male,No,1.0,Graduate,No,2882,123.0,1.0,Semiurban,Y
249,250,Male,No,0.0,Graduate,No,1809,90.0,1.0,Urban,Y
250,251,Male,No,0.0,Not Graduate,No,1668,201.0,0.0,Semiurban,N
251,252,Female,Yes,2.0,Graduate,No,3427,138.0,1.0,Urban,N
252,253,Male,Yes,0.0,Not Graduate,Yes,2583,104.0,1.0,Rural,Y
253,254,Male,No,1.0,Not Graduate,No,2661,279.0,1.0,Semiurban,Y
254,255,Male,Yes,0.0,Graduate,Yes,16250,192.0,0.0,Urban,N
255,256,Female,Yes,3.0,Graduate,No,3083,255.0,1.0,Rural,Y
256,257,Male,Yes,0.0,Not Graduate,No,6045,115.0,0.0,Rural,N
257,258,Male,No,3.0,Graduate,No,5250,94.0,1.0,Urban,N
258,259,Male,No,0.0,Graduate,No,14683,304.0,1.0,Rural,N
259,260,Male,No,3.0,Not Graduate,No,4931,128.0,NaN,Semiurban,N
260,261,Male,No,1.0,Graduate,No,6083,330.0,NaN,Urban,Y
261,262,Male,Yes,0.0,Graduate,No,2060,134.0,1.0,Semiurban,Y
262,263,Female,Yes,1.0,Graduate,No,3481,155.0,1.0,Semiurban,N
263,264,Female,Yes,0.0,Graduate,No,7200,120.0,1.0,Rural,Y
264,265,Male,Yes,0.0,Graduate,Yes,5166,128.0,1.0,Semiurban,Y
265,266,Male,Yes,0.0,Graduate,No,4095,151.0,1.0,Rural,Y
266,267,Male,No,2.0,Graduate,No,4708,150.0,1.0,Semiurban,Y
267,268,Male,No,3.0,Graduate,No,4333,160.0,0.0,Urban,Y
268,269,Female,Yes,0.0,Graduate,NaN,3418,135.0,1.0,Rural,N
269,270,Female,Yes,1.0,Graduate,No,2876,90.0,1.0,Urban,Y
270,271,Female,Yes,0.0,Graduate,No,3237,30.0,1.0,Urban,Y
271,272,Male,No,0.0,Graduate,No,11146,136.0,1.0,Urban,Y
272,273,Male,Yes,0.0,Graduate,No,2833,126.0,1.0,Rural,Y
273,274,Male,No,0.0,Graduate,No,2620,150.0,1.0,Semiurban,Y
274,275,Male,No,2.0,Graduate,No,3900,90.0,1.0,Semiurban,Y
275,276,Male,No,1.0,Graduate,No,2750,115.0,1.0,Semiurban,Y
276,277,Male,No,0.0,Graduate,No,3993,207.0,1.0,Semiurban,Y
277,278,Male,No,0.0,Graduate,No,3103,80.0,1.0,Urban,Y
278,279,Male,No,0.0,Graduate,No,14583,436.0,1.0,Semiurban,Y
279,280,Female,No,0.0,Not Graduate,No,4100,124.0,NaN,Rural,Y
280,281,Male,Yes,1.0,Not Graduate,Yes,4053,158.0,0.0,Urban,N
281,282,Male,No,0.0,Graduate,No,3927,112.0,1.0,Semiurban,Y
282,283,Male,No,2.0,Graduate,No,2301,78.0,1.0,Urban,Y
283,284,Female,Yes,0.0,Graduate,No,1811,54.0,1.0,Urban,Y
284,285,Male,No,0.0,Graduate,No,20667,NaN,1.0,Rural,N
285,286,Male,Yes,0.0,Graduate,No,3158,89.0,1.0,Rural,Y
286,287,Female,Yes,0.0,Graduate,Yes,2600,99.0,1.0,Semiurban,N
287,288,Male,No,0.0,Graduate,No,3704,120.0,1.0,Rural,Y
288,289,Female,Yes,0.0,Graduate,No,4124,115.0,1.0,Semiurban,Y
289,290,Male,Yes,0.0,Graduate,No,9508,187.0,1.0,Rural,Y
290,291,Male,No,0.0,Graduate,No,3075,139.0,1.0,Rural,Y
291,292,Male,No,2.0,Graduate,No,4400,127.0,0.0,Semiurban,N
292,293,Male,No,2.0,Graduate,No,3153,134.0,1.0,Urban,Y
293,294,Female,Yes,NaN,Graduate,No,5417,143.0,0.0,Urban,N
294,295,Male,No,0.0,Graduate,No,2383,172.0,1.0,Semiurban,Y
295,296,Male,No,3.0,Graduate,NaN,4416,110.0,1.0,Urban,Y
296,297,Male,No,1.0,Graduate,No,6875,200.0,1.0,Semiurban,Y
297,298,Female,No,1.0,Graduate,No,4666,135.0,1.0,Urban,Y
298,299,Female,Yes,0.0,Graduate,No,5000,151.0,1.0,Rural,N
299,300,Male,No,1.0,Graduate,No,2014,113.0,1.0,Urban,N
300,301,Male,No,0.0,Not Graduate,No,1800,93.0,0.0,Urban,N
301,302,Male,No,NaN,Not Graduate,No,2875,105.0,1.0,Semiurban,Y
302,303,Female,Yes,0.0,Graduate,No,5000,132.0,1.0,Rural,Y
303,304,Male,No,1.0,Graduate,No,1625,96.0,1.0,Urban,Y
304,305,Male,Yes,0.0,Graduate,No,4000,140.0,1.0,Rural,Y
305,306,Male,Yes,0.0,Not Graduate,No,2000,NaN,1.0,Urban,N
306,307,Female,Yes,0.0,Graduate,No,3762,135.0,1.0,Rural,Y
307,308,Female,Yes,0.0,Graduate,No,2400,104.0,0.0,Urban,N
308,309,Male,Yes,0.0,Graduate,No,20233,480.0,1.0,Rural,N
309,310,Male,No,2.0,Not Graduate,No,7667,185.0,NaN,Rural,Y
310,311,Female,Yes,0.0,Graduate,No,2917,84.0,1.0,Semiurban,Y
311,312,Male,Yes,0.0,Not Graduate,No,2927,111.0,1.0,Semiurban,Y
312,313,Female,Yes,0.0,Graduate,No,2507,56.0,1.0,Rural,Y
313,314,Male,No,2.0,Graduate,Yes,5746,144.0,NaN,Rural,Y
314,315,NaN,No,0.0,Graduate,No,2473,159.0,1.0,Rural,N
315,316,Male,No,1.0,Not Graduate,No,3399,111.0,1.0,Urban,Y
316,317,Male,No,2.0,Graduate,No,3717,120.0,1.0,Semiurban,Y
317,318,Male,No,0.0,Graduate,No,2058,88.0,NaN,Urban,Y
318,319,Female,Yes,1.0,Graduate,No,3541,112.0,NaN,Semiurban,Y
319,320,Male,No,1.0,Graduate,Yes,10000,155.0,1.0,Rural,N
320,321,Male,No,0.0,Graduate,No,2400,115.0,1.0,Semiurban,Y
321,322,Male,No,3.0,Graduate,No,4342,124.0,1.0,Semiurban,Y
322,323,Male,No,2.0,Not Graduate,No,3601,NaN,1.0,Rural,Y
323,324,Female,Yes,0.0,Graduate,No,3166,132.0,NaN,Rural,Y
324,325,Male,No,3.0,Graduate,No,15000,300.0,1.0,Rural,Y
325,326,Male,No,1.0,Graduate,Yes,8666,376.0,0.0,Rural,N
326,327,Male,Yes,0.0,Graduate,No,4917,130.0,0.0,Rural,Y
327,328,Male,No,0.0,Graduate,Yes,5818,184.0,1.0,Semiurban,Y
328,329,Female,No,0.0,Graduate,No,4333,110.0,1.0,Urban,N
329,330,Female,Yes,0.0,Graduate,No,2500,67.0,1.0,Urban,Y
330,331,Male,Yes,1.0,Graduate,No,4384,117.0,1.0,Urban,Y
331,332,Male,Yes,0.0,Graduate,No,2935,98.0,1.0,Semiurban,Y
332,333,Male,Yes,NaN,Graduate,No,2833,71.0,1.0,Urban,Y
333,334,Male,No,0.0,Graduate,NaN,63337,490.0,1.0,Urban,Y
334,335,NaN,No,1.0,Graduate,Yes,9833,182.0,1.0,Urban,Y
335,336,Male,No,NaN,Graduate,Yes,5503,70.0,1.0,Semiurban,Y
336,337,Male,No,1.0,Graduate,NaN,5250,160.0,1.0,Rural,Y
337,338,Male,No,2.0,Graduate,Yes,2500,176.0,1.0,Rural,Y
338,339,Female,Yes,3.0,Not Graduate,No,1830,NaN,0.0,Urban,N
339,340,Female,Yes,0.0,Graduate,No,4160,71.0,1.0,Semiurban,Y
340,341,Male,No,3.0,Not Graduate,No,2647,173.0,1.0,Rural,N
341,342,Female,Yes,0.0,Graduate,No,2378,46.0,1.0,Rural,N
342,343,Male,No,1.0,Not Graduate,No,4554,158.0,1.0,Urban,Y
343,344,Male,No,3.0,Not Graduate,No,3173,74.0,1.0,Semiurban,Y
344,345,Male,No,2.0,Graduate,NaN,2583,125.0,1.0,Rural,Y
345,346,Male,No,0.0,Graduate,No,2499,160.0,1.0,Semiurban,Y

In [37]:
dataset.sort_values(by=['Gender', 'Education' ], ascending=False)

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
6,7,Male,No,0.0,Not Graduate,No,2333,95.0,1.0,Urban,Y
16,17,Male,Yes,1.0,Not Graduate,No,3596,100.0,NaN,Urban,Y
18,19,Male,No,0.0,Not Graduate,No,4887,133.0,1.0,Rural,N
20,21,Male,No,0.0,Not Graduate,No,7660,104.0,0.0,Urban,N
...,...,...,...,...,...,...,...,...,...,...,...
477,478,NaN,No,2.0,Graduate,No,2873,132.0,0.0,Semiurban,N
507,508,NaN,Yes,0.0,Graduate,No,3583,96.0,1.0,Urban,N
576,577,NaN,No,0.0,Graduate,No,3087,136.0,0.0,Semiurban,N
588,589,NaN,Yes,0.0,Graduate,No,4750,94.0,1.0,Semiurban,Y
592,593,NaN,Yes,3.0,Graduate,Yes,9357,292.0,1.0,Semiurban,Y

In [61]:
dataset.sort_values(by=['Experience_Years', 'Gender', 'Education', 'Salary * 10E4'], ascending=[True, True, True, False], inplace=True)

In [62]:
dataset[['Experience_Years', 'Gender', 'Education']].head (500)

     Experience_Years  Gender     Education
233               0.0  Female      Graduate
119               0.0  Female      Graduate
148               0.0  Female      Graduate
210               0.0  Female      Graduate
404               0.0  Female      Graduate
559               0.0  Female      Graduate
382               0.0  Female      Graduate
116               0.0  Female      Graduate
298               0.0  Female      Graduate
37                0.0  Female      Graduate
49                0.0  Female      Graduate
111               0.0  Female      Graduate
96                0.0  Female      Graduate
122               0.0  Female      Graduate
69                0.0  Female      Graduate
306               0.0  Female      Graduate
268               0.0  Female      Graduate
613               0.0  Female      Graduate
323               0.0  Female      Graduate
302               0.0  Female      Graduate
354               0.0  Female      Graduate
237               0.0  Female      Graduate
48                0.0  Female      Graduate
51                0.0  Female      Graduate
263               0.0  Female      Graduate
64                0.0  Female      Graduate
405               0.0  Female      Graduate
288               0.0  Female      Graduate
500               0.0  Female      Graduate
198               0.0  Female      Graduate
166               0.0  Female      Graduate
52                0.0  Female      Graduate
80                0.0  Female      Graduate
374               0.0  Female      Graduate
328               0.0  Female      Graduate
184               0.0  Female      Graduate
353               0.0  Female      Graduate
307               0.0  Female      Graduate
399               0.0  Female      Graduate
548               0.0  Female      Graduate
501               0.0  Female      Graduate
145               0.0  Female      Graduate
286               0.0  Female      Graduate
541               0.0  Female      Graduate
473               0.0  Female      Graduate
125               0.0  Female      Graduate
45                0.0  Female      Graduate
136               0.0  Female      Graduate
310               0.0  Female      Graduate
556               0.0  Female      Graduate
206               0.0  Female      Graduate
17                0.0  Female      Graduate
339               0.0  Female      Graduate
396               0.0  Female      Graduate
609               0.0  Female      Graduate
329               0.0  Female      Graduate
415               0.0  Female      Graduate
312               0.0  Female      Graduate
370               0.0  Female      Graduate
283               0.0  Female      Graduate
341               0.0  Female      Graduate
121               0.0  Female      Graduate
582               0.0  Female      Graduate
270               0.0  Female      Graduate
568               0.0  Female      Graduate
493               0.0  Female  Not Graduate
414               0.0  Female  Not Graduate
480               0.0  Female  Not Graduate
439               0.0  Female  Not Graduate
534               0.0  Female  Not Graduate
279               0.0  Female  Not Graduate
205               0.0  Female  Not Graduate
197               0.0  Female  Not Graduate
544               0.0  Female  Not Graduate
50                0.0  Female  Not Graduate
519               0.0  Female  Not Graduate
421               0.0  Female  Not Graduate
587               0.0  Female  Not Graduate
407               0.0  Female  Not Graduate
403               0.0  Female  Not Graduate
130               0.0    Male      Graduate
369               0.0    Male      Graduate
333               0.0    Male      Graduate
308               0.0    Male      Graduate
506               0.0    Male      Graduate
278               0.0    Male      Graduate
432               0.0    Male      Graduate
536               0.0    Male      Graduate
514               0.0    Male      Graduate
351               0.0    Male      Graduate
258               0.0    Male      Graduate
381               0.0    Male      Graduate
161               0.0    Male      Graduate
83                0.0    Male      Graduate
594               0.0    Male      Graduate
348               0.0    Male      Graduate
65                0.0    Male      Graduate
159               0.0    Male      Graduate
236               0.0    Male      Graduate
152               0.0    Male      Graduate
138               0.0    Male      Graduate
483               0.0    Male      Graduate
350               0.0    Male      Graduate
530               0.0    Male      Graduate
562               0.0    Male      Graduate
88                0.0    Male      Graduate
499               0.0    Male      Graduate
276               0.0    Male      Graduate
229               0.0    Male      Graduate
254               0.0    Male      Graduate
25                0.0    Male      Graduate
189               0.0    Male      Graduate
508               0.0    Male      Graduate
196               0.0    Male      Graduate
173               0.0    Male      Graduate
349               0.0    Male      Graduate
438               0.0    Male      Graduate
440               0.0    Male      Graduate
289               0.0    Male      Graduate
518               0.0    Male      Graduate
38                0.0    Male      Graduate
327               0.0    Male      Graduate
165               0.0    Male      Graduate
129               0.0    Male      Graduate
598               0.0    Male      Graduate
441               0.0    Male      Graduate
76                0.0    Male      Graduate
89                0.0    Male      Graduate
118               0.0    Male      Graduate
142               0.0    Male      Graduate
223               0.0    Male      Graduate
444               0.0    Male      Graduate
457               0.0    Male      Graduate
70                0.0    Male      Graduate
603               0.0    Male      Graduate
294               0.0    Male      Graduate
225               0.0    Male      Graduate
141               0.0    Male      Graduate
191               0.0    Male      Graduate
558               0.0    Male      Graduate
579               0.0    Male      Graduate
459               0.0    Male      Graduate
345               0.0    Male      Graduate
411               0.0    Male      Graduate
242               0.0    Male      Graduate
545               0.0    Male      Graduate
462               0.0    Male      Graduate
151               0.0    Male      Graduate
101               0.0    Male      Graduate
265               0.0    Male      Graduate
273               0.0    Male      Graduate
452               0.0    Male      Graduate
547               0.0    Male      Graduate
47                0.0    Male      Graduate
222               0.0    Male      Graduate
433               0.0    Male      Graduate
593               0.0    Male      Graduate
4                 0.0    Male      Graduate
364               0.0    Male      Graduate
465               0.0    Male      Graduate
304               0.0    Male      Graduate
290               0.0    Male      Graduate
419               0.0    Male      Graduate
420               0.0    Male      Graduate
214               0.0    Male      Graduate
110               0.0    Male      Graduate
85                0.0    Male      Graduate
388               0.0    Male      Graduate
271               0.0    Male      Graduate
216               0.0    Male      Graduate
57                0.0    Male      Graduate
43                0.0    Male      Graduate
261               0.0    Male      Graduate
554               0.0    Male      Graduate
99                0.0    Male      Graduate
90                0.0    Male      Graduate
217               0.0    Male      Graduate
377               0.0    Male      Graduate
362               0.0    Male      Graduate
326               0.0    Male      Graduate
167               0.0    Male      Graduate
482               0.0    Male      Graduate
264               0.0    Male      Graduate
380               0.0    Male      Graduate
224               0.0    Male      Graduate
383               0.0    Male      Graduate
209               0.0    Male      Graduate
272               0.0    Male      Graduate
149               0.0    Male      Graduate
15                0.0    Male      Graduate
389               0.0    Male      Graduate
367               0.0    Male      Graduate
93                0.0    Male      Graduate
143               0.0    Male      Graduate
26                0.0    Male      Graduate
425               0.0    Male      Graduate
158               0.0    Male      Graduate
60                0.0    Male      Graduate
185               0.0    Male      Graduate
194               0.0    Male      Graduate
375               0.0    Male      Graduate
245               0.0    Male      Graduate
392               0.0    Male      Graduate
287               0.0    Male      Graduate
494               0.0    Male      Graduate
150               0.0    Male      Graduate
456               0.0    Male      Graduate
114               0.0    Male      Graduate
175               0.0    Male      Graduate
19                0.0    Male      Graduate
320               0.0    Male      Graduate
13                0.0    Male      Graduate
33                0.0    Male      Graduate
75                0.0    Male      Graduate
418               0.0    Male      Graduate
281               0.0    Male      Graduate
497               0.0    Male      Graduate
469               0.0    Male      Graduate
577               0.0    Male      Graduate
526               0.0    Male      Graduate
549               0.0    Male      Graduate
608               0.0    Male      Graduate
431               0.0    Male      Graduate
87                0.0    Male      Graduate
586               0.0    Male      Graduate
569               0.0    Male      Graduate
402               0.0    Male      Graduate
134               0.0    Male      Graduate
422               0.0    Male      Graduate
36                0.0    Male      Graduate
434               0.0    Male      Graduate
464               0.0    Male      Graduate
331               0.0    Male      Graduate
424               0.0    Male      Graduate
56                0.0    Male      Graduate
366               0.0    Male      Graduate
363               0.0    Male      Graduate
397               0.0    Male      Graduate
453               0.0    Male      Graduate
249               0.0    Male      Graduate
581               0.0    Male      Graduate
285               0.0    Male      Graduate
317               0.0    Male      Graduate
428               0.0    Male      Graduate
454               0.0    Male      Graduate
199               0.0    Male      Graduate
72                0.0    Male      Graduate
40                0.0    Male      Graduate
277               0.0    Male      Graduate
193               0.0    Male      Graduate
42                0.0    Male      Graduate
164               0.0    Male      Graduate
489               0.0    Male      Graduate
131               0.0    Male      Graduate
31                0.0    Male      Graduate
182               0.0    Male      Graduate
378               0.0    Male      Graduate
132               0.0    Male      Graduate
566               0.0    Male      Graduate
513               0.0    Male      Graduate
181               0.0    Male      Graduate
2                 0.0    Male      Graduate
168               0.0    Male      Graduate
220               0.0    Male      Graduate
208               0.0    Male      Graduate
187               0.0    Male      Graduate
590               0.0    Male      Graduate
447               0.0    Male      Graduate
521               0.0    Male      Graduate
154               0.0    Male      Graduate
97                0.0    Male      Graduate
436               0.0    Male      Graduate
41                0.0    Male      Graduate
231               0.0    Male      Graduate
133               0.0    Male      Graduate
0                 0.0    Male      Graduate
95                0.0    Male      Graduate
103               0.0    Male      Graduate
35                0.0    Male      Graduate
127               0.0    Male      Graduate
437               0.0    Male      Graduate
284               0.0    Male      Graduate
524               0.0    Male      Graduate
412               0.0    Male  Not Graduate
250               0.0    Male  Not Graduate
124               0.0    Male  Not Graduate
553               0.0    Male  Not Graduate
62                0.0    Male  Not Graduate
192               0.0    Male  Not Graduate
601               0.0    Male  Not Graduate
112               0.0    Male  Not Graduate
18                0.0    Male  Not Graduate
365               0.0    Male  Not Graduate
386               0.0    Male  Not Graduate
563               0.0    Male  Not Graduate
529               0.0    Male  Not Graduate
66                0.0    Male  Not Graduate
535               0.0    Male  Not Graduate
504               0.0    Male  Not Graduate
244               0.0    Male  Not Graduate
107               0.0    Male  Not Graduate
3                 0.0    Male  Not Graduate
232               0.0    Male  Not Graduate
565               0.0    Male  Not Graduate
22                0.0    Male  Not Graduate
98                0.0    Male  Not Graduate
256               0.0    Male  Not Graduate
406               0.0    Male  Not Graduate
311               0.0    Male  Not Graduate
492               0.0    Male  Not Graduate
39                0.0    Male  Not Graduate
595               0.0    Male  Not Graduate
413               0.0    Male  Not Graduate
398               0.0    Male  Not Graduate
496               0.0    Male  Not Graduate
20                0.0    Male  Not Graduate
252               0.0    Male  Not Graduate
179               0.0    Male  Not Graduate
358               0.0    Male  Not Graduate
510               0.0    Male  Not Graduate
160               0.0    Male  Not Graduate
490               0.0    Male  Not Graduate
44                0.0    Male  Not Graduate
170               0.0    Male  Not Graduate
6                 0.0    Male  Not Graduate
300               0.0    Male  Not Graduate
174               0.0    Male  Not Graduate
546               0.0    Male  Not Graduate
538               0.0    Male  Not Graduate
401               0.0    Male  Not Graduate
429               0.0    Male  Not Graduate
207               0.0    Male  Not Graduate
190               0.0    Male  Not Graduate
28                0.0    Male  Not Graduate
94                0.0    Male  Not Graduate
387               0.0    Male  Not Graduate
305               0.0    Male  Not Graduate
605               0.0    Male  Not Graduate
188               0.0     NaN      Graduate
460               0.0     NaN      Graduate
314               0.0     NaN      Graduate
576               0.0     NaN      Graduate
467               0.0     NaN      Graduate
507               0.0     NaN      Graduate
588               0.0     NaN      Graduate
561               1.0  Female      Graduate
604               1.0  Female      Graduate
54                1.0  Female      Graduate
416               1.0  Female      Graduate
262               1.0  Female      Graduate
430               1.0  Female      Graduate
540               1.0  Female      Graduate
297               1.0  Female      Graduate
318               1.0  Female      Graduate
238               1.0  Female      Graduate
495               1.0  Female      Graduate
542               1.0  Female      Graduate
269               1.0  Female      Graduate
360               1.0  Female      Graduate
509               1.0  Female      Graduate
113               1.0  Female      Graduate
463               1.0  Female  Not Graduate
426               1.0  Female  Not Graduate
410               1.0  Female  Not Graduate
487               1.0    Male      Graduate
325               1.0    Male      Graduate
9                 1.0    Male      Graduate
260               1.0    Male      Graduate
21                1.0    Male      Graduate
67                1.0    Male      Graduate
183               1.0    Male      Graduate
611               1.0    Male      Graduate
511               1.0    Male      Graduate
212               1.0    Male      Graduate
30                1.0    Male      Graduate
296               1.0    Male      Graduate
533               1.0    Male      Graduate
157               1.0    Male      Graduate
570               1.0    Male      Graduate
115               1.0    Male      Graduate
180               1.0    Male      Graduate
58                1.0    Male      Graduate
368               1.0    Male      Graduate
606               1.0    Male      Graduate
585               1.0    Male      Graduate
195               1.0    Male      Graduate
235               1.0    Male      Graduate
470               1.0    Male      Graduate
128               1.0    Male      Graduate
156               1.0    Male      Graduate
336               1.0    Male      Graduate
552               1.0    Male      Graduate
319               1.0    Male      Graduate
408               1.0    Male      Graduate
443               1.0    Male      Graduate
24                1.0    Male      Graduate
584               1.0    Male      Graduate
234               1.0    Male      Graduate
445               1.0    Male      Graduate
1                 1.0    Male      Graduate
248               1.0    Male      Graduate
162               1.0    Male      Graduate
330               1.0    Male      Graduate
178               1.0    Male      Graduate
275               1.0    Male      Graduate
385               1.0    Male      Graduate
299               1.0    Male      Graduate
373               1.0    Male      Graduate
77                1.0    Male      Graduate
423               1.0    Male      Graduate
578               1.0    Male      Graduate
32                1.0    Male      Graduate
230               1.0    Male      Graduate
105               1.0    Male      Graduate
239               1.0    Male      Graduate
303               1.0    Male      Graduate
498               1.0    Male      Graduate
478               1.0    Male      Graduate
117               1.0    Male      Graduate
357               1.0    Male      Graduate
186               1.0    Male      Graduate
583               1.0    Male      Graduate
84                1.0    Male      Graduate
46                1.0    Male      Graduate
147               1.0    Male      Graduate
555               1.0    Male      Graduate
63                1.0    Male      Graduate
81                1.0    Male      Graduate
253               1.0    Male  Not Graduate
449               1.0    Male  Not Graduate
491               1.0    Male  Not Graduate
527               1.0    Male  Not Graduate
280               1.0    Male  Not Graduate
342               1.0    Male  Not Graduate
241               1.0    Male  Not Graduate
503               1.0    Male  Not Graduate
247               1.0    Male  Not Graduate
203               1.0    Male  Not Graduate
485               1.0    Male  Not Graduate
543               1.0    Male  Not Graduate
471               1.0    Male  Not Graduate
315               1.0    Male  Not Graduate
16                1.0    Male  Not Graduate
528               1.0    Male  Not Graduate
200               1.0    Male  Not Graduate
551               1.0    Male  Not Graduate
334               1.0     NaN      Graduate
82                2.0  Female      Graduate
251               2.0  Female      Graduate
219               2.0  Female      Graduate
29                2.0  Female      Graduate
516               2.0  Female      Graduate
146               2.0  Female      Graduate

In [63]:
dataset[['Experience_Years', 'Gender', 'Education', 'Salary * 10E4']].head (500)

     Experience_Years  Gender     Education  Salary * 10E4
233               0.0  Female      Graduate          280.0
119               0.0  Female      Graduate          259.0
148               0.0  Female      Graduate          225.0
210               0.0  Female      Graduate          214.0
404               0.0  Female      Graduate          194.0
559               0.0  Female      Graduate          182.0
382               0.0  Female      Graduate          156.0
116               0.0  Female      Graduate          154.0
298               0.0  Female      Graduate          151.0
37                0.0  Female      Graduate          144.0
49                0.0  Female      Graduate          144.0
111               0.0  Female      Graduate          139.0
96                0.0  Female      Graduate          137.0
122               0.0  Female      Graduate          137.0
69                0.0  Female      Graduate          136.0
306               0.0  Female      Graduate          135.0
268               0.0  Female      Graduate          135.0
613               0.0  Female      Graduate          133.0
323               0.0  Female      Graduate          132.0
302               0.0  Female      Graduate          132.0
354               0.0  Female      Graduate          130.0
237               0.0  Female      Graduate          122.0
48                0.0  Female      Graduate          120.0
51                0.0  Female      Graduate          120.0
263               0.0  Female      Graduate          120.0
64                0.0  Female      Graduate          116.0
405               0.0  Female      Graduate          115.0
288               0.0  Female      Graduate          115.0
500               0.0  Female      Graduate          113.0
198               0.0  Female      Graduate          113.0
166               0.0  Female      Graduate          112.0
52                0.0  Female      Graduate          112.0
80                0.0  Female      Graduate          111.0
374               0.0  Female      Graduate          110.0
328               0.0  Female      Graduate          110.0
184               0.0  Female      Graduate          108.0
353               0.0  Female      Graduate          105.0
307               0.0  Female      Graduate          104.0
399               0.0  Female      Graduate          103.0
548               0.0  Female      Graduate          103.0
501               0.0  Female      Graduate          100.0
145               0.0  Female      Graduate          100.0
286               0.0  Female      Graduate           99.0
541               0.0  Female      Graduate           99.0
473               0.0  Female      Graduate           93.0
125               0.0  Female      Graduate           93.0
45                0.0  Female      Graduate           88.0
136               0.0  Female      Graduate           84.0
310               0.0  Female      Graduate           84.0
556               0.0  Female      Graduate           84.0
206               0.0  Female      Graduate           80.0
17                0.0  Female      Graduate           76.0
339               0.0  Female      Graduate           71.0
396               0.0  Female      Graduate           71.0
609               0.0  Female      Graduate           71.0
329               0.0  Female      Graduate           67.0
415               0.0  Female      Graduate           60.0
312               0.0  Female      Graduate           56.0
370               0.0  Female      Graduate           55.0
283               0.0  Female      Graduate           54.0
341               0.0  Female      Graduate           46.0
121               0.0  Female      Graduate           44.0
582               0.0  Female      Graduate           36.0
270               0.0  Female      Graduate           30.0
568               0.0  Female      Graduate            9.0
493               0.0  Female  Not Graduate          225.0
414               0.0  Female  Not Graduate          178.0
480               0.0  Female  Not Graduate          154.0
439               0.0  Female  Not Graduate          138.0
534               0.0  Female  Not Graduate          125.0
279               0.0  Female  Not Graduate          124.0
205               0.0  Female  Not Graduate          120.0
197               0.0  Female  Not Graduate          120.0
544               0.0  Female  Not Graduate          102.0
50                0.0  Female  Not Graduate          100.0
519               0.0  Female  Not Graduate           95.0
421               0.0  Female  Not Graduate           80.0
587               0.0  Female  Not Graduate           70.0
407               0.0  Female  Not Graduate           66.0
403               0.0  Female  Not Graduate           53.0
130               0.0    Male      Graduate          650.0
369               0.0    Male      Graduate          570.0
333               0.0    Male      Graduate          490.0
308               0.0    Male      Graduate          480.0
506               0.0    Male      Graduate          480.0
278               0.0    Male      Graduate          436.0
432               0.0    Male      Graduate          405.0
536               0.0    Male      Graduate          324.0
514               0.0    Male      Graduate          311.0
351               0.0    Male      Graduate          308.0
258               0.0    Male      Graduate          304.0
381               0.0    Male      Graduate          296.0
161               0.0    Male      Graduate          275.0
83                0.0    Male      Graduate          265.0
594               0.0    Male      Graduate          260.0
348               0.0    Male      Graduate          259.0
65                0.0    Male      Graduate          258.0
159               0.0    Male      Graduate          255.0
236               0.0    Male      Graduate          255.0
152               0.0    Male      Graduate          244.0
138               0.0    Male      Graduate          242.0
483               0.0    Male      Graduate          234.0
350               0.0    Male      Graduate          228.0
530               0.0    Male      Graduate          216.0
562               0.0    Male      Graduate          211.0
88                0.0    Male      Graduate          210.0
499               0.0    Male      Graduate          209.0
276               0.0    Male      Graduate          207.0
229               0.0    Male      Graduate          200.0
254               0.0    Male      Graduate          192.0
25                0.0    Male      Graduate          191.0
189               0.0    Male      Graduate          188.0
508               0.0    Male      Graduate          188.0
196               0.0    Male      Graduate          187.0
173               0.0    Male      Graduate          187.0
349               0.0    Male      Graduate          187.0
438               0.0    Male      Graduate          187.0
440               0.0    Male      Graduate          187.0
289               0.0    Male      Graduate          187.0
518               0.0    Male      Graduate          185.0
38                0.0    Male      Graduate          184.0
327               0.0    Male      Graduate          184.0
165               0.0    Male      Graduate          182.0
129               0.0    Male      Graduate          182.0
598               0.0    Male      Graduate          180.0
441               0.0    Male      Graduate          180.0
76                0.0    Male      Graduate          176.0
89                0.0    Male      Graduate          175.0
118               0.0    Male      Graduate          175.0
142               0.0    Male      Graduate          175.0
223               0.0    Male      Graduate          175.0
444               0.0    Male      Graduate          175.0
457               0.0    Male      Graduate          173.0
70                0.0    Male      Graduate          172.0
603               0.0    Male      Graduate          172.0
294               0.0    Male      Graduate          172.0
225               0.0    Male      Graduate          170.0
141               0.0    Male      Graduate          168.0
191               0.0    Male      Graduate          164.0
558               0.0    Male      Graduate          162.0
579               0.0    Male      Graduate          161.0
459               0.0    Male      Graduate          160.0
345               0.0    Male      Graduate          160.0
411               0.0    Male      Graduate          160.0
242               0.0    Male      Graduate          155.0
545               0.0    Male      Graduate          155.0
462               0.0    Male      Graduate          153.0
151               0.0    Male      Graduate          152.0
101               0.0    Male      Graduate          151.0
265               0.0    Male      Graduate          151.0
273               0.0    Male      Graduate          150.0
452               0.0    Male      Graduate          149.0
547               0.0    Male      Graduate          145.0
47                0.0    Male      Graduate          144.0
222               0.0    Male      Graduate          144.0
433               0.0    Male      Graduate          143.0
593               0.0    Male      Graduate          142.0
4                 0.0    Male      Graduate          141.0
364               0.0    Male      Graduate          141.0
465               0.0    Male      Graduate          140.0
304               0.0    Male      Graduate          140.0
290               0.0    Male      Graduate          139.0
419               0.0    Male      Graduate          138.0
420               0.0    Male      Graduate          138.0
214               0.0    Male      Graduate          137.0
110               0.0    Male      Graduate          136.0
85                0.0    Male      Graduate          136.0
388               0.0    Male      Graduate          136.0
271               0.0    Male      Graduate          136.0
216               0.0    Male      Graduate          135.0
57                0.0    Male      Graduate          135.0
43                0.0    Male      Graduate          134.0
261               0.0    Male      Graduate          134.0
554               0.0    Male      Graduate          132.0
99                0.0    Male      Graduate          131.0
90                0.0    Male      Graduate          131.0
217               0.0    Male      Graduate          131.0
377               0.0    Male      Graduate          130.0
362               0.0    Male      Graduate          130.0
326               0.0    Male      Graduate          130.0
167               0.0    Male      Graduate          129.0
482               0.0    Male      Graduate          128.0
264               0.0    Male      Graduate          128.0
380               0.0    Male      Graduate          128.0
224               0.0    Male      Graduate          128.0
383               0.0    Male      Graduate          128.0
209               0.0    Male      Graduate          127.0
272               0.0    Male      Graduate          126.0
149               0.0    Male      Graduate          125.0
15                0.0    Male      Graduate          125.0
389               0.0    Male      Graduate          125.0
367               0.0    Male      Graduate          124.0
93                0.0    Male      Graduate          122.0
143               0.0    Male      Graduate          122.0
26                0.0    Male      Graduate          122.0
425               0.0    Male      Graduate          121.0
158               0.0    Male      Graduate          120.0
60                0.0    Male      Graduate          120.0
185               0.0    Male      Graduate          120.0
194               0.0    Male      Graduate          120.0
375               0.0    Male      Graduate          120.0
245               0.0    Male      Graduate          120.0
392               0.0    Male      Graduate          120.0
287               0.0    Male      Graduate          120.0
494               0.0    Male      Graduate          119.0
150               0.0    Male      Graduate          118.0
456               0.0    Male      Graduate          118.0
114               0.0    Male      Graduate          118.0
175               0.0    Male      Graduate          116.0
19                0.0    Male      Graduate          115.0
320               0.0    Male      Graduate          115.0
13                0.0    Male      Graduate          114.0
33                0.0    Male      Graduate          114.0
75                0.0    Male      Graduate          113.0
418               0.0    Male      Graduate          112.0
281               0.0    Male      Graduate          112.0
497               0.0    Male      Graduate          111.0
469               0.0    Male      Graduate          110.0
577               0.0    Male      Graduate          110.0
526               0.0    Male      Graduate          110.0
549               0.0    Male      Graduate          110.0
608               0.0    Male      Graduate          108.0
431               0.0    Male      Graduate          105.0
87                0.0    Male      Graduate          104.0
586               0.0    Male      Graduate          104.0
569               0.0    Male      Graduate          104.0
402               0.0    Male      Graduate          103.0
134               0.0    Male      Graduate          102.0
422               0.0    Male      Graduate          100.0
36                0.0    Male      Graduate          100.0
434               0.0    Male      Graduate          100.0
464               0.0    Male      Graduate           98.0
331               0.0    Male      Graduate           98.0
424               0.0    Male      Graduate           96.0
56                0.0    Male      Graduate           96.0
366               0.0    Male      Graduate           96.0
363               0.0    Male      Graduate           95.0
397               0.0    Male      Graduate           95.0
453               0.0    Male      Graduate           90.0
249               0.0    Male      Graduate           90.0
581               0.0    Male      Graduate           90.0
285               0.0    Male      Graduate           89.0
317               0.0    Male      Graduate           88.0
428               0.0    Male      Graduate           87.0
454               0.0    Male      Graduate           84.0
199               0.0    Male      Graduate           83.0
72                0.0    Male      Graduate           81.0
40                0.0    Male      Graduate           80.0
277               0.0    Male      Graduate           80.0
193               0.0    Male      Graduate           76.0
42                0.0    Male      Graduate           75.0
164               0.0    Male      Graduate           75.0
489               0.0    Male      Graduate           75.0
131               0.0    Male      Graduate           74.0
31                0.0    Male      Graduate           74.0
182               0.0    Male      Graduate           73.0
378               0.0    Male      Graduate           71.0
132               0.0    Male      Graduate           70.0
566               0.0    Male      Graduate           70.0
513               0.0    Male      Graduate           70.0
181               0.0    Male      Graduate           67.0
2                 0.0    Male      Graduate           66.0
168               0.0    Male      Graduate           63.0
220               0.0    Male      Graduate           60.0
208               0.0    Male      Graduate           59.0
187               0.0    Male      Graduate           58.0
590               0.0    Male      Graduate           56.0
447               0.0    Male      Graduate           55.0
521               0.0    Male      Graduate           55.0
154               0.0    Male      Graduate           50.0
97                0.0    Male      Graduate           50.0
436               0.0    Male      Graduate           50.0
41                0.0    Male      Graduate           47.0
231               0.0    Male      Graduate           42.0
133               0.0    Male      Graduate           25.0
0                 0.0    Male      Graduate            0.0
95                0.0    Male      Graduate            NaN
103               0.0    Male      Graduate            NaN
35                0.0    Male      Graduate            NaN
127               0.0    Male      Graduate            NaN
437               0.0    Male      Graduate            NaN
284               0.0    Male      Graduate            NaN
524               0.0    Male      Graduate            NaN
412               0.0    Male  Not Graduate          218.0
250               0.0    Male  Not Graduate          201.0
124               0.0    Male  Not Graduate          194.0
553               0.0    Male  Not Graduate          181.0
62                0.0    Male  Not Graduate          165.0
192               0.0    Male  Not Graduate          160.0
601               0.0    Male  Not Graduate          155.0
112               0.0    Male  Not Graduate          152.0
18                0.0    Male  Not Graduate          133.0
365               0.0    Male  Not Graduate          133.0
386               0.0    Male  Not Graduate          132.0
563               0.0    Male  Not Graduate          132.0
529               0.0    Male  Not Graduate          130.0
66                0.0    Male  Not Graduate          126.0
535               0.0    Male  Not Graduate          126.0
504               0.0    Male  Not Graduate          124.0
244               0.0    Male  Not Graduate          123.0
107               0.0    Male  Not Graduate          120.0
3                 0.0    Male  Not Graduate          120.0
232               0.0    Male  Not Graduate          120.0
565               0.0    Male  Not Graduate          120.0
22                0.0    Male  Not Graduate          116.0
98                0.0    Male  Not Graduate          115.0
256               0.0    Male  Not Graduate          115.0
406               0.0    Male  Not Graduate          115.0
311               0.0    Male  Not Graduate          111.0
492               0.0    Male  Not Graduate          110.0
39                0.0    Male  Not Graduate          110.0
595               0.0    Male  Not Graduate          110.0
413               0.0    Male  Not Graduate          110.0
398               0.0    Male  Not Graduate          109.0
496               0.0    Male  Not Graduate          107.0
20                0.0    Male  Not Graduate          104.0
252               0.0    Male  Not Graduate          104.0
179               0.0    Male  Not Graduate          102.0
358               0.0    Male  Not Graduate          100.0
510               0.0    Male  Not Graduate          100.0
160               0.0    Male  Not Graduate           98.0
490               0.0    Male  Not Graduate           96.0
44                0.0    Male  Not Graduate           96.0
170               0.0    Male  Not Graduate           95.0
6                 0.0    Male  Not Graduate           95.0
300               0.0    Male  Not Graduate           93.0
174               0.0    Male  Not Graduate           87.0
546               0.0    Male  Not Graduate           80.0
538               0.0    Male  Not Graduate           66.0
401               0.0    Male  Not Graduate           65.0
429               0.0    Male  Not Graduate           60.0
207               0.0    Male  Not Graduate           55.0
190               0.0    Male  Not Graduate           48.0
28                0.0    Male  Not Graduate           35.0
94                0.0    Male  Not Graduate           25.0
387               0.0    Male  Not Graduate            NaN
305               0.0    Male  Not Graduate            NaN

In [66]:
dataset ['Salary * 10E4'] .nlargest(10)

171    700.0
130    650.0
561    600.0
155    600.0
369    570.0
487    500.0
604    496.0
177    495.0
333    490.0
308    480.0
Name: Salary * 10E4, dtype: float64

In [69]:
dataset.nlargest(10,'Salary * 10E4')

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
171,172,NaN,No,3.0,Graduate,No,51763,700.0,1.0,Urban,Y
130,131,Male,Yes,0.0,Graduate,Yes,20166,650.0,NaN,Urban,Y
561,562,Female,No,1.0,Graduate,Yes,19484,600.0,1.0,Semiurban,Y
155,156,Male,No,3.0,Graduate,No,39999,600.0,0.0,Semiurban,Y
369,370,Male,No,0.0,Graduate,No,19730,570.0,1.0,Rural,N
487,488,Male,No,1.0,Graduate,No,18333,500.0,1.0,Urban,N
604,605,Female,No,1.0,Graduate,No,12000,496.0,1.0,Semiurban,Y
177,178,Male,No,3.0,Graduate,No,5516,495.0,0.0,Semiurban,N
333,334,Male,No,0.0,Graduate,NaN,63337,490.0,1.0,Urban,Y
308,309,Male,Yes,0.0,Graduate,No,20233,480.0,1.0,Rural,N

In [70]:
dataset.head(500)

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
233,234,Female,Yes,0.0,Graduate,No,8333,280.0,1.0,Semiurban,Y
119,120,Female,Yes,0.0,Graduate,No,10408,259.0,1.0,Urban,Y
148,149,Female,Yes,0.0,Graduate,No,10000,225.0,1.0,Rural,N
210,211,Female,Yes,0.0,Graduate,No,10000,214.0,1.0,Semiurban,N
404,405,Female,Yes,0.0,Graduate,Yes,7441,194.0,1.0,Rural,N
559,560,Female,No,0.0,Graduate,No,4180,182.0,1.0,Semiurban,Y
382,383,Female,Yes,0.0,Graduate,No,6000,156.0,1.0,Urban,Y
116,117,Female,No,0.0,Graduate,No,3167,154.0,1.0,Semiurban,Y
298,299,Female,Yes,0.0,Graduate,No,5000,151.0,1.0,Rural,N
37,38,Female,No,0.0,Graduate,No,3667,144.0,1.0,Semiurban,Y
49,50,Female,Yes,0.0,Graduate,No,4000,144.0,1.0,Semiurban,Y
111,112,Female,No,0.0,Graduate,NaN,2929,139.0,1.0,Semiurban,Y
96,97,Female,No,0.0,Graduate,No,2484,137.0,1.0,Semiurban,Y
122,123,Female,Yes,0.0,Graduate,No,2137,137.0,0.0,Semiurban,Y
69,70,Female,Yes,0.0,Graduate,No,4300,136.0,0.0,Semiurban,N
306,307,Female,Yes,0.0,Graduate,No,3762,135.0,1.0,Rural,Y
268,269,Female,Yes,0.0,Graduate,NaN,3418,135.0,1.0,Rural,N
613,614,Female,Yes,0.0,Graduate,Yes,4583,133.0,0.0,Semiurban,N
323,324,Female,Yes,0.0,Graduate,No,3166,132.0,NaN,Rural,Y
302,303,Female,Yes,0.0,Graduate,No,5000,132.0,1.0,Rural,Y
354,355,Female,No,0.0,Graduate,No,2423,130.0,1.0,Semiurban,Y
237,238,Female,Yes,0.0,Graduate,Yes,3463,122.0,NaN,Urban,Y
48,49,Female,No,0.0,Graduate,No,2645,120.0,0.0,Urban,N
51,52,Female,Yes,0.0,Graduate,No,3086,120.0,1.0,Semiurban,Y
263,264,Female,Yes,0.0,Graduate,No,7200,120.0,1.0,Rural,Y
64,65,Female,Yes,0.0,Graduate,No,4166,116.0,0.0,Semiurban,N
405,406,Female,Yes,0.0,Graduate,No,4547,115.0,1.0,Semiurban,Y
288,289,Female,Yes,0.0,Graduate,No,4124,115.0,1.0,Semiurban,Y
500,501,Female,Yes,0.0,Graduate,No,645,113.0,1.0,Rural,Y
198,199,Female,No,0.0,Graduate,No,3416,113.0,NaN,Semiurban,Y
166,167,Female,No,0.0,Graduate,No,4583,112.0,1.0,Rural,N
52,53,Female,Yes,0.0,Graduate,No,4230,112.0,1.0,Semiurban,N
80,81,Female,Yes,0.0,Graduate,No,3846,111.0,1.0,Semiurban,Y
374,375,Female,Yes,0.0,Graduate,NaN,2764,110.0,1.0,Urban,Y
328,329,Female,No,0.0,Graduate,No,4333,110.0,1.0,Urban,N
184,185,Female,No,0.0,Graduate,No,3625,108.0,1.0,Semiurban,Y
353,354,Female,No,0.0,Graduate,Yes,5500,105.0,0.0,Rural,N
307,308,Female,Yes,0.0,Graduate,No,2400,104.0,0.0,Urban,N
399,400,Female,Yes,0.0,Graduate,No,1500,103.0,0.0,Semiurban,N
548,549,Female,Yes,0.0,Graduate,No,5000,103.0,0.0,Semiurban,N
501,502,Female,Yes,0.0,Graduate,No,3159,100.0,1.0,Semiurban,Y
145,146,Female,No,0.0,Graduate,No,2330,100.0,1.0,Semiurban,Y
286,287,Female,Yes,0.0,Graduate,Yes,2600,99.0,1.0,Semiurban,N
541,542,Female,Yes,0.0,Graduate,No,2138,99.0,0.0,Semiurban,N
473,474,Female,Yes,0.0,Graduate,Yes,2500,93.0,NaN,Urban,Y
125,126,Female,Yes,0.0,Graduate,No,3692,93.0,NaN,Rural,Y
45,46,Female,Yes,0.0,Graduate,No,3410,88.0,1.0,Urban,Y
136,137,Female,No,0.0,Graduate,No,4583,84.0,1.0,Rural,N
310,311,Female,Yes,0.0,Graduate,No,2917,84.0,1.0,Semiurban,Y
556,557,Female,Yes,0.0,Graduate,No,2667,84.0,NaN,Urban,Y
206,207,Female,Yes,0.0,Graduate,No,3244,80.0,1.0,Urban,Y
17,18,Female,Yes,0.0,Graduate,No,3510,76.0,0.0,Urban,N
339,340,Female,Yes,0.0,Graduate,No,4160,71.0,1.0,Semiurban,Y
396,397,Female,Yes,0.0,Graduate,No,3180,71.0,0.0,Urban,N
609,610,Female,Yes,0.0,Graduate,No,2900,71.0,1.0,Rural,Y
329,330,Female,Yes,0.0,Graduate,No,2500,67.0,1.0,Urban,Y
415,416,Female,Yes,0.0,Graduate,No,2995,60.0,1.0,Urban,Y
312,313,Female,Yes,0.0,Graduate,No,2507,56.0,1.0,Rural,Y
370,371,Female,Yes,0.0,Graduate,Yes,15759,55.0,1.0,Semiurban,Y
283,284,Female,Yes,0.0,Graduate,No,1811,54.0,1.0,Urban,Y
341,342,Female,Yes,0.0,Graduate,No,2378,46.0,1.0,Rural,N
121,122,Female,Yes,0.0,Graduate,No,4166,44.0,1.0,Semiurban,Y
582,583,Female,No,0.0,Graduate,No,3166,36.0,1.0,Semiurban,Y
270,271,Female,Yes,0.0,Graduate,No,3237,30.0,1.0,Urban,Y
568,569,Female,Yes,0.0,Graduate,No,2378,9.0,1.0,Urban,N
493,494,Female,Yes,0.0,Not Graduate,Yes,17263,225.0,1.0,Semiurban,Y
414,415,Female,No,0.0,Not Graduate,No,2149,178.0,0.0,Semiurban,N
480,481,Female,Yes,0.0,Not Graduate,No,4350,154.0,1.0,Rural,Y
439,440,Female,No,0.0,Not Graduate,Yes,7142,138.0,1.0,Rural,Y
534,535,Female,Yes,0.0,Not Graduate,Yes,18165,125.0,1.0,Urban,Y
279,280,Female,No,0.0,Not Graduate,No,4100,124.0,NaN,Rural,Y
205,206,Female,Yes,0.0,Not Graduate,No,4408,120.0,1.0,Semiurban,Y
197,198,Female,Yes,0.0,Not Graduate,No,1907,120.0,1.0,Urban,Y
544,545,Female,No,0.0,Not Graduate,No,3017,102.0,NaN,Semiurban,Y
50,51,Female,No,0.0,Not Graduate,No,1928,100.0,1.0,Semiurban,Y
519,520,Female,Yes,0.0,Not Graduate,No,3400,95.0,1.0,Rural,N
421,422,Female,Yes,0.0,Not Graduate,No,2720,80.0,0.0,Urban,N
587,588,Female,Yes,0.0,Not Graduate,No,2165,70.0,1.0,Semiurban,Y
407,408,Female,Yes,0.0,Not Graduate,No,2213,66.0,1.0,Rural,Y
403,404,Female,Yes,0.0,Not Graduate,No,1963,53.0,1.0,Semiurban,Y
130,131,Male,Yes,0.0,Graduate,Yes,20166,650.0,NaN,Urban,Y
369,370,Male,No,0.0,Graduate,No,19730,570.0,1.0,Rural,N
333,334,Male,No,0.0,Graduate,NaN,63337,490.0,1.0,Urban,Y
308,309,Male,Yes,0.0,Graduate,No,20233,480.0,1.0,Rural,N
506,507,Male,No,0.0,Graduate,No,20833,480.0,NaN,Urban,Y
278,279,Male,No,0.0,Graduate,No,14583,436.0,1.0,Semiurban,Y
432,433,Male,Yes,0.0,Graduate,NaN,12876,405.0,1.0,Semiurban,Y
536,537,Male,No,0.0,Graduate,No,6133,324.0,1.0,Urban,Y
514,515,Male,Yes,0.0,Graduate,No,5815,311.0,1.0,Rural,N
351,352,Male,Yes,0.0,Graduate,No,8750,308.0,1.0,Rural,N
258,259,Male,No,0.0,Graduate,No,14683,304.0,1.0,Rural,N
381,382,Male,Yes,0.0,Graduate,No,5941,296.0,1.0,Semiurban,Y
161,162,Male,No,0.0,Graduate,No,7933,275.0,1.0,Urban,N
83,84,Male,No,0.0,Graduate,No,6000,265.0,NaN,Semiurban,N
594,595,Male,No,0.0,Graduate,Yes,16120,260.0,1.0,Urban,Y
348,349,Male,No,0.0,Graduate,No,6333,259.0,NaN,Semiurban,Y
65,66,Male,No,0.0,Graduate,No,5726,258.0,1.0,Semiurban,N
159,160,Male,No,0.0,Graduate,No,4583,255.0,1.0,Semiurban,Y
236,237,Male,No,0.0,Graduate,NaN,5746,255.0,NaN,Urban,N
152,153,Male,Yes,0.0,Graduate,No,9166,244.0,1.0,Urban,N
138,139,Male,Yes,0.0,Graduate,No,14999,242.0,0.0,Semiurban,N
483,484,Male,No,0.0,Graduate,No,10833,234.0,1.0,Semiurban,Y
350,351,Male,No,0.0,Graduate,No,9083,228.0,1.0,Semiurban,Y
530,531,Male,No,0.0,Graduate,No,1025,216.0,NaN,Rural,Y
562,563,Male,No,0.0,Graduate,No,5923,211.0,1.0,Rural,Y
88,89,Male,Yes,0.0,Graduate,No,8566,210.0,1.0,Urban,Y
499,500,Male,Yes,0.0,Graduate,No,6283,209.0,0.0,Rural,N
276,277,Male,No,0.0,Graduate,No,3993,207.0,1.0,Semiurban,Y
229,230,Male,Yes,0.0,Graduate,Yes,6400,200.0,1.0,Rural,Y
254,255,Male,Yes,0.0,Graduate,Yes,16250,192.0,0.0,Urban,N
25,26,Male,No,0.0,Graduate,Yes,9560,191.0,1.0,Semiurban,Y
189,190,Male,No,0.0,Graduate,No,9328,188.0,1.0,Rural,Y
508,509,Male,No,0.0,Graduate,Yes,2479,188.0,1.0,Urban,Y
196,197,Male,Yes,0.0,Graduate,No,8333,187.0,1.0,Rural,Y
173,174,Male,No,0.0,Graduate,No,5708,187.0,1.0,Semiurban,Y
349,350,Male,No,0.0,Graduate,No,2625,187.0,1.0,Rural,Y
438,439,Male,Yes,0.0,Graduate,Yes,10416,187.0,0.0,Urban,N
440,441,Male,Yes,0.0,Graduate,No,3660,187.0,1.0,Semiurban,Y
289,290,Male,Yes,0.0,Graduate,No,9508,187.0,1.0,Rural,Y
518,519,Male,Yes,0.0,Graduate,No,4683,185.0,1.0,Semiurban,N
38,39,Male,Yes,0.0,Graduate,No,4166,184.0,1.0,Urban,Y
327,328,Male,No,0.0,Graduate,Yes,5818,184.0,1.0,Semiurban,Y
165,166,Male,No,0.0,Graduate,No,3707,182.0,1.0,Rural,Y
129,130,Male,No,0.0,Graduate,No,6080,182.0,NaN,Rural,N
598,599,Male,No,0.0,Graduate,Yes,9963,180.0,1.0,Rural,Y
441,442,Male,No,0.0,Graduate,No,7901,180.0,1.0,Rural,Y
76,77,Male,Yes,0.0,Graduate,No,3750,176.0,1.0,Urban,N
89,90,Male,No,0.0,Graduate,No,5695,175.0,1.0,Semiurban,Y
118,119,Male,No,0.0,Graduate,No,5568,175.0,1.0,Rural,N
142,143,Male,Yes,0.0,Graduate,Yes,6950,175.0,1.0,Semiurban,Y
223,224,Male,No,0.0,Graduate,No,7578,175.0,1.0,Semiurban,Y
444,445,Male,No,0.0,Graduate,No,7333,175.0,NaN,Rural,Y
457,458,Male,No,0.0,Graduate,No,3708,173.0,1.0,Urban,N
70,71,Male,No,0.0,Graduate,No,3208,172.0,1.0,Urban,Y
603,604,Male,Yes,0.0,Graduate,No,3676,172.0,1.0,Rural,Y
294,295,Male,No,0.0,Graduate,No,2383,172.0,1.0,Semiurban,Y
225,226,Male,No,0.0,Graduate,No,3250,170.0,1.0,Rural,N
141,142,Male,Yes,0.0,Graduate,No,5417,168.0,1.0,Urban,Y
191,192,Male,Yes,0.0,Graduate,No,12000,164.0,1.0,Semiurban,N
558,559,Male,No,0.0,Graduate,No,3887,162.0,1.0,Semiurban,Y
579,580,Male,Yes,0.0,Graduate,NaN,3182,161.0,1.0,Urban,Y
459,460,Male,No,0.0,Graduate,No,8334,160.0,1.0,Semiurban,N
345,346,Male,No,0.0,Graduate,No,2499,160.0,1.0,Semiurban,Y
411,412,Male,No,0.0,Graduate,NaN,6256,160.0,NaN,Urban,Y
242,243,Male,Yes,0.0,Graduate,No,2965,155.0,1.0,Urban,Y
545,546,Male,No,0.0,Graduate,No,2768,155.0,1.0,Rural,Y
462,463,Male,No,0.0,Graduate,No,3015,153.0,1.0,Rural,Y
151,152,Male,No,0.0,Graduate,Yes,2577,152.0,1.0,Rural,Y
101,102,Male,Yes,0.0,Graduate,No,4843,151.0,1.0,Semiurban,Y
265,266,Male,Yes,0.0,Graduate,No,4095,151.0,1.0,Rural,Y
273,274,Male,No,0.0,Graduate,No,2620,150.0,1.0,Semiurban,Y
452,453,Male,No,0.0,Graduate,No,3948,149.0,0.0,Rural,N
547,548,Male,Yes,0.0,Graduate,No,2526,145.0,1.0,Rural,Y
47,48,Male,No,0.0,Graduate,No,5821,144.0,1.0,Urban,Y
222,223,Male,Yes,0.0,Graduate,No,2971,144.0,1.0,Semiurban,Y
433,434,Male,No,0.0,Graduate,No,2425,143.0,1.0,Semiurban,Y
593,594,Male,No,0.0,Graduate,No,3859,142.0,1.0,Rural,Y
4,5,Male,Yes,0.0,Graduate,No,6000,141.0,1.0,Urban,Y
364,365,Male,Yes,0.0,Graduate,Yes,6822,141.0,1.0,Rural,Y
465,466,Male,Yes,0.0,Graduate,No,6000,140.0,1.0,Rural,Y
304,305,Male,Yes,0.0,Graduate,No,4000,140.0,1.0,Rural,Y
290,291,Male,No,0.0,Graduate,No,3075,139.0,1.0,Rural,Y
419,420,Male,No,0.0,Graduate,No,3246,138.0,1.0,Semiurban,Y
420,421,Male,No,0.0,Graduate,No,5829,138.0,1.0,Rural,Y
214,215,Male,No,0.0,Graduate,No,3173,137.0,1.0,Urban,Y
110,111,Male,Yes,0.0,Graduate,No,5316,136.0,1.0,Urban,Y
85,86,Male,Yes,0.0,Graduate,No,2366,136.0,1.0,Semiurban,Y
388,389,Male,No,0.0,Graduate,No,2333,136.0,1.0,Urban,Y
271,272,Male,No,0.0,Graduate,No,11146,136.0,1.0,Urban,Y
216,217,Male,No,0.0,Graduate,No,150,135.0,1.0,Rural,N
57,58,Male,No,0.0,Graduate,No,3366,135.0,1.0,Rural,N
43,44,Male,No,0.0,Graduate,No,3941,134.0,1.0,Semiurban,Y
261,262,Male,Yes,0.0,Graduate,No,2060,134.0,1.0,Semiurban,Y
554,555,Male,No,0.0,Graduate,No,3593,132.0,0.0,Rural,N
99,100,Male,No,0.0,Graduate,No,1759,131.0,1.0,Semiurban,Y
90,91,Male,No,0.0,Graduate,No,2958,131.0,1.0,Semiurban,Y
217,218,Male,No,0.0,Graduate,No,3727,131.0,1.0,Semiurban,Y
377,378,Male,No,0.0,Graduate,No,4310,130.0,NaN,Semiurban,Y
362,363,Male,No,0.0,Graduate,No,4750,130.0,1.0,Urban,Y
326,327,Male,Yes,0.0,Graduate,No,4917,130.0,0.0,Rural,Y
167,168,Male,No,0.0,Graduate,No,2439,129.0,1.0,Rural,Y
482,483,Male,No,0.0,Graduate,No,2083,128.0,1.0,Semiurban,Y
264,265,Male,Yes,0.0,Graduate,Yes,5166,128.0,1.0,Semiurban,Y
380,381,Male,No,0.0,Graduate,NaN,3333,128.0,1.0,Semiurban,Y
224,225,Male,No,0.0,Graduate,No,6250,128.0,1.0,Semiurban,Y
383,384,Male,Yes,0.0,Graduate,Yes,7167,128.0,1.0,Urban,Y
209,210,Male,Yes,0.0,Graduate,No,3418,127.0,1.0,Semiurban,N
272,273,Male,Yes,0.0,Graduate,No,2833,126.0,1.0,Rural,Y
149,150,Male,No,0.0,Graduate,No,4860,125.0,1.0,Semiurban,Y
15,16,Male,Yes,0.0,Graduate,No,4950,125.0,1.0,Urban,Y
389,390,Male,No,0.0,Graduate,No,5488,125.0,1.0,Rural,Y
367,368,Male,Yes,0.0,Graduate,No,5124,124.0,0.0,Rural,N
93,94,Male,Yes,0.0,Graduate,No,4133,122.0,1.0,Semiurban,Y
143,144,Male,No,0.0,Graduate,No,2698,122.0,1.0,Semiurban,Y
26,27,Male,No,0.0,Graduate,No,2799,122.0,1.0,Semiurban,Y
425,426,Male,No,0.0,Graduate,No,2666,121.0,1.0,Rural,Y
158,159,Male,Yes,0.0,Graduate,NaN,2980,120.0,1.0,Rural,Y
60,61,Male,No,0.0,Graduate,No,2500,120.0,1.0,Urban,Y
185,186,Male,No,0.0,Graduate,Yes,39147,120.0,1.0,Semiurban,Y
194,195,Male,Yes,0.0,Graduate,No,4191,120.0,1.0,Rural,Y
375,376,Male,No,0.0,Graduate,No,4817,120.0,1.0,Urban,Y
245,246,Male,Yes,0.0,Graduate,Yes,6050,120.0,1.0,Urban,N
392,393,Male,No,0.0,Graduate,No,2583,120.0,NaN,Urban,Y
287,288,Male,No,0.0,Graduate,No,3704,120.0,1.0,Rural,Y
494,495,Male,No,0.0,Graduate,No,3597,119.0,0.0,Rural,N
150,151,Male,Yes,0.0,Graduate,No,6277,118.0,0.0,Rural,N
456,457,Male,No,0.0,Graduate,No,4301,118.0,1.0,Urban,Y
114,115,Male,Yes,0.0,Graduate,NaN,5050,118.0,1.0,Semiurban,Y
175,176,Male,No,0.0,Graduate,No,3497,116.0,1.0,Rural,Y
19,20,Male,No,0.0,Graduate,NaN,2600,115.0,1.0,Urban,Y
320,321,Male,No,0.0,Graduate,No,2400,115.0,1.0,Semiurban,Y
13,14,Male,Yes,0.0,Graduate,No,1853,114.0,1.0,Rural,N
33,34,Male,No,0.0,Graduate,No,3500,114.0,1.0,Semiurban,Y
75,76,Male,Yes,0.0,Graduate,No,3750,113.0,1.0,Urban,N
418,419,Male,No,0.0,Graduate,No,1025,112.0,1.0,Rural,Y
281,282,Male,No,0.0,Graduate,No,3927,112.0,1.0,Semiurban,Y
497,498,Male,No,0.0,Graduate,No,4625,111.0,NaN,Urban,Y
469,470,Male,No,0.0,Graduate,No,4333,110.0,1.0,Urban,N
577,578,Male,Yes,0.0,Graduate,No,3229,110.0,1.0,Urban,Y
526,527,Male,No,0.0,Graduate,No,3775,110.0,1.0,Semiurban,Y
549,550,Male,No,0.0,Graduate,No,2785,110.0,1.0,Rural,Y
608,609,Male,No,0.0,Graduate,No,3232,108.0,1.0,Rural,Y
431,432,Male,Yes,0.0,Graduate,No,6500,105.0,0.0,Rural,N
87,88,Male,No,0.0,Graduate,No,2500,104.0,1.0,Semiurban,Y
586,587,Male,No,0.0,Graduate,No,2297,104.0,1.0,Urban,Y
569,570,Male,No,0.0,Graduate,No,3166,104.0,0.0,Urban,N
402,403,Male,Yes,0.0,Graduate,No,2500,103.0,1.0,Semiurban,Y
134,135,Male,Yes,0.0,Graduate,No,4895,102.0,1.0,Semiurban,Y
422,423,Male,No,0.0,Graduate,No,1820,100.0,1.0,Urban,Y
36,37,Male,No,0.0,Graduate,No,1828,100.0,0.0,Urban,N
434,435,Male,Yes,0.0,Graduate,No,3750,100.0,1.0,Urban,Y
464,465,Male,Yes,0.0,Graduate,No,4166,98.0,0.0,Semiurban,N
331,332,Male,Yes,0.0,Graduate,No,2935,98.0,1.0,Semiurban,Y
424,425,Male,No,0.0,Graduate,No,14880,96.0,1.0,Semiurban,Y
56,57,Male,No,0.0,Graduate,No,2132,96.0,1.0,Semiurban,Y
366,367,Male,Yes,0.0,Graduate,No,2500,96.0,1.0,Semiurban,N
363,364,Male,No,0.0,Graduate,No,3013,95.0,NaN,Urban,Y
397,398,Male,No,0.0,Graduate,No,3033,95.0,1.0,Urban,Y
453,454,Male,No,0.0,Graduate,No,2483,90.0,0.0,Rural,Y
249,250,Male,No,0.0,Graduate,No,1809,90.0,1.0,Urban,Y
581,582,Male,Yes,0.0,Graduate,No,1836,90.0,1.0,Urban,N
285,286,Male,Yes,0.0,Graduate,No,3158,89.0,1.0,Rural,Y
317,318,Male,No,0.0,Graduate,No,2058,88.0,NaN,Urban,Y
428,429,Male,No,0.0,Graduate,No,2920,87.0,1.0,Rural,Y
454,455,Male,Yes,0.0,Graduate,Yes,7085,84.0,1.0,Semiurban,Y
199,200,Male,Yes,0.0,Graduate,Yes,11000,83.0,1.0,Urban,N
72,73,Male,Yes,0.0,Graduate,No,3500,81.0,1.0,Semiurban,Y
40,41,Male,Yes,0.0,Graduate,No,3600,80.0,1.0,Urban,N
277,278,Male,No,0.0,Graduate,No,3103,80.0,1.0,Urban,Y
193,194,Male,Yes,0.0,Graduate,No,3858,76.0,1.0,Semiurban,Y
42,43,Male,No,0.0,Graduate,No,2400,75.0,NaN,Urban,Y
164,165,Male,No,0.0,Graduate,No,9323,75.0,1.0,Urban,Y
489,490,Male,Yes,0.0,Graduate,No,2435,75.0,1.0,Urban,N
131,132,Male,Yes,0.0,Graduate,No,2014,74.0,1.0,Urban,Y
31,32,Male,Yes,0.0,Graduate,No,3167,74.0,1.0,Urban,N
182,183,Male,No,0.0,Graduate,No,4600,73.0,1.0,Semiurban,Y
378,379,Male,Yes,0.0,Graduate,No,3069,71.0,1.0,Urban,N
132,133,Male,Yes,0.0,Graduate,No,2718,70.0,1.0,Semiurban,Y
566,567,Male,Yes,0.0,Graduate,No,3333,70.0,1.0,Urban,Y
513,514,Male,No,0.0,Graduate,No,2130,70.0,1.0,Semiurban,N
181,182,Male,Yes,0.0,Graduate,No,1916,67.0,NaN,Rural,N
2,3,Male,No,0.0,Graduate,Yes,3000,66.0,1.0,Urban,Y
168,169,Male,Yes,0.0,Graduate,No,2237,63.0,0.0,Semiurban,N
220,221,Male,No,0.0,Graduate,No,2221,60.0,0.0,Urban,N
208,209,Male,Yes,0.0,Graduate,No,2479,59.0,1.0,Urban,Y
187,188,Male,No,0.0,Graduate,No,2383,58.0,NaN,Rural,Y
590,591,Male,No,0.0,Graduate,No,3000,56.0,1.0,Semiurban,Y
447,448,Male,No,0.0,Graduate,NaN,3539,55.0,1.0,Rural,N
521,522,Male,Yes,0.0,Graduate,No,2500,55.0,1.0,Semiurban,Y
154,155,Male,Yes,0.0,Graduate,No,3254,50.0,1.0,Urban,Y
97,98,Male,No,0.0,Graduate,No,1977,50.0,1.0,Semiurban,Y
436,437,Male,Yes,0.0,Graduate,No,1926,50.0,1.0,Semiurban,Y
41,42,Male,Yes,0.0,Graduate,No,1800,47.0,1.0,Urban,Y
231,232,Male,No,0.0,Graduate,NaN,3716,42.0,1.0,Rural,Y
133,134,Male,No,0.0,Graduate,Yes,3459,25.0,1.0,Semiurban,Y
0,1,Male,Yes,0.0,Graduate,No,5139,0.0,1.0,Urban,Y
95,96,Male,Yes,0.0,Graduate,NaN,6782,NaN,NaN,Urban,N
103,104,Male,No,0.0,Graduate,No,4652,NaN,1.0,Semiurban,Y
35,36,Male,No,0.0,Graduate,No,2275,NaN,1.0,Urban,Y
127,128,Male,Yes,0.0,Graduate,No,3865,NaN,1.0,Rural,Y
437,438,Male,No,0.0,Graduate,No,2213,NaN,1.0,Urban,Y
284,285,Male,No,0.0,Graduate,No,20667,NaN,1.0,Rural,N
524,525,Male,Yes,0.0,Graduate,No,4680,NaN,1.0,Semiurban,N
412,413,Male,No,0.0,Not Graduate,No,6096,218.0,0.0,Rural,N
250,251,Male,No,0.0,Not Graduate,No,1668,201.0,0.0,Semiurban,N
124,125,Male,No,0.0,Not Graduate,No,4300,194.0,1.0,Rural,Y
553,554,Male,No,0.0,Not Graduate,No,2454,181.0,0.0,Urban,N
62,63,Male,No,0.0,Not Graduate,Yes,2609,165.0,0.0,Rural,N
192,193,Male,No,0.0,Not Graduate,No,6033,160.0,1.0,Urban,N
601,602,Male,No,0.0,Not Graduate,NaN,2894,155.0,1.0,Rural,Y
112,113,Male,No,0.0,Not Graduate,No,3572,152.0,0.0,Rural,N
18,19,Male,No,0.0,Not Graduate,No,4887,133.0,1.0,Rural,N
365,366,Male,Yes,0.0,Not Graduate,No,6216,133.0,1.0,Rural,N
386,387,Male,Yes,0.0,Not Graduate,No,2346,132.0,1.0,Semiurban,Y
563,564,Male,Yes,0.0,Not Graduate,Yes,5800,132.0,1.0,Semiurban,Y
529,530,Male,Yes,0.0,Not Graduate,No,6783,130.0,1.0,Semiurban,Y
66,67,Male,Yes,0.0,Not Graduate,No,3200,126.0,0.0,Urban,N
535,536,Male,Yes,0.0,Not Graduate,NaN,2550,126.0,1.0,Rural,Y
504,505,Male,No,0.0,Not Graduate,No,3814,124.0,1.0,Semiurban,Y
244,245,Male,No,0.0,Not Graduate,No,3406,123.0,1.0,Semiurban,Y
107,108,Male,Yes,0.0,Not Graduate,NaN,7333,120.0,1.0,Rural,N
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
232,233,Male,Yes,0.0,Not Graduate,No,3189,120.0,1.0,Rural,Y
565,566,Male,No,0.0,Not Graduate,No,4467,120.0,NaN,Rural,Y
22,23,Male,No,0.0,Not Graduate,No,2600,116.0,0.0,Semiurban,N
98,99,Male,No,0.0,Not Graduate,No,4188,115.0,1.0,Semiurban,Y
256,257,Male,Yes,0.0,Not Graduate,No,6045,115.0,0.0,Rural,N
406,407,Male,No,0.0,Not Graduate,No,2167,115.0,1.0,Urban,Y
311,312,Male,Yes,0.0,Not Graduate,No,2927,111.0,1.0,Semiurban,Y
492,493,Male,Yes,0.0,Not Graduate,No,3691,110.0,1.0,Rural,Y
39,40,Male,Yes,0.0,Not Graduate,No,3748,110.0,1.0,Semiurban,Y
595,596,Male,Yes,0.0,Not Graduate,No,3833,110.0,1.0,Rural,Y
413,414,Male,No,0.0,Not Graduate,No,2253,110.0,1.0,Rural,Y
398,399,Male,Yes,0.0,Not Graduate,No,3902,109.0,1.0,Rural,Y
496,497,Male,No,0.0,Not Graduate,No,2600,107.0,1.0,Rural,Y
20,21,Male,No,0.0,Not Graduate,No,7660,104.0,0.0,Urban,N
252,253,Male,Yes,0.0,Not Graduate,Yes,2583,104.0,1.0,Rural,Y
179,180,Male,Yes,0.0,Not Graduate,No,2333,102.0,0.0,Urban,N
358,359,Male,No,0.0,Not Graduate,No,3000,100.0,0.0,Urban,N
510,511,Male,Yes,0.0,Not Graduate,No,3598,100.0,1.0,Rural,N
160,161,Male,No,0.0,Not Graduate,No,1863,98.0,1.0,Semiurban,Y
490,491,Male,Yes,0.0,Not Graduate,No,2699,96.0,NaN,Semiurban,Y
44,45,Male,No,0.0,Not Graduate,Yes,4695,96.0,1.0,Urban,Y
170,171,Male,No,0.0,Not Graduate,NaN,1820,95.0,1.0,Rural,Y
6,7,Male,No,0.0,Not Graduate,No,2333,95.0,1.0,Urban,Y
300,301,Male,No,0.0,Not Graduate,No,1800,93.0,0.0,Urban,N
174,175,Male,No,0.0,Not Graduate,Yes,4344,87.0,1.0,Semiurban,N
546,547,Male,Yes,0.0,Not Graduate,No,3358,80.0,1.0,Semiurban,N
538,539,Male,No,0.0,Not Graduate,No,2917,66.0,1.0,Rural,N
401,402,Male,Yes,0.0,Not Graduate,No,2755,65.0,1.0,Rural,N
429,430,Male,Yes,0.0,Not Graduate,No,2717,60.0,1.0,Urban,Y
207,208,Male,Yes,0.0,Not Graduate,No,3975,55.0,1.0,Rural,Y
190,191,Male,Yes,0.0,Not Graduate,No,4885,48.0,1.0,Rural,Y
28,29,Male,Yes,0.0,Not Graduate,No,1442,35.0,1.0,Urban,N
94,95,Male,Yes,0.0,Not Graduate,No,3620,25.0,1.0,Semiurban,Y
387,388,Male,No,0.0,Not Graduate,No,3010,NaN,0.0,Urban,N
305,306,Male,Yes,0.0,Not Graduate,No,2000,NaN,1.0,Urban,N
605,606,Male,No,0.0,Not Graduate,No,2400,NaN,1.0,Urban,N
188,189,NaN,No,0.0,Graduate,Yes,674,168.0,1.0,Rural,Y
460,461,NaN,No,0.0,Graduate,Yes,2083,160.0,NaN,Semiurban,Y
314,315,NaN,No,0.0,Graduate,No,2473,159.0,1.0,Rural,N
576,577,NaN,No,0.0,Graduate,No,3087,136.0,0.0,Semiurban,N
467,468,NaN,No,0.0,Graduate,No,16692,110.0,1.0,Semiurban,Y

In [71]:
dataset ['Salary * 10E4'].head (500)

233    280.0
119    259.0
148    225.0
210    214.0
404    194.0
559    182.0
382    156.0
116    154.0
298    151.0
37     144.0
49     144.0
111    139.0
96     137.0
122    137.0
69     136.0
306    135.0
268    135.0
613    133.0
323    132.0
302    132.0
354    130.0
237    122.0
48     120.0
51     120.0
263    120.0
64     116.0
405    115.0
288    115.0
500    113.0
198    113.0
166    112.0
52     112.0
80     111.0
374    110.0
328    110.0
184    108.0
353    105.0
307    104.0
399    103.0
548    103.0
501    100.0
145    100.0
286     99.0
541     99.0
473     93.0
125     93.0
45      88.0
136     84.0
310     84.0
556     84.0
206     80.0
17      76.0
339     71.0
396     71.0
609     71.0
329     67.0
415     60.0
312     56.0
370     55.0
283     54.0
341     46.0
121     44.0
582     36.0
270     30.0
568      9.0
493    225.0
414    178.0
480    154.0
439    138.0
534    125.0
279    124.0
205    120.0
197    120.0
544    102.0
50     100.0
519     95.0
421     80.0
587     70.0
407     66.0
403     53.0
130    650.0
369    570.0
333    490.0
308    480.0
506    480.0
278    436.0
432    405.0
536    324.0
514    311.0
351    308.0
258    304.0
381    296.0
161    275.0
83     265.0
594    260.0
348    259.0
65     258.0
159    255.0
236    255.0
152    244.0
138    242.0
483    234.0
350    228.0
530    216.0
562    211.0
88     210.0
499    209.0
276    207.0
229    200.0
254    192.0
25     191.0
189    188.0
508    188.0
196    187.0
173    187.0
349    187.0
438    187.0
440    187.0
289    187.0
518    185.0
38     184.0
327    184.0
165    182.0
129    182.0
598    180.0
441    180.0
76     176.0
89     175.0
118    175.0
142    175.0
223    175.0
444    175.0
457    173.0
70     172.0
603    172.0
294    172.0
225    170.0
141    168.0
191    164.0
558    162.0
579    161.0
459    160.0
345    160.0
411    160.0
242    155.0
545    155.0
462    153.0
151    152.0
101    151.0
265    151.0
273    150.0
452    149.0
547    145.0
47     144.0
222    144.0
433    143.0
593    142.0
4      141.0
364    141.0
465    140.0
304    140.0
290    139.0
419    138.0
420    138.0
214    137.0
110    136.0
85     136.0
388    136.0
271    136.0
216    135.0
57     135.0
43     134.0
261    134.0
554    132.0
99     131.0
90     131.0
217    131.0
377    130.0
362    130.0
326    130.0
167    129.0
482    128.0
264    128.0
380    128.0
224    128.0
383    128.0
209    127.0
272    126.0
149    125.0
15     125.0
389    125.0
367    124.0
93     122.0
143    122.0
26     122.0
425    121.0
158    120.0
60     120.0
185    120.0
194    120.0
375    120.0
245    120.0
392    120.0
287    120.0
494    119.0
150    118.0
456    118.0
114    118.0
175    116.0
19     115.0
320    115.0
13     114.0
33     114.0
75     113.0
418    112.0
281    112.0
497    111.0
469    110.0
577    110.0
526    110.0
549    110.0
608    108.0
431    105.0
87     104.0
586    104.0
569    104.0
402    103.0
134    102.0
422    100.0
36     100.0
434    100.0
464     98.0
331     98.0
424     96.0
56      96.0
366     96.0
363     95.0
397     95.0
453     90.0
249     90.0
581     90.0
285     89.0
317     88.0
428     87.0
454     84.0
199     83.0
72      81.0
40      80.0
277     80.0
193     76.0
42      75.0
164     75.0
489     75.0
131     74.0
31      74.0
182     73.0
378     71.0
132     70.0
566     70.0
513     70.0
181     67.0
2       66.0
168     63.0
220     60.0
208     59.0
187     58.0
590     56.0
447     55.0
521     55.0
154     50.0
97      50.0
436     50.0
41      47.0
231     42.0
133     25.0
0        0.0
95       NaN
103      NaN
35       NaN
127      NaN
437      NaN
284      NaN
524      NaN
412    218.0
250    201.0
124    194.0
553    181.0
62     165.0
192    160.0
601    155.0
112    152.0
18     133.0
365    133.0
386    132.0
563    132.0
529    130.0
66     126.0
535    126.0
504    124.0
244    123.0
107    120.0
3      120.0
232    120.0
565    120.0
22     116.0
98     115.0
256    115.0
406    115.0
311    111.0
492    110.0
39     110.0
595    110.0
413    110.0
398    109.0
496    107.0
20     104.0
252    104.0
179    102.0
358    100.0
510    100.0
160     98.0
490     96.0
44      96.0
170     95.0
6       95.0
300     93.0
174     87.0
546     80.0
538     66.0
401     65.0
429     60.0
207     55.0
190     48.0
28      35.0
94      25.0
387      NaN
305      NaN
605      NaN
188    168.0
460    160.0
314    159.0
576    136.0
467    110.0
507     96.0
588     94.0
561    600.0
604    496.0
54     286.0
416    160.0
262    155.0
430    150.0
540    140.0
297    135.0
318    112.0
238    112.0
495    105.0
542     95.0
269     90.0
360     81.0
509     40.0
113      NaN
463    132.0
426     81.0
410     62.0
487    500.0
325    376.0
9      349.0
260    330.0
21     315.0
67     312.0
183    260.0
611    253.0
511    250.0
212    240.0
30     201.0
296    200.0
533    196.0
157    187.0
570    186.0
115    185.0
180    180.0
58     180.0
368    175.0
606    173.0
585    172.0
195    170.0
235    170.0
470    162.0
128    160.0
156    160.0
336    160.0
552    158.0
319    155.0
408    152.0
443    152.0
24     151.0
584    146.0
234    140.0
445    130.0
1      128.0
248    123.0
162    121.0
330    117.0
178    116.0
275    115.0
385    113.0
299    113.0
373    111.0
77     110.0
423    110.0
578    107.0
32     106.0
230    104.0
105    100.0
239     96.0
303     96.0
498     95.0
478     86.0
117     85.0
357     67.0
186     66.0
583     61.0
84      50.0
46      44.0
147     30.0
555     26.0
63       NaN
81       NaN
253    279.0
449    190.0
491    186.0
527    161.0
280    158.0
342    158.0
241    140.0
503    138.0
247    137.0
203    135.0
485    131.0
543    128.0
471    113.0
315    111.0
16     100.0
528     94.0
200     90.0
551      NaN
334    182.0
82     167.0
251    138.0
219    127.0
29     120.0
516    113.0
146     70.0
468     98.0
523    480.0
525    400.0
372    380.0
572    275.0
5      267.0
564    258.0
484    246.0
505    243.0
417    239.0
361    236.0
476    230.0
106    225.0
108    216.0
227    210.0
502    208.0
580    205.0
591    205.0
169    200.0
12     200.0
599    192.0
91     188.0
612    187.0
144    187.0
140    185.0
337    176.0
8      168.0
201    166.0
356    165.0
474    162.0
488    160.0
163    158.0
371    155.0
475    150.0
448    150.0
266    150.0
512    148.0
313    144.0
458    136.0
395    135.0
292    134.0
53     134.0
427    133.0
379    130.0
291    127.0
344    125.0
316    120.0
Name: Salary * 10E4, dtype: float64

In [72]:
dataset ['Salary * 10E4'].median ()

128.0

In [73]:
dataset.median()

Serial_no            307.5
Experience_Years       0.0
Score               3812.5
Salary * 10E4        128.0
Offer_History          1.0
dtype: float64

In [74]:
dataset.describe()

,Serial_no,Experience_Years,Score,Salary * 10E4,Offer_History
count,614.000000,599.000000,614.000000,593.000000,564.000000
mean,307.500000,0.762938,5402.302932,146.165261,0.842199
std,177.390811,1.015216,6109.024398,85.726110,0.364878
min,1.000000,0.000000,150.000000,0.000000,0.000000
25%,154.250000,0.000000,2877.500000,100.000000,1.000000
50%,307.500000,0.000000,3812.500000,128.000000,1.000000
75%,460.750000,2.000000,5771.500000,168.000000,1.000000
max,614.000000,3.000000,81000.000000,700.000000,1.000000

In [75]:
dataset['Python_exp']

233    Yes
119    Yes
148    Yes
210    Yes
404    Yes
      ...
102     No
346     No
226     No
517     No
301     No
Name: Python_exp, Length: 614, dtype: object

In [76]:
dataset['Python_exp']. value_counts()

No     398
Yes    213
Name: Python_exp, dtype: int64

In [77]:
dataset['Location']. value_counts()

Semiurban    233
Urban        202
Rural        179
Name: Location, dtype: int64

In [78]:
pd.set_option('display.max_rows', 500)

In [79]:
dataset.head(500)

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
233,234,Female,Yes,0.0,Graduate,No,8333,280.0,1.0,Semiurban,Y
119,120,Female,Yes,0.0,Graduate,No,10408,259.0,1.0,Urban,Y
148,149,Female,Yes,0.0,Graduate,No,10000,225.0,1.0,Rural,N
210,211,Female,Yes,0.0,Graduate,No,10000,214.0,1.0,Semiurban,N
404,405,Female,Yes,0.0,Graduate,Yes,7441,194.0,1.0,Rural,N
559,560,Female,No,0.0,Graduate,No,4180,182.0,1.0,Semiurban,Y
382,383,Female,Yes,0.0,Graduate,No,6000,156.0,1.0,Urban,Y
116,117,Female,No,0.0,Graduate,No,3167,154.0,1.0,Semiurban,Y
298,299,Female,Yes,0.0,Graduate,No,5000,151.0,1.0,Rural,N
37,38,Female,No,0.0,Graduate,No,3667,144.0,1.0,Semiurban,Y
49,50,Female,Yes,0.0,Graduate,No,4000,144.0,1.0,Semiurban,Y
111,112,Female,No,0.0,Graduate,NaN,2929,139.0,1.0,Semiurban,Y
96,97,Female,No,0.0,Graduate,No,2484,137.0,1.0,Semiurban,Y
122,123,Female,Yes,0.0,Graduate,No,2137,137.0,0.0,Semiurban,Y
69,70,Female,Yes,0.0,Graduate,No,4300,136.0,0.0,Semiurban,N
306,307,Female,Yes,0.0,Graduate,No,3762,135.0,1.0,Rural,Y
268,269,Female,Yes,0.0,Graduate,NaN,3418,135.0,1.0,Rural,N
613,614,Female,Yes,0.0,Graduate,Yes,4583,133.0,0.0,Semiurban,N
323,324,Female,Yes,0.0,Graduate,No,3166,132.0,NaN,Rural,Y
302,303,Female,Yes,0.0,Graduate,No,5000,132.0,1.0,Rural,Y
354,355,Female,No,0.0,Graduate,No,2423,130.0,1.0,Semiurban,Y
237,238,Female,Yes,0.0,Graduate,Yes,3463,122.0,NaN,Urban,Y
48,49,Female,No,0.0,Graduate,No,2645,120.0,0.0,Urban,N
51,52,Female,Yes,0.0,Graduate,No,3086,120.0,1.0,Semiurban,Y
263,264,Female,Yes,0.0,Graduate,No,7200,120.0,1.0,Rural,Y
64,65,Female,Yes,0.0,Graduate,No,4166,116.0,0.0,Semiurban,N
405,406,Female,Yes,0.0,Graduate,No,4547,115.0,1.0,Semiurban,Y
288,289,Female,Yes,0.0,Graduate,No,4124,115.0,1.0,Semiurban,Y
500,501,Female,Yes,0.0,Graduate,No,645,113.0,1.0,Rural,Y
198,199,Female,No,0.0,Graduate,No,3416,113.0,NaN,Semiurban,Y
166,167,Female,No,0.0,Graduate,No,4583,112.0,1.0,Rural,N
52,53,Female,Yes,0.0,Graduate,No,4230,112.0,1.0,Semiurban,N
80,81,Female,Yes,0.0,Graduate,No,3846,111.0,1.0,Semiurban,Y
374,375,Female,Yes,0.0,Graduate,NaN,2764,110.0,1.0,Urban,Y
328,329,Female,No,0.0,Graduate,No,4333,110.0,1.0,Urban,N
184,185,Female,No,0.0,Graduate,No,3625,108.0,1.0,Semiurban,Y
353,354,Female,No,0.0,Graduate,Yes,5500,105.0,0.0,Rural,N
307,308,Female,Yes,0.0,Graduate,No,2400,104.0,0.0,Urban,N
399,400,Female,Yes,0.0,Graduate,No,1500,103.0,0.0,Semiurban,N
548,549,Female,Yes,0.0,Graduate,No,5000,103.0,0.0,Semiurban,N
501,502,Female,Yes,0.0,Graduate,No,3159,100.0,1.0,Semiurban,Y
145,146,Female,No,0.0,Graduate,No,2330,100.0,1.0,Semiurban,Y
286,287,Female,Yes,0.0,Graduate,Yes,2600,99.0,1.0,Semiurban,N
541,542,Female,Yes,0.0,Graduate,No,2138,99.0,0.0,Semiurban,N
473,474,Female,Yes,0.0,Graduate,Yes,2500,93.0,NaN,Urban,Y
125,126,Female,Yes,0.0,Graduate,No,3692,93.0,NaN,Rural,Y
45,46,Female,Yes,0.0,Graduate,No,3410,88.0,1.0,Urban,Y
136,137,Female,No,0.0,Graduate,No,4583,84.0,1.0,Rural,N
310,311,Female,Yes,0.0,Graduate,No,2917,84.0,1.0,Semiurban,Y
556,557,Female,Yes,0.0,Graduate,No,2667,84.0,NaN,Urban,Y
206,207,Female,Yes,0.0,Graduate,No,3244,80.0,1.0,Urban,Y
17,18,Female,Yes,0.0,Graduate,No,3510,76.0,0.0,Urban,N
339,340,Female,Yes,0.0,Graduate,No,4160,71.0,1.0,Semiurban,Y
396,397,Female,Yes,0.0,Graduate,No,3180,71.0,0.0,Urban,N
609,610,Female,Yes,0.0,Graduate,No,2900,71.0,1.0,Rural,Y
329,330,Female,Yes,0.0,Graduate,No,2500,67.0,1.0,Urban,Y
415,416,Female,Yes,0.0,Graduate,No,2995,60.0,1.0,Urban,Y
312,313,Female,Yes,0.0,Graduate,No,2507,56.0,1.0,Rural,Y
370,371,Female,Yes,0.0,Graduate,Yes,15759,55.0,1.0,Semiurban,Y
283,284,Female,Yes,0.0,Graduate,No,1811,54.0,1.0,Urban,Y
341,342,Female,Yes,0.0,Graduate,No,2378,46.0,1.0,Rural,N
121,122,Female,Yes,0.0,Graduate,No,4166,44.0,1.0,Semiurban,Y
582,583,Female,No,0.0,Graduate,No,3166,36.0,1.0,Semiurban,Y
270,271,Female,Yes,0.0,Graduate,No,3237,30.0,1.0,Urban,Y
568,569,Female,Yes,0.0,Graduate,No,2378,9.0,1.0,Urban,N
493,494,Female,Yes,0.0,Not Graduate,Yes,17263,225.0,1.0,Semiurban,Y
414,415,Female,No,0.0,Not Graduate,No,2149,178.0,0.0,Semiurban,N
480,481,Female,Yes,0.0,Not Graduate,No,4350,154.0,1.0,Rural,Y
439,440,Female,No,0.0,Not Graduate,Yes,7142,138.0,1.0,Rural,Y
534,535,Female,Yes,0.0,Not Graduate,Yes,18165,125.0,1.0,Urban,Y
279,280,Female,No,0.0,Not Graduate,No,4100,124.0,NaN,Rural,Y
205,206,Female,Yes,0.0,Not Graduate,No,4408,120.0,1.0,Semiurban,Y
197,198,Female,Yes,0.0,Not Graduate,No,1907,120.0,1.0,Urban,Y
544,545,Female,No,0.0,Not Graduate,No,3017,102.0,NaN,Semiurban,Y
50,51,Female,No,0.0,Not Graduate,No,1928,100.0,1.0,Semiurban,Y
519,520,Female,Yes,0.0,Not Graduate,No,3400,95.0,1.0,Rural,N
421,422,Female,Yes,0.0,Not Graduate,No,2720,80.0,0.0,Urban,N
587,588,Female,Yes,0.0,Not Graduate,No,2165,70.0,1.0,Semiurban,Y
407,408,Female,Yes,0.0,Not Graduate,No,2213,66.0,1.0,Rural,Y
403,404,Female,Yes,0.0,Not Graduate,No,1963,53.0,1.0,Semiurban,Y
130,131,Male,Yes,0.0,Graduate,Yes,20166,650.0,NaN,Urban,Y
369,370,Male,No,0.0,Graduate,No,19730,570.0,1.0,Rural,N
333,334,Male,No,0.0,Graduate,NaN,63337,490.0,1.0,Urban,Y
308,309,Male,Yes,0.0,Graduate,No,20233,480.0,1.0,Rural,N
506,507,Male,No,0.0,Graduate,No,20833,480.0,NaN,Urban,Y
278,279,Male,No,0.0,Graduate,No,14583,436.0,1.0,Semiurban,Y
432,433,Male,Yes,0.0,Graduate,NaN,12876,405.0,1.0,Semiurban,Y
536,537,Male,No,0.0,Graduate,No,6133,324.0,1.0,Urban,Y
514,515,Male,Yes,0.0,Graduate,No,5815,311.0,1.0,Rural,N
351,352,Male,Yes,0.0,Graduate,No,8750,308.0,1.0,Rural,N
258,259,Male,No,0.0,Graduate,No,14683,304.0,1.0,Rural,N
381,382,Male,Yes,0.0,Graduate,No,5941,296.0,1.0,Semiurban,Y
161,162,Male,No,0.0,Graduate,No,7933,275.0,1.0,Urban,N
83,84,Male,No,0.0,Graduate,No,6000,265.0,NaN,Semiurban,N
594,595,Male,No,0.0,Graduate,Yes,16120,260.0,1.0,Urban,Y
348,349,Male,No,0.0,Graduate,No,6333,259.0,NaN,Semiurban,Y
65,66,Male,No,0.0,Graduate,No,5726,258.0,1.0,Semiurban,N
159,160,Male,No,0.0,Graduate,No,4583,255.0,1.0,Semiurban,Y
236,237,Male,No,0.0,Graduate,NaN,5746,255.0,NaN,Urban,N
152,153,Male,Yes,0.0,Graduate,No,9166,244.0,1.0,Urban,N
138,139,Male,Yes,0.0,Graduate,No,14999,242.0,0.0,Semiurban,N
483,484,Male,No,0.0,Graduate,No,10833,234.0,1.0,Semiurban,Y
350,351,Male,No,0.0,Graduate,No,9083,228.0,1.0,Semiurban,Y
530,531,Male,No,0.0,Graduate,No,1025,216.0,NaN,Rural,Y
562,563,Male,No,0.0,Graduate,No,5923,211.0,1.0,Rural,Y
88,89,Male,Yes,0.0,Graduate,No,8566,210.0,1.0,Urban,Y
499,500,Male,Yes,0.0,Graduate,No,6283,209.0,0.0,Rural,N
276,277,Male,No,0.0,Graduate,No,3993,207.0,1.0,Semiurban,Y
229,230,Male,Yes,0.0,Graduate,Yes,6400,200.0,1.0,Rural,Y
254,255,Male,Yes,0.0,Graduate,Yes,16250,192.0,0.0,Urban,N
25,26,Male,No,0.0,Graduate,Yes,9560,191.0,1.0,Semiurban,Y
189,190,Male,No,0.0,Graduate,No,9328,188.0,1.0,Rural,Y
508,509,Male,No,0.0,Graduate,Yes,2479,188.0,1.0,Urban,Y
196,197,Male,Yes,0.0,Graduate,No,8333,187.0,1.0,Rural,Y
173,174,Male,No,0.0,Graduate,No,5708,187.0,1.0,Semiurban,Y
349,350,Male,No,0.0,Graduate,No,2625,187.0,1.0,Rural,Y
438,439,Male,Yes,0.0,Graduate,Yes,10416,187.0,0.0,Urban,N
440,441,Male,Yes,0.0,Graduate,No,3660,187.0,1.0,Semiurban,Y
289,290,Male,Yes,0.0,Graduate,No,9508,187.0,1.0,Rural,Y
518,519,Male,Yes,0.0,Graduate,No,4683,185.0,1.0,Semiurban,N
38,39,Male,Yes,0.0,Graduate,No,4166,184.0,1.0,Urban,Y
327,328,Male,No,0.0,Graduate,Yes,5818,184.0,1.0,Semiurban,Y
165,166,Male,No,0.0,Graduate,No,3707,182.0,1.0,Rural,Y
129,130,Male,No,0.0,Graduate,No,6080,182.0,NaN,Rural,N
598,599,Male,No,0.0,Graduate,Yes,9963,180.0,1.0,Rural,Y
441,442,Male,No,0.0,Graduate,No,7901,180.0,1.0,Rural,Y
76,77,Male,Yes,0.0,Graduate,No,3750,176.0,1.0,Urban,N
89,90,Male,No,0.0,Graduate,No,5695,175.0,1.0,Semiurban,Y
118,119,Male,No,0.0,Graduate,No,5568,175.0,1.0,Rural,N
142,143,Male,Yes,0.0,Graduate,Yes,6950,175.0,1.0,Semiurban,Y
223,224,Male,No,0.0,Graduate,No,7578,175.0,1.0,Semiurban,Y
444,445,Male,No,0.0,Graduate,No,7333,175.0,NaN,Rural,Y
457,458,Male,No,0.0,Graduate,No,3708,173.0,1.0,Urban,N
70,71,Male,No,0.0,Graduate,No,3208,172.0,1.0,Urban,Y
603,604,Male,Yes,0.0,Graduate,No,3676,172.0,1.0,Rural,Y
294,295,Male,No,0.0,Graduate,No,2383,172.0,1.0,Semiurban,Y
225,226,Male,No,0.0,Graduate,No,3250,170.0,1.0,Rural,N
141,142,Male,Yes,0.0,Graduate,No,5417,168.0,1.0,Urban,Y
191,192,Male,Yes,0.0,Graduate,No,12000,164.0,1.0,Semiurban,N
558,559,Male,No,0.0,Graduate,No,3887,162.0,1.0,Semiurban,Y
579,580,Male,Yes,0.0,Graduate,NaN,3182,161.0,1.0,Urban,Y
459,460,Male,No,0.0,Graduate,No,8334,160.0,1.0,Semiurban,N
345,346,Male,No,0.0,Graduate,No,2499,160.0,1.0,Semiurban,Y
411,412,Male,No,0.0,Graduate,NaN,6256,160.0,NaN,Urban,Y
242,243,Male,Yes,0.0,Graduate,No,2965,155.0,1.0,Urban,Y
545,546,Male,No,0.0,Graduate,No,2768,155.0,1.0,Rural,Y
462,463,Male,No,0.0,Graduate,No,3015,153.0,1.0,Rural,Y
151,152,Male,No,0.0,Graduate,Yes,2577,152.0,1.0,Rural,Y
101,102,Male,Yes,0.0,Graduate,No,4843,151.0,1.0,Semiurban,Y
265,266,Male,Yes,0.0,Graduate,No,4095,151.0,1.0,Rural,Y
273,274,Male,No,0.0,Graduate,No,2620,150.0,1.0,Semiurban,Y
452,453,Male,No,0.0,Graduate,No,3948,149.0,0.0,Rural,N
547,548,Male,Yes,0.0,Graduate,No,2526,145.0,1.0,Rural,Y
47,48,Male,No,0.0,Graduate,No,5821,144.0,1.0,Urban,Y
222,223,Male,Yes,0.0,Graduate,No,2971,144.0,1.0,Semiurban,Y
433,434,Male,No,0.0,Graduate,No,2425,143.0,1.0,Semiurban,Y
593,594,Male,No,0.0,Graduate,No,3859,142.0,1.0,Rural,Y
4,5,Male,Yes,0.0,Graduate,No,6000,141.0,1.0,Urban,Y
364,365,Male,Yes,0.0,Graduate,Yes,6822,141.0,1.0,Rural,Y
465,466,Male,Yes,0.0,Graduate,No,6000,140.0,1.0,Rural,Y
304,305,Male,Yes,0.0,Graduate,No,4000,140.0,1.0,Rural,Y
290,291,Male,No,0.0,Graduate,No,3075,139.0,1.0,Rural,Y
419,420,Male,No,0.0,Graduate,No,3246,138.0,1.0,Semiurban,Y
420,421,Male,No,0.0,Graduate,No,5829,138.0,1.0,Rural,Y
214,215,Male,No,0.0,Graduate,No,3173,137.0,1.0,Urban,Y
110,111,Male,Yes,0.0,Graduate,No,5316,136.0,1.0,Urban,Y
85,86,Male,Yes,0.0,Graduate,No,2366,136.0,1.0,Semiurban,Y
388,389,Male,No,0.0,Graduate,No,2333,136.0,1.0,Urban,Y
271,272,Male,No,0.0,Graduate,No,11146,136.0,1.0,Urban,Y
216,217,Male,No,0.0,Graduate,No,150,135.0,1.0,Rural,N
57,58,Male,No,0.0,Graduate,No,3366,135.0,1.0,Rural,N
43,44,Male,No,0.0,Graduate,No,3941,134.0,1.0,Semiurban,Y
261,262,Male,Yes,0.0,Graduate,No,2060,134.0,1.0,Semiurban,Y
554,555,Male,No,0.0,Graduate,No,3593,132.0,0.0,Rural,N
99,100,Male,No,0.0,Graduate,No,1759,131.0,1.0,Semiurban,Y
90,91,Male,No,0.0,Graduate,No,2958,131.0,1.0,Semiurban,Y
217,218,Male,No,0.0,Graduate,No,3727,131.0,1.0,Semiurban,Y
377,378,Male,No,0.0,Graduate,No,4310,130.0,NaN,Semiurban,Y
362,363,Male,No,0.0,Graduate,No,4750,130.0,1.0,Urban,Y
326,327,Male,Yes,0.0,Graduate,No,4917,130.0,0.0,Rural,Y
167,168,Male,No,0.0,Graduate,No,2439,129.0,1.0,Rural,Y
482,483,Male,No,0.0,Graduate,No,2083,128.0,1.0,Semiurban,Y
264,265,Male,Yes,0.0,Graduate,Yes,5166,128.0,1.0,Semiurban,Y
380,381,Male,No,0.0,Graduate,NaN,3333,128.0,1.0,Semiurban,Y
224,225,Male,No,0.0,Graduate,No,6250,128.0,1.0,Semiurban,Y
383,384,Male,Yes,0.0,Graduate,Yes,7167,128.0,1.0,Urban,Y
209,210,Male,Yes,0.0,Graduate,No,3418,127.0,1.0,Semiurban,N
272,273,Male,Yes,0.0,Graduate,No,2833,126.0,1.0,Rural,Y
149,150,Male,No,0.0,Graduate,No,4860,125.0,1.0,Semiurban,Y
15,16,Male,Yes,0.0,Graduate,No,4950,125.0,1.0,Urban,Y
389,390,Male,No,0.0,Graduate,No,5488,125.0,1.0,Rural,Y
367,368,Male,Yes,0.0,Graduate,No,5124,124.0,0.0,Rural,N
93,94,Male,Yes,0.0,Graduate,No,4133,122.0,1.0,Semiurban,Y
143,144,Male,No,0.0,Graduate,No,2698,122.0,1.0,Semiurban,Y
26,27,Male,No,0.0,Graduate,No,2799,122.0,1.0,Semiurban,Y
425,426,Male,No,0.0,Graduate,No,2666,121.0,1.0,Rural,Y
158,159,Male,Yes,0.0,Graduate,NaN,2980,120.0,1.0,Rural,Y
60,61,Male,No,0.0,Graduate,No,2500,120.0,1.0,Urban,Y
185,186,Male,No,0.0,Graduate,Yes,39147,120.0,1.0,Semiurban,Y
194,195,Male,Yes,0.0,Graduate,No,4191,120.0,1.0,Rural,Y
375,376,Male,No,0.0,Graduate,No,4817,120.0,1.0,Urban,Y
245,246,Male,Yes,0.0,Graduate,Yes,6050,120.0,1.0,Urban,N
392,393,Male,No,0.0,Graduate,No,2583,120.0,NaN,Urban,Y
287,288,Male,No,0.0,Graduate,No,3704,120.0,1.0,Rural,Y
494,495,Male,No,0.0,Graduate,No,3597,119.0,0.0,Rural,N
150,151,Male,Yes,0.0,Graduate,No,6277,118.0,0.0,Rural,N
456,457,Male,No,0.0,Graduate,No,4301,118.0,1.0,Urban,Y
114,115,Male,Yes,0.0,Graduate,NaN,5050,118.0,1.0,Semiurban,Y
175,176,Male,No,0.0,Graduate,No,3497,116.0,1.0,Rural,Y
19,20,Male,No,0.0,Graduate,NaN,2600,115.0,1.0,Urban,Y
320,321,Male,No,0.0,Graduate,No,2400,115.0,1.0,Semiurban,Y
13,14,Male,Yes,0.0,Graduate,No,1853,114.0,1.0,Rural,N
33,34,Male,No,0.0,Graduate,No,3500,114.0,1.0,Semiurban,Y
75,76,Male,Yes,0.0,Graduate,No,3750,113.0,1.0,Urban,N
418,419,Male,No,0.0,Graduate,No,1025,112.0,1.0,Rural,Y
281,282,Male,No,0.0,Graduate,No,3927,112.0,1.0,Semiurban,Y
497,498,Male,No,0.0,Graduate,No,4625,111.0,NaN,Urban,Y
469,470,Male,No,0.0,Graduate,No,4333,110.0,1.0,Urban,N
577,578,Male,Yes,0.0,Graduate,No,3229,110.0,1.0,Urban,Y
526,527,Male,No,0.0,Graduate,No,3775,110.0,1.0,Semiurban,Y
549,550,Male,No,0.0,Graduate,No,2785,110.0,1.0,Rural,Y
608,609,Male,No,0.0,Graduate,No,3232,108.0,1.0,Rural,Y
431,432,Male,Yes,0.0,Graduate,No,6500,105.0,0.0,Rural,N
87,88,Male,No,0.0,Graduate,No,2500,104.0,1.0,Semiurban,Y
586,587,Male,No,0.0,Graduate,No,2297,104.0,1.0,Urban,Y
569,570,Male,No,0.0,Graduate,No,3166,104.0,0.0,Urban,N
402,403,Male,Yes,0.0,Graduate,No,2500,103.0,1.0,Semiurban,Y
134,135,Male,Yes,0.0,Graduate,No,4895,102.0,1.0,Semiurban,Y
422,423,Male,No,0.0,Graduate,No,1820,100.0,1.0,Urban,Y
36,37,Male,No,0.0,Graduate,No,1828,100.0,0.0,Urban,N
434,435,Male,Yes,0.0,Graduate,No,3750,100.0,1.0,Urban,Y
464,465,Male,Yes,0.0,Graduate,No,4166,98.0,0.0,Semiurban,N
331,332,Male,Yes,0.0,Graduate,No,2935,98.0,1.0,Semiurban,Y
424,425,Male,No,0.0,Graduate,No,14880,96.0,1.0,Semiurban,Y
56,57,Male,No,0.0,Graduate,No,2132,96.0,1.0,Semiurban,Y
366,367,Male,Yes,0.0,Graduate,No,2500,96.0,1.0,Semiurban,N
363,364,Male,No,0.0,Graduate,No,3013,95.0,NaN,Urban,Y
397,398,Male,No,0.0,Graduate,No,3033,95.0,1.0,Urban,Y
453,454,Male,No,0.0,Graduate,No,2483,90.0,0.0,Rural,Y
249,250,Male,No,0.0,Graduate,No,1809,90.0,1.0,Urban,Y
581,582,Male,Yes,0.0,Graduate,No,1836,90.0,1.0,Urban,N
285,286,Male,Yes,0.0,Graduate,No,3158,89.0,1.0,Rural,Y
317,318,Male,No,0.0,Graduate,No,2058,88.0,NaN,Urban,Y
428,429,Male,No,0.0,Graduate,No,2920,87.0,1.0,Rural,Y
454,455,Male,Yes,0.0,Graduate,Yes,7085,84.0,1.0,Semiurban,Y
199,200,Male,Yes,0.0,Graduate,Yes,11000,83.0,1.0,Urban,N
72,73,Male,Yes,0.0,Graduate,No,3500,81.0,1.0,Semiurban,Y
40,41,Male,Yes,0.0,Graduate,No,3600,80.0,1.0,Urban,N
277,278,Male,No,0.0,Graduate,No,3103,80.0,1.0,Urban,Y
193,194,Male,Yes,0.0,Graduate,No,3858,76.0,1.0,Semiurban,Y
42,43,Male,No,0.0,Graduate,No,2400,75.0,NaN,Urban,Y
164,165,Male,No,0.0,Graduate,No,9323,75.0,1.0,Urban,Y
489,490,Male,Yes,0.0,Graduate,No,2435,75.0,1.0,Urban,N
131,132,Male,Yes,0.0,Graduate,No,2014,74.0,1.0,Urban,Y
31,32,Male,Yes,0.0,Graduate,No,3167,74.0,1.0,Urban,N
182,183,Male,No,0.0,Graduate,No,4600,73.0,1.0,Semiurban,Y
378,379,Male,Yes,0.0,Graduate,No,3069,71.0,1.0,Urban,N
132,133,Male,Yes,0.0,Graduate,No,2718,70.0,1.0,Semiurban,Y
566,567,Male,Yes,0.0,Graduate,No,3333,70.0,1.0,Urban,Y
513,514,Male,No,0.0,Graduate,No,2130,70.0,1.0,Semiurban,N
181,182,Male,Yes,0.0,Graduate,No,1916,67.0,NaN,Rural,N
2,3,Male,No,0.0,Graduate,Yes,3000,66.0,1.0,Urban,Y
168,169,Male,Yes,0.0,Graduate,No,2237,63.0,0.0,Semiurban,N
220,221,Male,No,0.0,Graduate,No,2221,60.0,0.0,Urban,N
208,209,Male,Yes,0.0,Graduate,No,2479,59.0,1.0,Urban,Y
187,188,Male,No,0.0,Graduate,No,2383,58.0,NaN,Rural,Y
590,591,Male,No,0.0,Graduate,No,3000,56.0,1.0,Semiurban,Y
447,448,Male,No,0.0,Graduate,NaN,3539,55.0,1.0,Rural,N
521,522,Male,Yes,0.0,Graduate,No,2500,55.0,1.0,Semiurban,Y
154,155,Male,Yes,0.0,Graduate,No,3254,50.0,1.0,Urban,Y
97,98,Male,No,0.0,Graduate,No,1977,50.0,1.0,Semiurban,Y
436,437,Male,Yes,0.0,Graduate,No,1926,50.0,1.0,Semiurban,Y
41,42,Male,Yes,0.0,Graduate,No,1800,47.0,1.0,Urban,Y
231,232,Male,No,0.0,Graduate,NaN,3716,42.0,1.0,Rural,Y
133,134,Male,No,0.0,Graduate,Yes,3459,25.0,1.0,Semiurban,Y
0,1,Male,Yes,0.0,Graduate,No,5139,0.0,1.0,Urban,Y
95,96,Male,Yes,0.0,Graduate,NaN,6782,NaN,NaN,Urban,N
103,104,Male,No,0.0,Graduate,No,4652,NaN,1.0,Semiurban,Y
35,36,Male,No,0.0,Graduate,No,2275,NaN,1.0,Urban,Y
127,128,Male,Yes,0.0,Graduate,No,3865,NaN,1.0,Rural,Y
437,438,Male,No,0.0,Graduate,No,2213,NaN,1.0,Urban,Y
284,285,Male,No,0.0,Graduate,No,20667,NaN,1.0,Rural,N
524,525,Male,Yes,0.0,Graduate,No,4680,NaN,1.0,Semiurban,N
412,413,Male,No,0.0,Not Graduate,No,6096,218.0,0.0,Rural,N
250,251,Male,No,0.0,Not Graduate,No,1668,201.0,0.0,Semiurban,N
124,125,Male,No,0.0,Not Graduate,No,4300,194.0,1.0,Rural,Y
553,554,Male,No,0.0,Not Graduate,No,2454,181.0,0.0,Urban,N
62,63,Male,No,0.0,Not Graduate,Yes,2609,165.0,0.0,Rural,N
192,193,Male,No,0.0,Not Graduate,No,6033,160.0,1.0,Urban,N
601,602,Male,No,0.0,Not Graduate,NaN,2894,155.0,1.0,Rural,Y
112,113,Male,No,0.0,Not Graduate,No,3572,152.0,0.0,Rural,N
18,19,Male,No,0.0,Not Graduate,No,4887,133.0,1.0,Rural,N
365,366,Male,Yes,0.0,Not Graduate,No,6216,133.0,1.0,Rural,N
386,387,Male,Yes,0.0,Not Graduate,No,2346,132.0,1.0,Semiurban,Y
563,564,Male,Yes,0.0,Not Graduate,Yes,5800,132.0,1.0,Semiurban,Y
529,530,Male,Yes,0.0,Not Graduate,No,6783,130.0,1.0,Semiurban,Y
66,67,Male,Yes,0.0,Not Graduate,No,3200,126.0,0.0,Urban,N
535,536,Male,Yes,0.0,Not Graduate,NaN,2550,126.0,1.0,Rural,Y
504,505,Male,No,0.0,Not Graduate,No,3814,124.0,1.0,Semiurban,Y
244,245,Male,No,0.0,Not Graduate,No,3406,123.0,1.0,Semiurban,Y
107,108,Male,Yes,0.0,Not Graduate,NaN,7333,120.0,1.0,Rural,N
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
232,233,Male,Yes,0.0,Not Graduate,No,3189,120.0,1.0,Rural,Y
565,566,Male,No,0.0,Not Graduate,No,4467,120.0,NaN,Rural,Y
22,23,Male,No,0.0,Not Graduate,No,2600,116.0,0.0,Semiurban,N
98,99,Male,No,0.0,Not Graduate,No,4188,115.0,1.0,Semiurban,Y
256,257,Male,Yes,0.0,Not Graduate,No,6045,115.0,0.0,Rural,N
406,407,Male,No,0.0,Not Graduate,No,2167,115.0,1.0,Urban,Y
311,312,Male,Yes,0.0,Not Graduate,No,2927,111.0,1.0,Semiurban,Y
492,493,Male,Yes,0.0,Not Graduate,No,3691,110.0,1.0,Rural,Y
39,40,Male,Yes,0.0,Not Graduate,No,3748,110.0,1.0,Semiurban,Y
595,596,Male,Yes,0.0,Not Graduate,No,3833,110.0,1.0,Rural,Y
413,414,Male,No,0.0,Not Graduate,No,2253,110.0,1.0,Rural,Y
398,399,Male,Yes,0.0,Not Graduate,No,3902,109.0,1.0,Rural,Y
496,497,Male,No,0.0,Not Graduate,No,2600,107.0,1.0,Rural,Y
20,21,Male,No,0.0,Not Graduate,No,7660,104.0,0.0,Urban,N
252,253,Male,Yes,0.0,Not Graduate,Yes,2583,104.0,1.0,Rural,Y
179,180,Male,Yes,0.0,Not Graduate,No,2333,102.0,0.0,Urban,N
358,359,Male,No,0.0,Not Graduate,No,3000,100.0,0.0,Urban,N
510,511,Male,Yes,0.0,Not Graduate,No,3598,100.0,1.0,Rural,N
160,161,Male,No,0.0,Not Graduate,No,1863,98.0,1.0,Semiurban,Y
490,491,Male,Yes,0.0,Not Graduate,No,2699,96.0,NaN,Semiurban,Y
44,45,Male,No,0.0,Not Graduate,Yes,4695,96.0,1.0,Urban,Y
170,171,Male,No,0.0,Not Graduate,NaN,1820,95.0,1.0,Rural,Y
6,7,Male,No,0.0,Not Graduate,No,2333,95.0,1.0,Urban,Y
300,301,Male,No,0.0,Not Graduate,No,1800,93.0,0.0,Urban,N
174,175,Male,No,0.0,Not Graduate,Yes,4344,87.0,1.0,Semiurban,N
546,547,Male,Yes,0.0,Not Graduate,No,3358,80.0,1.0,Semiurban,N
538,539,Male,No,0.0,Not Graduate,No,2917,66.0,1.0,Rural,N
401,402,Male,Yes,0.0,Not Graduate,No,2755,65.0,1.0,Rural,N
429,430,Male,Yes,0.0,Not Graduate,No,2717,60.0,1.0,Urban,Y
207,208,Male,Yes,0.0,Not Graduate,No,3975,55.0,1.0,Rural,Y
190,191,Male,Yes,0.0,Not Graduate,No,4885,48.0,1.0,Rural,Y
28,29,Male,Yes,0.0,Not Graduate,No,1442,35.0,1.0,Urban,N
94,95,Male,Yes,0.0,Not Graduate,No,3620,25.0,1.0,Semiurban,Y
387,388,Male,No,0.0,Not Graduate,No,3010,NaN,0.0,Urban,N
305,306,Male,Yes,0.0,Not Graduate,No,2000,NaN,1.0,Urban,N
605,606,Male,No,0.0,Not Graduate,No,2400,NaN,1.0,Urban,N
188,189,NaN,No,0.0,Graduate,Yes,674,168.0,1.0,Rural,Y
460,461,NaN,No,0.0,Graduate,Yes,2083,160.0,NaN,Semiurban,Y
314,315,NaN,No,0.0,Graduate,No,2473,159.0,1.0,Rural,N
576,577,NaN,No,0.0,Graduate,No,3087,136.0,0.0,Semiurban,N
467,468,NaN,No,0.0,Graduate,No,16692,110.0,1.0,Semiurban,Y

In [87]:
dataset.groupby (['Gender']) ["Offer_History",] .sum()

        Offer_History
Gender
Female           84.0
Male            382.0

In [92]:
dataset.groupby (['Gender', 'Education', 'Internship']) ["Offer_History",] .sum()

                                Offer_History
Gender Education    Internship
Female Graduate     No                   58.0
                    Yes                   6.0
       Not Graduate No                    9.0
                    Yes                   4.0
Male   Graduate     No                  247.0
                    Yes                  41.0
       Not Graduate No                   67.0
                    Yes                   9.0

In [96]:
dataset.head(500)

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
233,234,Female,Yes,0.0,Graduate,No,8333,280.0,1.0,Semiurban,Y
119,120,Female,Yes,0.0,Graduate,No,10408,259.0,1.0,Urban,Y
148,149,Female,Yes,0.0,Graduate,No,10000,225.0,1.0,Rural,N
210,211,Female,Yes,0.0,Graduate,No,10000,214.0,1.0,Semiurban,N
404,405,Female,Yes,0.0,Graduate,Yes,7441,194.0,1.0,Rural,N
559,560,Female,No,0.0,Graduate,No,4180,182.0,1.0,Semiurban,Y
382,383,Female,Yes,0.0,Graduate,No,6000,156.0,1.0,Urban,Y
116,117,Female,No,0.0,Graduate,No,3167,154.0,1.0,Semiurban,Y
298,299,Female,Yes,0.0,Graduate,No,5000,151.0,1.0,Rural,N
37,38,Female,No,0.0,Graduate,No,3667,144.0,1.0,Semiurban,Y
49,50,Female,Yes,0.0,Graduate,No,4000,144.0,1.0,Semiurban,Y
111,112,Female,No,0.0,Graduate,NaN,2929,139.0,1.0,Semiurban,Y
96,97,Female,No,0.0,Graduate,No,2484,137.0,1.0,Semiurban,Y
122,123,Female,Yes,0.0,Graduate,No,2137,137.0,0.0,Semiurban,Y
69,70,Female,Yes,0.0,Graduate,No,4300,136.0,0.0,Semiurban,N
306,307,Female,Yes,0.0,Graduate,No,3762,135.0,1.0,Rural,Y
268,269,Female,Yes,0.0,Graduate,NaN,3418,135.0,1.0,Rural,N
613,614,Female,Yes,0.0,Graduate,Yes,4583,133.0,0.0,Semiurban,N
323,324,Female,Yes,0.0,Graduate,No,3166,132.0,NaN,Rural,Y
302,303,Female,Yes,0.0,Graduate,No,5000,132.0,1.0,Rural,Y
354,355,Female,No,0.0,Graduate,No,2423,130.0,1.0,Semiurban,Y
237,238,Female,Yes,0.0,Graduate,Yes,3463,122.0,NaN,Urban,Y
48,49,Female,No,0.0,Graduate,No,2645,120.0,0.0,Urban,N
51,52,Female,Yes,0.0,Graduate,No,3086,120.0,1.0,Semiurban,Y
263,264,Female,Yes,0.0,Graduate,No,7200,120.0,1.0,Rural,Y
64,65,Female,Yes,0.0,Graduate,No,4166,116.0,0.0,Semiurban,N
405,406,Female,Yes,0.0,Graduate,No,4547,115.0,1.0,Semiurban,Y
288,289,Female,Yes,0.0,Graduate,No,4124,115.0,1.0,Semiurban,Y
500,501,Female,Yes,0.0,Graduate,No,645,113.0,1.0,Rural,Y
198,199,Female,No,0.0,Graduate,No,3416,113.0,NaN,Semiurban,Y
166,167,Female,No,0.0,Graduate,No,4583,112.0,1.0,Rural,N
52,53,Female,Yes,0.0,Graduate,No,4230,112.0,1.0,Semiurban,N
80,81,Female,Yes,0.0,Graduate,No,3846,111.0,1.0,Semiurban,Y
374,375,Female,Yes,0.0,Graduate,NaN,2764,110.0,1.0,Urban,Y
328,329,Female,No,0.0,Graduate,No,4333,110.0,1.0,Urban,N
184,185,Female,No,0.0,Graduate,No,3625,108.0,1.0,Semiurban,Y
353,354,Female,No,0.0,Graduate,Yes,5500,105.0,0.0,Rural,N
307,308,Female,Yes,0.0,Graduate,No,2400,104.0,0.0,Urban,N
399,400,Female,Yes,0.0,Graduate,No,1500,103.0,0.0,Semiurban,N
548,549,Female,Yes,0.0,Graduate,No,5000,103.0,0.0,Semiurban,N
501,502,Female,Yes,0.0,Graduate,No,3159,100.0,1.0,Semiurban,Y
145,146,Female,No,0.0,Graduate,No,2330,100.0,1.0,Semiurban,Y
286,287,Female,Yes,0.0,Graduate,Yes,2600,99.0,1.0,Semiurban,N
541,542,Female,Yes,0.0,Graduate,No,2138,99.0,0.0,Semiurban,N
473,474,Female,Yes,0.0,Graduate,Yes,2500,93.0,NaN,Urban,Y
125,126,Female,Yes,0.0,Graduate,No,3692,93.0,NaN,Rural,Y
45,46,Female,Yes,0.0,Graduate,No,3410,88.0,1.0,Urban,Y
136,137,Female,No,0.0,Graduate,No,4583,84.0,1.0,Rural,N
310,311,Female,Yes,0.0,Graduate,No,2917,84.0,1.0,Semiurban,Y
556,557,Female,Yes,0.0,Graduate,No,2667,84.0,NaN,Urban,Y
206,207,Female,Yes,0.0,Graduate,No,3244,80.0,1.0,Urban,Y
17,18,Female,Yes,0.0,Graduate,No,3510,76.0,0.0,Urban,N
339,340,Female,Yes,0.0,Graduate,No,4160,71.0,1.0,Semiurban,Y
396,397,Female,Yes,0.0,Graduate,No,3180,71.0,0.0,Urban,N
609,610,Female,Yes,0.0,Graduate,No,2900,71.0,1.0,Rural,Y
329,330,Female,Yes,0.0,Graduate,No,2500,67.0,1.0,Urban,Y
415,416,Female,Yes,0.0,Graduate,No,2995,60.0,1.0,Urban,Y
312,313,Female,Yes,0.0,Graduate,No,2507,56.0,1.0,Rural,Y
370,371,Female,Yes,0.0,Graduate,Yes,15759,55.0,1.0,Semiurban,Y
283,284,Female,Yes,0.0,Graduate,No,1811,54.0,1.0,Urban,Y
341,342,Female,Yes,0.0,Graduate,No,2378,46.0,1.0,Rural,N
121,122,Female,Yes,0.0,Graduate,No,4166,44.0,1.0,Semiurban,Y
582,583,Female,No,0.0,Graduate,No,3166,36.0,1.0,Semiurban,Y
270,271,Female,Yes,0.0,Graduate,No,3237,30.0,1.0,Urban,Y
568,569,Female,Yes,0.0,Graduate,No,2378,9.0,1.0,Urban,N
493,494,Female,Yes,0.0,Not Graduate,Yes,17263,225.0,1.0,Semiurban,Y
414,415,Female,No,0.0,Not Graduate,No,2149,178.0,0.0,Semiurban,N
480,481,Female,Yes,0.0,Not Graduate,No,4350,154.0,1.0,Rural,Y
439,440,Female,No,0.0,Not Graduate,Yes,7142,138.0,1.0,Rural,Y
534,535,Female,Yes,0.0,Not Graduate,Yes,18165,125.0,1.0,Urban,Y
279,280,Female,No,0.0,Not Graduate,No,4100,124.0,NaN,Rural,Y
205,206,Female,Yes,0.0,Not Graduate,No,4408,120.0,1.0,Semiurban,Y
197,198,Female,Yes,0.0,Not Graduate,No,1907,120.0,1.0,Urban,Y
544,545,Female,No,0.0,Not Graduate,No,3017,102.0,NaN,Semiurban,Y
50,51,Female,No,0.0,Not Graduate,No,1928,100.0,1.0,Semiurban,Y
519,520,Female,Yes,0.0,Not Graduate,No,3400,95.0,1.0,Rural,N
421,422,Female,Yes,0.0,Not Graduate,No,2720,80.0,0.0,Urban,N
587,588,Female,Yes,0.0,Not Graduate,No,2165,70.0,1.0,Semiurban,Y
407,408,Female,Yes,0.0,Not Graduate,No,2213,66.0,1.0,Rural,Y
403,404,Female,Yes,0.0,Not Graduate,No,1963,53.0,1.0,Semiurban,Y
130,131,Male,Yes,0.0,Graduate,Yes,20166,650.0,NaN,Urban,Y
369,370,Male,No,0.0,Graduate,No,19730,570.0,1.0,Rural,N
333,334,Male,No,0.0,Graduate,NaN,63337,490.0,1.0,Urban,Y
308,309,Male,Yes,0.0,Graduate,No,20233,480.0,1.0,Rural,N
506,507,Male,No,0.0,Graduate,No,20833,480.0,NaN,Urban,Y
278,279,Male,No,0.0,Graduate,No,14583,436.0,1.0,Semiurban,Y
432,433,Male,Yes,0.0,Graduate,NaN,12876,405.0,1.0,Semiurban,Y
536,537,Male,No,0.0,Graduate,No,6133,324.0,1.0,Urban,Y
514,515,Male,Yes,0.0,Graduate,No,5815,311.0,1.0,Rural,N
351,352,Male,Yes,0.0,Graduate,No,8750,308.0,1.0,Rural,N
258,259,Male,No,0.0,Graduate,No,14683,304.0,1.0,Rural,N
381,382,Male,Yes,0.0,Graduate,No,5941,296.0,1.0,Semiurban,Y
161,162,Male,No,0.0,Graduate,No,7933,275.0,1.0,Urban,N
83,84,Male,No,0.0,Graduate,No,6000,265.0,NaN,Semiurban,N
594,595,Male,No,0.0,Graduate,Yes,16120,260.0,1.0,Urban,Y
348,349,Male,No,0.0,Graduate,No,6333,259.0,NaN,Semiurban,Y
65,66,Male,No,0.0,Graduate,No,5726,258.0,1.0,Semiurban,N
159,160,Male,No,0.0,Graduate,No,4583,255.0,1.0,Semiurban,Y
236,237,Male,No,0.0,Graduate,NaN,5746,255.0,NaN,Urban,N
152,153,Male,Yes,0.0,Graduate,No,9166,244.0,1.0,Urban,N
138,139,Male,Yes,0.0,Graduate,No,14999,242.0,0.0,Semiurban,N
483,484,Male,No,0.0,Graduate,No,10833,234.0,1.0,Semiurban,Y
350,351,Male,No,0.0,Graduate,No,9083,228.0,1.0,Semiurban,Y
530,531,Male,No,0.0,Graduate,No,1025,216.0,NaN,Rural,Y
562,563,Male,No,0.0,Graduate,No,5923,211.0,1.0,Rural,Y
88,89,Male,Yes,0.0,Graduate,No,8566,210.0,1.0,Urban,Y
499,500,Male,Yes,0.0,Graduate,No,6283,209.0,0.0,Rural,N
276,277,Male,No,0.0,Graduate,No,3993,207.0,1.0,Semiurban,Y
229,230,Male,Yes,0.0,Graduate,Yes,6400,200.0,1.0,Rural,Y
254,255,Male,Yes,0.0,Graduate,Yes,16250,192.0,0.0,Urban,N
25,26,Male,No,0.0,Graduate,Yes,9560,191.0,1.0,Semiurban,Y
189,190,Male,No,0.0,Graduate,No,9328,188.0,1.0,Rural,Y
508,509,Male,No,0.0,Graduate,Yes,2479,188.0,1.0,Urban,Y
196,197,Male,Yes,0.0,Graduate,No,8333,187.0,1.0,Rural,Y
173,174,Male,No,0.0,Graduate,No,5708,187.0,1.0,Semiurban,Y
349,350,Male,No,0.0,Graduate,No,2625,187.0,1.0,Rural,Y
438,439,Male,Yes,0.0,Graduate,Yes,10416,187.0,0.0,Urban,N
440,441,Male,Yes,0.0,Graduate,No,3660,187.0,1.0,Semiurban,Y
289,290,Male,Yes,0.0,Graduate,No,9508,187.0,1.0,Rural,Y
518,519,Male,Yes,0.0,Graduate,No,4683,185.0,1.0,Semiurban,N
38,39,Male,Yes,0.0,Graduate,No,4166,184.0,1.0,Urban,Y
327,328,Male,No,0.0,Graduate,Yes,5818,184.0,1.0,Semiurban,Y
165,166,Male,No,0.0,Graduate,No,3707,182.0,1.0,Rural,Y
129,130,Male,No,0.0,Graduate,No,6080,182.0,NaN,Rural,N
598,599,Male,No,0.0,Graduate,Yes,9963,180.0,1.0,Rural,Y
441,442,Male,No,0.0,Graduate,No,7901,180.0,1.0,Rural,Y
76,77,Male,Yes,0.0,Graduate,No,3750,176.0,1.0,Urban,N
89,90,Male,No,0.0,Graduate,No,5695,175.0,1.0,Semiurban,Y
118,119,Male,No,0.0,Graduate,No,5568,175.0,1.0,Rural,N
142,143,Male,Yes,0.0,Graduate,Yes,6950,175.0,1.0,Semiurban,Y
223,224,Male,No,0.0,Graduate,No,7578,175.0,1.0,Semiurban,Y
444,445,Male,No,0.0,Graduate,No,7333,175.0,NaN,Rural,Y
457,458,Male,No,0.0,Graduate,No,3708,173.0,1.0,Urban,N
70,71,Male,No,0.0,Graduate,No,3208,172.0,1.0,Urban,Y
603,604,Male,Yes,0.0,Graduate,No,3676,172.0,1.0,Rural,Y
294,295,Male,No,0.0,Graduate,No,2383,172.0,1.0,Semiurban,Y
225,226,Male,No,0.0,Graduate,No,3250,170.0,1.0,Rural,N
141,142,Male,Yes,0.0,Graduate,No,5417,168.0,1.0,Urban,Y
191,192,Male,Yes,0.0,Graduate,No,12000,164.0,1.0,Semiurban,N
558,559,Male,No,0.0,Graduate,No,3887,162.0,1.0,Semiurban,Y
579,580,Male,Yes,0.0,Graduate,NaN,3182,161.0,1.0,Urban,Y
459,460,Male,No,0.0,Graduate,No,8334,160.0,1.0,Semiurban,N
345,346,Male,No,0.0,Graduate,No,2499,160.0,1.0,Semiurban,Y
411,412,Male,No,0.0,Graduate,NaN,6256,160.0,NaN,Urban,Y
242,243,Male,Yes,0.0,Graduate,No,2965,155.0,1.0,Urban,Y
545,546,Male,No,0.0,Graduate,No,2768,155.0,1.0,Rural,Y
462,463,Male,No,0.0,Graduate,No,3015,153.0,1.0,Rural,Y
151,152,Male,No,0.0,Graduate,Yes,2577,152.0,1.0,Rural,Y
101,102,Male,Yes,0.0,Graduate,No,4843,151.0,1.0,Semiurban,Y
265,266,Male,Yes,0.0,Graduate,No,4095,151.0,1.0,Rural,Y
273,274,Male,No,0.0,Graduate,No,2620,150.0,1.0,Semiurban,Y
452,453,Male,No,0.0,Graduate,No,3948,149.0,0.0,Rural,N
547,548,Male,Yes,0.0,Graduate,No,2526,145.0,1.0,Rural,Y
47,48,Male,No,0.0,Graduate,No,5821,144.0,1.0,Urban,Y
222,223,Male,Yes,0.0,Graduate,No,2971,144.0,1.0,Semiurban,Y
433,434,Male,No,0.0,Graduate,No,2425,143.0,1.0,Semiurban,Y
593,594,Male,No,0.0,Graduate,No,3859,142.0,1.0,Rural,Y
4,5,Male,Yes,0.0,Graduate,No,6000,141.0,1.0,Urban,Y
364,365,Male,Yes,0.0,Graduate,Yes,6822,141.0,1.0,Rural,Y
465,466,Male,Yes,0.0,Graduate,No,6000,140.0,1.0,Rural,Y
304,305,Male,Yes,0.0,Graduate,No,4000,140.0,1.0,Rural,Y
290,291,Male,No,0.0,Graduate,No,3075,139.0,1.0,Rural,Y
419,420,Male,No,0.0,Graduate,No,3246,138.0,1.0,Semiurban,Y
420,421,Male,No,0.0,Graduate,No,5829,138.0,1.0,Rural,Y
214,215,Male,No,0.0,Graduate,No,3173,137.0,1.0,Urban,Y
110,111,Male,Yes,0.0,Graduate,No,5316,136.0,1.0,Urban,Y
85,86,Male,Yes,0.0,Graduate,No,2366,136.0,1.0,Semiurban,Y
388,389,Male,No,0.0,Graduate,No,2333,136.0,1.0,Urban,Y
271,272,Male,No,0.0,Graduate,No,11146,136.0,1.0,Urban,Y
216,217,Male,No,0.0,Graduate,No,150,135.0,1.0,Rural,N
57,58,Male,No,0.0,Graduate,No,3366,135.0,1.0,Rural,N
43,44,Male,No,0.0,Graduate,No,3941,134.0,1.0,Semiurban,Y
261,262,Male,Yes,0.0,Graduate,No,2060,134.0,1.0,Semiurban,Y
554,555,Male,No,0.0,Graduate,No,3593,132.0,0.0,Rural,N
99,100,Male,No,0.0,Graduate,No,1759,131.0,1.0,Semiurban,Y
90,91,Male,No,0.0,Graduate,No,2958,131.0,1.0,Semiurban,Y
217,218,Male,No,0.0,Graduate,No,3727,131.0,1.0,Semiurban,Y
377,378,Male,No,0.0,Graduate,No,4310,130.0,NaN,Semiurban,Y
362,363,Male,No,0.0,Graduate,No,4750,130.0,1.0,Urban,Y
326,327,Male,Yes,0.0,Graduate,No,4917,130.0,0.0,Rural,Y
167,168,Male,No,0.0,Graduate,No,2439,129.0,1.0,Rural,Y
482,483,Male,No,0.0,Graduate,No,2083,128.0,1.0,Semiurban,Y
264,265,Male,Yes,0.0,Graduate,Yes,5166,128.0,1.0,Semiurban,Y
380,381,Male,No,0.0,Graduate,NaN,3333,128.0,1.0,Semiurban,Y
224,225,Male,No,0.0,Graduate,No,6250,128.0,1.0,Semiurban,Y
383,384,Male,Yes,0.0,Graduate,Yes,7167,128.0,1.0,Urban,Y
209,210,Male,Yes,0.0,Graduate,No,3418,127.0,1.0,Semiurban,N
272,273,Male,Yes,0.0,Graduate,No,2833,126.0,1.0,Rural,Y
149,150,Male,No,0.0,Graduate,No,4860,125.0,1.0,Semiurban,Y
15,16,Male,Yes,0.0,Graduate,No,4950,125.0,1.0,Urban,Y
389,390,Male,No,0.0,Graduate,No,5488,125.0,1.0,Rural,Y
367,368,Male,Yes,0.0,Graduate,No,5124,124.0,0.0,Rural,N
93,94,Male,Yes,0.0,Graduate,No,4133,122.0,1.0,Semiurban,Y
143,144,Male,No,0.0,Graduate,No,2698,122.0,1.0,Semiurban,Y
26,27,Male,No,0.0,Graduate,No,2799,122.0,1.0,Semiurban,Y
425,426,Male,No,0.0,Graduate,No,2666,121.0,1.0,Rural,Y
158,159,Male,Yes,0.0,Graduate,NaN,2980,120.0,1.0,Rural,Y
60,61,Male,No,0.0,Graduate,No,2500,120.0,1.0,Urban,Y
185,186,Male,No,0.0,Graduate,Yes,39147,120.0,1.0,Semiurban,Y
194,195,Male,Yes,0.0,Graduate,No,4191,120.0,1.0,Rural,Y
375,376,Male,No,0.0,Graduate,No,4817,120.0,1.0,Urban,Y
245,246,Male,Yes,0.0,Graduate,Yes,6050,120.0,1.0,Urban,N
392,393,Male,No,0.0,Graduate,No,2583,120.0,NaN,Urban,Y
287,288,Male,No,0.0,Graduate,No,3704,120.0,1.0,Rural,Y
494,495,Male,No,0.0,Graduate,No,3597,119.0,0.0,Rural,N
150,151,Male,Yes,0.0,Graduate,No,6277,118.0,0.0,Rural,N
456,457,Male,No,0.0,Graduate,No,4301,118.0,1.0,Urban,Y
114,115,Male,Yes,0.0,Graduate,NaN,5050,118.0,1.0,Semiurban,Y
175,176,Male,No,0.0,Graduate,No,3497,116.0,1.0,Rural,Y
19,20,Male,No,0.0,Graduate,NaN,2600,115.0,1.0,Urban,Y
320,321,Male,No,0.0,Graduate,No,2400,115.0,1.0,Semiurban,Y
13,14,Male,Yes,0.0,Graduate,No,1853,114.0,1.0,Rural,N
33,34,Male,No,0.0,Graduate,No,3500,114.0,1.0,Semiurban,Y
75,76,Male,Yes,0.0,Graduate,No,3750,113.0,1.0,Urban,N
418,419,Male,No,0.0,Graduate,No,1025,112.0,1.0,Rural,Y
281,282,Male,No,0.0,Graduate,No,3927,112.0,1.0,Semiurban,Y
497,498,Male,No,0.0,Graduate,No,4625,111.0,NaN,Urban,Y
469,470,Male,No,0.0,Graduate,No,4333,110.0,1.0,Urban,N
577,578,Male,Yes,0.0,Graduate,No,3229,110.0,1.0,Urban,Y
526,527,Male,No,0.0,Graduate,No,3775,110.0,1.0,Semiurban,Y
549,550,Male,No,0.0,Graduate,No,2785,110.0,1.0,Rural,Y
608,609,Male,No,0.0,Graduate,No,3232,108.0,1.0,Rural,Y
431,432,Male,Yes,0.0,Graduate,No,6500,105.0,0.0,Rural,N
87,88,Male,No,0.0,Graduate,No,2500,104.0,1.0,Semiurban,Y
586,587,Male,No,0.0,Graduate,No,2297,104.0,1.0,Urban,Y
569,570,Male,No,0.0,Graduate,No,3166,104.0,0.0,Urban,N
402,403,Male,Yes,0.0,Graduate,No,2500,103.0,1.0,Semiurban,Y
134,135,Male,Yes,0.0,Graduate,No,4895,102.0,1.0,Semiurban,Y
422,423,Male,No,0.0,Graduate,No,1820,100.0,1.0,Urban,Y
36,37,Male,No,0.0,Graduate,No,1828,100.0,0.0,Urban,N
434,435,Male,Yes,0.0,Graduate,No,3750,100.0,1.0,Urban,Y
464,465,Male,Yes,0.0,Graduate,No,4166,98.0,0.0,Semiurban,N
331,332,Male,Yes,0.0,Graduate,No,2935,98.0,1.0,Semiurban,Y
424,425,Male,No,0.0,Graduate,No,14880,96.0,1.0,Semiurban,Y
56,57,Male,No,0.0,Graduate,No,2132,96.0,1.0,Semiurban,Y
366,367,Male,Yes,0.0,Graduate,No,2500,96.0,1.0,Semiurban,N
363,364,Male,No,0.0,Graduate,No,3013,95.0,NaN,Urban,Y
397,398,Male,No,0.0,Graduate,No,3033,95.0,1.0,Urban,Y
453,454,Male,No,0.0,Graduate,No,2483,90.0,0.0,Rural,Y
249,250,Male,No,0.0,Graduate,No,1809,90.0,1.0,Urban,Y
581,582,Male,Yes,0.0,Graduate,No,1836,90.0,1.0,Urban,N
285,286,Male,Yes,0.0,Graduate,No,3158,89.0,1.0,Rural,Y
317,318,Male,No,0.0,Graduate,No,2058,88.0,NaN,Urban,Y
428,429,Male,No,0.0,Graduate,No,2920,87.0,1.0,Rural,Y
454,455,Male,Yes,0.0,Graduate,Yes,7085,84.0,1.0,Semiurban,Y
199,200,Male,Yes,0.0,Graduate,Yes,11000,83.0,1.0,Urban,N
72,73,Male,Yes,0.0,Graduate,No,3500,81.0,1.0,Semiurban,Y
40,41,Male,Yes,0.0,Graduate,No,3600,80.0,1.0,Urban,N
277,278,Male,No,0.0,Graduate,No,3103,80.0,1.0,Urban,Y
193,194,Male,Yes,0.0,Graduate,No,3858,76.0,1.0,Semiurban,Y
42,43,Male,No,0.0,Graduate,No,2400,75.0,NaN,Urban,Y
164,165,Male,No,0.0,Graduate,No,9323,75.0,1.0,Urban,Y
489,490,Male,Yes,0.0,Graduate,No,2435,75.0,1.0,Urban,N
131,132,Male,Yes,0.0,Graduate,No,2014,74.0,1.0,Urban,Y
31,32,Male,Yes,0.0,Graduate,No,3167,74.0,1.0,Urban,N
182,183,Male,No,0.0,Graduate,No,4600,73.0,1.0,Semiurban,Y
378,379,Male,Yes,0.0,Graduate,No,3069,71.0,1.0,Urban,N
132,133,Male,Yes,0.0,Graduate,No,2718,70.0,1.0,Semiurban,Y
566,567,Male,Yes,0.0,Graduate,No,3333,70.0,1.0,Urban,Y
513,514,Male,No,0.0,Graduate,No,2130,70.0,1.0,Semiurban,N
181,182,Male,Yes,0.0,Graduate,No,1916,67.0,NaN,Rural,N
2,3,Male,No,0.0,Graduate,Yes,3000,66.0,1.0,Urban,Y
168,169,Male,Yes,0.0,Graduate,No,2237,63.0,0.0,Semiurban,N
220,221,Male,No,0.0,Graduate,No,2221,60.0,0.0,Urban,N
208,209,Male,Yes,0.0,Graduate,No,2479,59.0,1.0,Urban,Y
187,188,Male,No,0.0,Graduate,No,2383,58.0,NaN,Rural,Y
590,591,Male,No,0.0,Graduate,No,3000,56.0,1.0,Semiurban,Y
447,448,Male,No,0.0,Graduate,NaN,3539,55.0,1.0,Rural,N
521,522,Male,Yes,0.0,Graduate,No,2500,55.0,1.0,Semiurban,Y
154,155,Male,Yes,0.0,Graduate,No,3254,50.0,1.0,Urban,Y
97,98,Male,No,0.0,Graduate,No,1977,50.0,1.0,Semiurban,Y
436,437,Male,Yes,0.0,Graduate,No,1926,50.0,1.0,Semiurban,Y
41,42,Male,Yes,0.0,Graduate,No,1800,47.0,1.0,Urban,Y
231,232,Male,No,0.0,Graduate,NaN,3716,42.0,1.0,Rural,Y
133,134,Male,No,0.0,Graduate,Yes,3459,25.0,1.0,Semiurban,Y
0,1,Male,Yes,0.0,Graduate,No,5139,0.0,1.0,Urban,Y
95,96,Male,Yes,0.0,Graduate,NaN,6782,NaN,NaN,Urban,N
103,104,Male,No,0.0,Graduate,No,4652,NaN,1.0,Semiurban,Y
35,36,Male,No,0.0,Graduate,No,2275,NaN,1.0,Urban,Y
127,128,Male,Yes,0.0,Graduate,No,3865,NaN,1.0,Rural,Y
437,438,Male,No,0.0,Graduate,No,2213,NaN,1.0,Urban,Y
284,285,Male,No,0.0,Graduate,No,20667,NaN,1.0,Rural,N
524,525,Male,Yes,0.0,Graduate,No,4680,NaN,1.0,Semiurban,N
412,413,Male,No,0.0,Not Graduate,No,6096,218.0,0.0,Rural,N
250,251,Male,No,0.0,Not Graduate,No,1668,201.0,0.0,Semiurban,N
124,125,Male,No,0.0,Not Graduate,No,4300,194.0,1.0,Rural,Y
553,554,Male,No,0.0,Not Graduate,No,2454,181.0,0.0,Urban,N
62,63,Male,No,0.0,Not Graduate,Yes,2609,165.0,0.0,Rural,N
192,193,Male,No,0.0,Not Graduate,No,6033,160.0,1.0,Urban,N
601,602,Male,No,0.0,Not Graduate,NaN,2894,155.0,1.0,Rural,Y
112,113,Male,No,0.0,Not Graduate,No,3572,152.0,0.0,Rural,N
18,19,Male,No,0.0,Not Graduate,No,4887,133.0,1.0,Rural,N
365,366,Male,Yes,0.0,Not Graduate,No,6216,133.0,1.0,Rural,N
386,387,Male,Yes,0.0,Not Graduate,No,2346,132.0,1.0,Semiurban,Y
563,564,Male,Yes,0.0,Not Graduate,Yes,5800,132.0,1.0,Semiurban,Y
529,530,Male,Yes,0.0,Not Graduate,No,6783,130.0,1.0,Semiurban,Y
66,67,Male,Yes,0.0,Not Graduate,No,3200,126.0,0.0,Urban,N
535,536,Male,Yes,0.0,Not Graduate,NaN,2550,126.0,1.0,Rural,Y
504,505,Male,No,0.0,Not Graduate,No,3814,124.0,1.0,Semiurban,Y
244,245,Male,No,0.0,Not Graduate,No,3406,123.0,1.0,Semiurban,Y
107,108,Male,Yes,0.0,Not Graduate,NaN,7333,120.0,1.0,Rural,N
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
232,233,Male,Yes,0.0,Not Graduate,No,3189,120.0,1.0,Rural,Y
565,566,Male,No,0.0,Not Graduate,No,4467,120.0,NaN,Rural,Y
22,23,Male,No,0.0,Not Graduate,No,2600,116.0,0.0,Semiurban,N
98,99,Male,No,0.0,Not Graduate,No,4188,115.0,1.0,Semiurban,Y
256,257,Male,Yes,0.0,Not Graduate,No,6045,115.0,0.0,Rural,N
406,407,Male,No,0.0,Not Graduate,No,2167,115.0,1.0,Urban,Y
311,312,Male,Yes,0.0,Not Graduate,No,2927,111.0,1.0,Semiurban,Y
492,493,Male,Yes,0.0,Not Graduate,No,3691,110.0,1.0,Rural,Y
39,40,Male,Yes,0.0,Not Graduate,No,3748,110.0,1.0,Semiurban,Y
595,596,Male,Yes,0.0,Not Graduate,No,3833,110.0,1.0,Rural,Y
413,414,Male,No,0.0,Not Graduate,No,2253,110.0,1.0,Rural,Y
398,399,Male,Yes,0.0,Not Graduate,No,3902,109.0,1.0,Rural,Y
496,497,Male,No,0.0,Not Graduate,No,2600,107.0,1.0,Rural,Y
20,21,Male,No,0.0,Not Graduate,No,7660,104.0,0.0,Urban,N
252,253,Male,Yes,0.0,Not Graduate,Yes,2583,104.0,1.0,Rural,Y
179,180,Male,Yes,0.0,Not Graduate,No,2333,102.0,0.0,Urban,N
358,359,Male,No,0.0,Not Graduate,No,3000,100.0,0.0,Urban,N
510,511,Male,Yes,0.0,Not Graduate,No,3598,100.0,1.0,Rural,N
160,161,Male,No,0.0,Not Graduate,No,1863,98.0,1.0,Semiurban,Y
490,491,Male,Yes,0.0,Not Graduate,No,2699,96.0,NaN,Semiurban,Y
44,45,Male,No,0.0,Not Graduate,Yes,4695,96.0,1.0,Urban,Y
170,171,Male,No,0.0,Not Graduate,NaN,1820,95.0,1.0,Rural,Y
6,7,Male,No,0.0,Not Graduate,No,2333,95.0,1.0,Urban,Y
300,301,Male,No,0.0,Not Graduate,No,1800,93.0,0.0,Urban,N
174,175,Male,No,0.0,Not Graduate,Yes,4344,87.0,1.0,Semiurban,N
546,547,Male,Yes,0.0,Not Graduate,No,3358,80.0,1.0,Semiurban,N
538,539,Male,No,0.0,Not Graduate,No,2917,66.0,1.0,Rural,N
401,402,Male,Yes,0.0,Not Graduate,No,2755,65.0,1.0,Rural,N
429,430,Male,Yes,0.0,Not Graduate,No,2717,60.0,1.0,Urban,Y
207,208,Male,Yes,0.0,Not Graduate,No,3975,55.0,1.0,Rural,Y
190,191,Male,Yes,0.0,Not Graduate,No,4885,48.0,1.0,Rural,Y
28,29,Male,Yes,0.0,Not Graduate,No,1442,35.0,1.0,Urban,N
94,95,Male,Yes,0.0,Not Graduate,No,3620,25.0,1.0,Semiurban,Y
387,388,Male,No,0.0,Not Graduate,No,3010,NaN,0.0,Urban,N
305,306,Male,Yes,0.0,Not Graduate,No,2000,NaN,1.0,Urban,N
605,606,Male,No,0.0,Not Graduate,No,2400,NaN,1.0,Urban,N
188,189,NaN,No,0.0,Graduate,Yes,674,168.0,1.0,Rural,Y
460,461,NaN,No,0.0,Graduate,Yes,2083,160.0,NaN,Semiurban,Y
314,315,NaN,No,0.0,Graduate,No,2473,159.0,1.0,Rural,N
576,577,NaN,No,0.0,Graduate,No,3087,136.0,0.0,Semiurban,N
467,468,NaN,No,0.0,Graduate,No,16692,110.0,1.0,Semiurban,Y

In [97]:
dataset['Serial_no']

233    234
119    120
148    149
210    211
404    405
      ...
102    103
346    347
226    227
517    518
301    302
Name: Serial_no, Length: 614, dtype: int64

In [99]:
dataset.set_index('Serial_no', inplace=True)

In [100]:
dataset

,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
Serial_no,,,,,,,,,,
234,Female,Yes,0.0,Graduate,No,8333,280.0,1.0,Semiurban,Y
120,Female,Yes,0.0,Graduate,No,10408,259.0,1.0,Urban,Y
149,Female,Yes,0.0,Graduate,No,10000,225.0,1.0,Rural,N
211,Female,Yes,0.0,Graduate,No,10000,214.0,1.0,Semiurban,N
405,Female,Yes,0.0,Graduate,Yes,7441,194.0,1.0,Rural,N
...,...,...,...,...,...,...,...,...,...,...
103,Male,No,NaN,Graduate,No,13650,NaN,1.0,Urban,Y
347,Male,No,NaN,Not Graduate,No,3523,152.0,0.0,Rural,N
227,Male,No,NaN,Not Graduate,Yes,4735,138.0,1.0,Urban,N
518,Male,No,NaN,Not Graduate,No,3074,123.0,0.0,Semiurban,N
302,Male,No,NaN,Not Graduate,No,2875,105.0,1.0,Semiurban,Y