In [1]:
import pandas as pd

In [14]:
import numpy as np

In [10]:
dataset = pd.read_csv("recruitment_decision_tree.csv")

In [3]:
dataset.head()

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
0,1,Male,Yes,0.0,Graduate,No,5139,0.0,1.0,Urban,Y
1,2,Male,No,1.0,Graduate,No,4583,128.0,1.0,Rural,N
2,3,Male,No,0.0,Graduate,Yes,3000,66.0,1.0,Urban,Y
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
4,5,Male,Yes,0.0,Graduate,No,6000,141.0,1.0,Urban,Y

In [4]:
dataset.tail()

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
609,610,Female,Yes,0.0,Graduate,No,2900,71.0,1.0,Rural,Y
610,611,Male,No,3.0,Graduate,No,4106,40.0,1.0,Rural,Y
611,612,Male,No,1.0,Graduate,No,8072,253.0,1.0,Urban,Y
612,613,Male,No,2.0,Graduate,No,7583,187.0,1.0,Urban,Y
613,614,Female,Yes,0.0,Graduate,Yes,4583,133.0,0.0,Semiurban,N

In [6]:
dataset.head()

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
0,1,Male,Yes,0.0,Graduate,No,5139,0.0,1.0,Urban,Y
1,2,Male,No,1.0,Graduate,No,4583,128.0,1.0,Rural,N
2,3,Male,No,0.0,Graduate,Yes,3000,66.0,1.0,Urban,Y
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
4,5,Male,Yes,0.0,Graduate,No,6000,141.0,1.0,Urban,Y

In [21]:
pd.set_option('display.max_rows', 500)

In [22]:
dataset.head(500)

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
0,1,Male,Yes,0.0,Graduate,No,5139,0.0,1.0,Urban,Y
1,2,Male,No,1.0,Graduate,No,4583,128.0,1.0,Rural,N
2,3,Male,No,0.0,Graduate,Yes,3000,66.0,1.0,Urban,Y
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
4,5,Male,Yes,0.0,Graduate,No,6000,141.0,1.0,Urban,Y
5,6,Male,No,2.0,Graduate,Yes,5417,267.0,1.0,Urban,Y
6,7,Male,No,0.0,Not Graduate,No,2333,95.0,1.0,Urban,Y
7,8,Male,No,3.0,Graduate,No,3036,158.0,0.0,Semiurban,N
8,9,Male,No,2.0,Graduate,No,4006,168.0,1.0,Urban,Y
9,10,Male,No,1.0,Graduate,No,12841,349.0,1.0,Semiurban,N
10,11,Male,No,2.0,Graduate,No,3200,70.0,1.0,Urban,Y
11,12,Male,No,2.0,Graduate,NaN,2500,109.0,1.0,Urban,Y
12,13,Male,No,2.0,Graduate,No,3073,200.0,1.0,Urban,Y
13,14,Male,Yes,0.0,Graduate,No,1853,114.0,1.0,Rural,N
14,15,Male,No,2.0,Graduate,No,1299,17.0,1.0,Urban,Y
15,16,Male,Yes,0.0,Graduate,No,4950,125.0,1.0,Urban,Y
16,17,Male,Yes,1.0,Not Graduate,No,3596,100.0,NaN,Urban,Y
17,18,Female,Yes,0.0,Graduate,No,3510,76.0,0.0,Urban,N
18,19,Male,No,0.0,Not Graduate,No,4887,133.0,1.0,Rural,N
19,20,Male,No,0.0,Graduate,NaN,2600,115.0,1.0,Urban,Y
20,21,Male,No,0.0,Not Graduate,No,7660,104.0,0.0,Urban,N
21,22,Male,No,1.0,Graduate,No,5955,315.0,1.0,Urban,Y
22,23,Male,No,0.0,Not Graduate,No,2600,116.0,0.0,Semiurban,N
23,24,NaN,No,2.0,Not Graduate,No,3365,112.0,0.0,Rural,N
24,25,Male,No,1.0,Graduate,NaN,3717,151.0,NaN,Semiurban,N
25,26,Male,No,0.0,Graduate,Yes,9560,191.0,1.0,Semiurban,Y
26,27,Male,No,0.0,Graduate,No,2799,122.0,1.0,Semiurban,Y
27,28,Male,No,2.0,Not Graduate,No,4226,110.0,1.0,Urban,Y
28,29,Male,Yes,0.0,Not Graduate,No,1442,35.0,1.0,Urban,N
29,30,Female,Yes,2.0,Graduate,NaN,3750,120.0,1.0,Semiurban,Y
30,31,Male,No,1.0,Graduate,NaN,4166,201.0,NaN,Urban,N
31,32,Male,Yes,0.0,Graduate,No,3167,74.0,1.0,Urban,N
32,33,Male,Yes,1.0,Graduate,Yes,4692,106.0,1.0,Rural,N
33,34,Male,No,0.0,Graduate,No,3500,114.0,1.0,Semiurban,Y
34,35,Male,Yes,3.0,Graduate,No,12500,320.0,1.0,Rural,N
35,36,Male,No,0.0,Graduate,No,2275,NaN,1.0,Urban,Y
36,37,Male,No,0.0,Graduate,No,1828,100.0,0.0,Urban,N
37,38,Female,No,0.0,Graduate,No,3667,144.0,1.0,Semiurban,Y
38,39,Male,Yes,0.0,Graduate,No,4166,184.0,1.0,Urban,Y
39,40,Male,Yes,0.0,Not Graduate,No,3748,110.0,1.0,Semiurban,Y
40,41,Male,Yes,0.0,Graduate,No,3600,80.0,1.0,Urban,N
41,42,Male,Yes,0.0,Graduate,No,1800,47.0,1.0,Urban,Y
42,43,Male,No,0.0,Graduate,No,2400,75.0,NaN,Urban,Y
43,44,Male,No,0.0,Graduate,No,3941,134.0,1.0,Semiurban,Y
44,45,Male,No,0.0,Not Graduate,Yes,4695,96.0,1.0,Urban,Y
45,46,Female,Yes,0.0,Graduate,No,3410,88.0,1.0,Urban,Y
46,47,Male,No,1.0,Graduate,No,5649,44.0,1.0,Urban,Y
47,48,Male,No,0.0,Graduate,No,5821,144.0,1.0,Urban,Y
48,49,Female,No,0.0,Graduate,No,2645,120.0,0.0,Urban,N
49,50,Female,Yes,0.0,Graduate,No,4000,144.0,1.0,Semiurban,Y
50,51,Female,No,0.0,Not Graduate,No,1928,100.0,1.0,Semiurban,Y
51,52,Female,Yes,0.0,Graduate,No,3086,120.0,1.0,Semiurban,Y
52,53,Female,Yes,0.0,Graduate,No,4230,112.0,1.0,Semiurban,N
53,54,Male,No,2.0,Graduate,No,4616,134.0,1.0,Urban,N
54,55,Female,No,1.0,Graduate,Yes,11500,286.0,0.0,Urban,N
55,56,Male,No,2.0,Graduate,No,2708,97.0,1.0,Semiurban,Y
56,57,Male,No,0.0,Graduate,No,2132,96.0,1.0,Semiurban,Y
57,58,Male,No,0.0,Graduate,No,3366,135.0,1.0,Rural,N
58,59,Male,No,1.0,Graduate,No,8080,180.0,1.0,Urban,Y
59,60,Male,No,2.0,Not Graduate,No,3357,144.0,1.0,Urban,Y
60,61,Male,No,0.0,Graduate,No,2500,120.0,1.0,Urban,Y
61,62,Male,No,3.0,Graduate,No,3029,99.0,1.0,Urban,Y
62,63,Male,No,0.0,Not Graduate,Yes,2609,165.0,0.0,Rural,N
63,64,Male,No,1.0,Graduate,No,4945,NaN,0.0,Rural,N
64,65,Female,Yes,0.0,Graduate,No,4166,116.0,0.0,Semiurban,N
65,66,Male,No,0.0,Graduate,No,5726,258.0,1.0,Semiurban,N
66,67,Male,Yes,0.0,Not Graduate,No,3200,126.0,0.0,Urban,N
67,68,Male,No,1.0,Graduate,No,10750,312.0,1.0,Urban,Y
68,69,Male,No,3.0,Not Graduate,Yes,7100,125.0,1.0,Urban,Y
69,70,Female,Yes,0.0,Graduate,No,4300,136.0,0.0,Semiurban,N
70,71,Male,No,0.0,Graduate,No,3208,172.0,1.0,Urban,Y
71,72,Male,No,2.0,Not Graduate,Yes,1875,97.0,1.0,Semiurban,Y
72,73,Male,Yes,0.0,Graduate,No,3500,81.0,1.0,Semiurban,Y
73,74,Male,No,3.0,Not Graduate,No,4755,95.0,0.0,Semiurban,N
74,75,Male,No,3.0,Graduate,Yes,5266,187.0,1.0,Semiurban,Y
75,76,Male,Yes,0.0,Graduate,No,3750,113.0,1.0,Urban,N
76,77,Male,Yes,0.0,Graduate,No,3750,176.0,1.0,Urban,N
77,78,Male,No,1.0,Graduate,Yes,1000,110.0,1.0,Urban,N
78,79,Male,No,3.0,Graduate,No,3167,180.0,0.0,Semiurban,N
79,80,Male,No,3.0,Not Graduate,Yes,3333,130.0,NaN,Semiurban,Y
80,81,Female,Yes,0.0,Graduate,No,3846,111.0,1.0,Semiurban,Y
81,82,Male,No,1.0,Graduate,Yes,2395,NaN,1.0,Semiurban,Y
82,83,Female,No,2.0,Graduate,No,1378,167.0,1.0,Urban,N
83,84,Male,No,0.0,Graduate,No,6000,265.0,NaN,Semiurban,N
84,85,Male,No,1.0,Graduate,No,3988,50.0,1.0,Urban,Y
85,86,Male,Yes,0.0,Graduate,No,2366,136.0,1.0,Semiurban,Y
86,87,Male,No,2.0,Not Graduate,No,3333,99.0,NaN,Semiurban,Y
87,88,Male,No,0.0,Graduate,No,2500,104.0,1.0,Semiurban,Y
88,89,Male,Yes,0.0,Graduate,No,8566,210.0,1.0,Urban,Y
89,90,Male,No,0.0,Graduate,No,5695,175.0,1.0,Semiurban,Y
90,91,Male,No,0.0,Graduate,No,2958,131.0,1.0,Semiurban,Y
91,92,Male,No,2.0,Graduate,No,6250,188.0,1.0,Semiurban,Y
92,93,Male,No,2.0,Not Graduate,No,3273,81.0,1.0,Urban,Y
93,94,Male,Yes,0.0,Graduate,No,4133,122.0,1.0,Semiurban,Y
94,95,Male,Yes,0.0,Not Graduate,No,3620,25.0,1.0,Semiurban,Y
95,96,Male,Yes,0.0,Graduate,NaN,6782,NaN,NaN,Urban,N
96,97,Female,No,0.0,Graduate,No,2484,137.0,1.0,Semiurban,Y
97,98,Male,No,0.0,Graduate,No,1977,50.0,1.0,Semiurban,Y
98,99,Male,No,0.0,Not Graduate,No,4188,115.0,1.0,Semiurban,Y
99,100,Male,No,0.0,Graduate,No,1759,131.0,1.0,Semiurban,Y
100,101,Male,No,2.0,Not Graduate,No,4288,133.0,1.0,Urban,Y
101,102,Male,Yes,0.0,Graduate,No,4843,151.0,1.0,Semiurban,Y
102,103,Male,No,NaN,Graduate,No,13650,NaN,1.0,Urban,Y
103,104,Male,No,0.0,Graduate,No,4652,NaN,1.0,Semiurban,Y
104,105,Male,NaN,NaN,Graduate,No,3816,160.0,1.0,Urban,Y
105,106,Male,No,1.0,Graduate,No,3052,100.0,1.0,Urban,Y
106,107,Male,No,2.0,Graduate,No,11417,225.0,1.0,Urban,Y
107,108,Male,Yes,0.0,Not Graduate,NaN,7333,120.0,1.0,Rural,N
108,109,Male,No,2.0,Graduate,No,3800,216.0,0.0,Urban,N
109,110,Male,No,3.0,Not Graduate,No,2071,94.0,1.0,Semiurban,Y
110,111,Male,Yes,0.0,Graduate,No,5316,136.0,1.0,Urban,Y
111,112,Female,No,0.0,Graduate,NaN,2929,139.0,1.0,Semiurban,Y
112,113,Male,No,0.0,Not Graduate,No,3572,152.0,0.0,Rural,N
113,114,Female,Yes,1.0,Graduate,Yes,7451,NaN,1.0,Semiurban,Y
114,115,Male,Yes,0.0,Graduate,NaN,5050,118.0,1.0,Semiurban,Y
115,116,Male,No,1.0,Graduate,No,14583,185.0,1.0,Rural,Y
116,117,Female,No,0.0,Graduate,No,3167,154.0,1.0,Semiurban,Y
117,118,Male,No,1.0,Graduate,No,2214,85.0,NaN,Urban,Y
118,119,Male,No,0.0,Graduate,No,5568,175.0,1.0,Rural,N
119,120,Female,Yes,0.0,Graduate,No,10408,259.0,1.0,Urban,Y
120,121,Male,No,NaN,Graduate,No,5667,180.0,1.0,Rural,Y
121,122,Female,Yes,0.0,Graduate,No,4166,44.0,1.0,Semiurban,Y
122,123,Female,Yes,0.0,Graduate,No,2137,137.0,0.0,Semiurban,Y
123,124,Male,No,2.0,Graduate,No,2957,81.0,1.0,Semiurban,Y
124,125,Male,No,0.0,Not Graduate,No,4300,194.0,1.0,Rural,Y
125,126,Female,Yes,0.0,Graduate,No,3692,93.0,NaN,Rural,Y
126,127,NaN,No,3.0,Graduate,No,23803,370.0,1.0,Rural,Y
127,128,Male,Yes,0.0,Graduate,No,3865,NaN,1.0,Rural,Y
128,129,Male,No,1.0,Graduate,Yes,10513,160.0,0.0,Urban,N
129,130,Male,No,0.0,Graduate,No,6080,182.0,NaN,Rural,N
130,131,Male,Yes,0.0,Graduate,Yes,20166,650.0,NaN,Urban,Y
131,132,Male,Yes,0.0,Graduate,No,2014,74.0,1.0,Urban,Y
132,133,Male,Yes,0.0,Graduate,No,2718,70.0,1.0,Semiurban,Y
133,134,Male,No,0.0,Graduate,Yes,3459,25.0,1.0,Semiurban,Y
134,135,Male,Yes,0.0,Graduate,No,4895,102.0,1.0,Semiurban,Y
135,136,Male,No,3.0,Graduate,No,4000,290.0,1.0,Semiurban,N
136,137,Female,No,0.0,Graduate,No,4583,84.0,1.0,Rural,N
137,138,Male,No,2.0,Graduate,Yes,3316,88.0,1.0,Urban,Y
138,139,Male,Yes,0.0,Graduate,No,14999,242.0,0.0,Semiurban,N
139,140,Male,No,2.0,Not Graduate,No,4200,129.0,1.0,Rural,N
140,141,Male,No,2.0,Graduate,No,5042,185.0,1.0,Rural,N
141,142,Male,Yes,0.0,Graduate,No,5417,168.0,1.0,Urban,Y
142,143,Male,Yes,0.0,Graduate,Yes,6950,175.0,1.0,Semiurban,Y
143,144,Male,No,0.0,Graduate,No,2698,122.0,1.0,Semiurban,Y
144,145,Male,No,2.0,Graduate,No,11757,187.0,1.0,Urban,Y
145,146,Female,No,0.0,Graduate,No,2330,100.0,1.0,Semiurban,Y
146,147,Female,No,2.0,Graduate,No,14866,70.0,1.0,Urban,Y
147,148,Male,No,1.0,Graduate,No,1538,30.0,1.0,Urban,Y
148,149,Female,Yes,0.0,Graduate,No,10000,225.0,1.0,Rural,N
149,150,Male,No,0.0,Graduate,No,4860,125.0,1.0,Semiurban,Y
150,151,Male,Yes,0.0,Graduate,No,6277,118.0,0.0,Rural,N
151,152,Male,No,0.0,Graduate,Yes,2577,152.0,1.0,Rural,Y
152,153,Male,Yes,0.0,Graduate,No,9166,244.0,1.0,Urban,N
153,154,Male,No,2.0,Not Graduate,No,2281,113.0,1.0,Rural,N
154,155,Male,Yes,0.0,Graduate,No,3254,50.0,1.0,Urban,Y
155,156,Male,No,3.0,Graduate,No,39999,600.0,0.0,Semiurban,Y
156,157,Male,No,1.0,Graduate,No,6000,160.0,NaN,Rural,Y
157,158,Male,No,1.0,Graduate,No,9538,187.0,1.0,Urban,Y
158,159,Male,Yes,0.0,Graduate,NaN,2980,120.0,1.0,Rural,Y
159,160,Male,No,0.0,Graduate,No,4583,255.0,1.0,Semiurban,Y
160,161,Male,No,0.0,Not Graduate,No,1863,98.0,1.0,Semiurban,Y
161,162,Male,No,0.0,Graduate,No,7933,275.0,1.0,Urban,N
162,163,Male,No,1.0,Graduate,No,3089,121.0,0.0,Semiurban,N
163,164,Male,No,2.0,Graduate,No,4167,158.0,1.0,Rural,Y
164,165,Male,No,0.0,Graduate,No,9323,75.0,1.0,Urban,Y
165,166,Male,No,0.0,Graduate,No,3707,182.0,1.0,Rural,Y
166,167,Female,No,0.0,Graduate,No,4583,112.0,1.0,Rural,N
167,168,Male,No,0.0,Graduate,No,2439,129.0,1.0,Rural,Y
168,169,Male,Yes,0.0,Graduate,No,2237,63.0,0.0,Semiurban,N
169,170,Male,No,2.0,Graduate,No,8000,200.0,1.0,Semiurban,Y
170,171,Male,No,0.0,Not Graduate,NaN,1820,95.0,1.0,Rural,Y
171,172,NaN,No,3.0,Graduate,No,51763,700.0,1.0,Urban,Y
172,173,Male,No,3.0,Not Graduate,No,3522,81.0,1.0,Rural,N
173,174,Male,No,0.0,Graduate,No,5708,187.0,1.0,Semiurban,Y
174,175,Male,No,0.0,Not Graduate,Yes,4344,87.0,1.0,Semiurban,N
175,176,Male,No,0.0,Graduate,No,3497,116.0,1.0,Rural,Y
176,177,Male,No,2.0,Graduate,No,2045,101.0,1.0,Rural,Y
177,178,Male,No,3.0,Graduate,No,5516,495.0,0.0,Semiurban,N
178,179,Male,No,1.0,Graduate,No,3750,116.0,1.0,Semiurban,Y
179,180,Male,Yes,0.0,Not Graduate,No,2333,102.0,0.0,Urban,N
180,181,Male,No,1.0,Graduate,No,6400,180.0,0.0,Urban,N
181,182,Male,Yes,0.0,Graduate,No,1916,67.0,NaN,Rural,N
182,183,Male,No,0.0,Graduate,No,4600,73.0,1.0,Semiurban,Y
183,184,Male,No,1.0,Graduate,No,33846,260.0,1.0,Semiurban,N
184,185,Female,No,0.0,Graduate,No,3625,108.0,1.0,Semiurban,Y
185,186,Male,No,0.0,Graduate,Yes,39147,120.0,1.0,Semiurban,Y
186,187,Male,No,1.0,Graduate,Yes,2178,66.0,0.0,Rural,N
187,188,Male,No,0.0,Graduate,No,2383,58.0,NaN,Rural,Y
188,189,NaN,No,0.0,Graduate,Yes,674,168.0,1.0,Rural,Y
189,190,Male,No,0.0,Graduate,No,9328,188.0,1.0,Rural,Y
190,191,Male,Yes,0.0,Not Graduate,No,4885,48.0,1.0,Rural,Y
191,192,Male,Yes,0.0,Graduate,No,12000,164.0,1.0,Semiurban,N
192,193,Male,No,0.0,Not Graduate,No,6033,160.0,1.0,Urban,N
193,194,Male,Yes,0.0,Graduate,No,3858,76.0,1.0,Semiurban,Y
194,195,Male,Yes,0.0,Graduate,No,4191,120.0,1.0,Rural,Y
195,196,Male,No,1.0,Graduate,No,3125,170.0,1.0,Semiurban,N
196,197,Male,Yes,0.0,Graduate,No,8333,187.0,1.0,Rural,Y
197,198,Female,Yes,0.0,Not Graduate,No,1907,120.0,1.0,Urban,Y
198,199,Female,No,0.0,Graduate,No,3416,113.0,NaN,Semiurban,Y
199,200,Male,Yes,0.0,Graduate,Yes,11000,83.0,1.0,Urban,N
200,201,Male,No,1.0,Not Graduate,No,2600,90.0,1.0,Semiurban,Y
201,202,Male,Yes,2.0,Graduate,No,4923,166.0,0.0,Semiurban,Y
202,203,Male,No,3.0,Not Graduate,No,3992,NaN,1.0,Urban,N
203,204,Male,No,1.0,Not Graduate,No,3500,135.0,1.0,Urban,Y
204,205,Male,No,2.0,Not Graduate,No,3917,124.0,1.0,Semiurban,Y
205,206,Female,Yes,0.0,Not Graduate,No,4408,120.0,1.0,Semiurban,Y
206,207,Female,Yes,0.0,Graduate,No,3244,80.0,1.0,Urban,Y
207,208,Male,Yes,0.0,Not Graduate,No,3975,55.0,1.0,Rural,Y
208,209,Male,Yes,0.0,Graduate,No,2479,59.0,1.0,Urban,Y
209,210,Male,Yes,0.0,Graduate,No,3418,127.0,1.0,Semiurban,N
210,211,Female,Yes,0.0,Graduate,No,10000,214.0,1.0,Semiurban,N
211,212,Male,No,3.0,Graduate,No,3430,128.0,0.0,Semiurban,N
212,213,Male,No,1.0,Graduate,Yes,7787,240.0,1.0,Urban,Y
213,214,Male,No,3.0,Not Graduate,Yes,5703,130.0,1.0,Rural,Y
214,215,Male,No,0.0,Graduate,No,3173,137.0,1.0,Urban,Y
215,216,Male,No,3.0,Not Graduate,No,3850,100.0,1.0,Semiurban,Y
216,217,Male,No,0.0,Graduate,No,150,135.0,1.0,Rural,N
217,218,Male,No,0.0,Graduate,No,3727,131.0,1.0,Semiurban,Y
218,219,Male,No,2.0,Graduate,NaN,5000,72.0,0.0,Semiurban,N
219,220,Female,No,2.0,Graduate,No,4283,127.0,NaN,Semiurban,Y
220,221,Male,No,0.0,Graduate,No,2221,60.0,0.0,Urban,N
221,222,Male,No,2.0,Graduate,No,4009,116.0,1.0,Semiurban,Y
222,223,Male,Yes,0.0,Graduate,No,2971,144.0,1.0,Semiurban,Y
223,224,Male,No,0.0,Graduate,No,7578,175.0,1.0,Semiurban,Y
224,225,Male,No,0.0,Graduate,No,6250,128.0,1.0,Semiurban,Y
225,226,Male,No,0.0,Graduate,No,3250,170.0,1.0,Rural,N
226,227,Male,No,NaN,Not Graduate,Yes,4735,138.0,1.0,Urban,N
227,228,Male,No,2.0,Graduate,No,6250,210.0,1.0,Semiurban,Y
228,229,Male,NaN,NaN,Graduate,No,4758,158.0,1.0,Semiurban,Y
229,230,Male,Yes,0.0,Graduate,Yes,6400,200.0,1.0,Rural,Y
230,231,Male,No,1.0,Graduate,No,2491,104.0,1.0,Semiurban,Y
231,232,Male,No,0.0,Graduate,NaN,3716,42.0,1.0,Rural,Y
232,233,Male,Yes,0.0,Not Graduate,No,3189,120.0,1.0,Rural,Y
233,234,Female,Yes,0.0,Graduate,No,8333,280.0,1.0,Semiurban,Y
234,235,Male,No,1.0,Graduate,No,3155,140.0,1.0,Semiurban,Y
235,236,Male,No,1.0,Graduate,No,5500,170.0,1.0,Rural,Y
236,237,Male,No,0.0,Graduate,NaN,5746,255.0,NaN,Urban,N
237,238,Female,Yes,0.0,Graduate,Yes,3463,122.0,NaN,Urban,Y
238,239,Female,Yes,1.0,Graduate,No,3812,112.0,1.0,Rural,Y
239,240,Male,No,1.0,Graduate,No,3315,96.0,1.0,Semiurban,Y
240,241,Male,No,2.0,Graduate,No,5819,120.0,1.0,Rural,Y
241,242,Male,No,1.0,Not Graduate,No,2510,140.0,1.0,Urban,N
242,243,Male,Yes,0.0,Graduate,No,2965,155.0,1.0,Urban,Y
243,244,Male,No,2.0,Graduate,Yes,6250,108.0,1.0,Rural,Y
244,245,Male,No,0.0,Not Graduate,No,3406,123.0,1.0,Semiurban,Y
245,246,Male,Yes,0.0,Graduate,Yes,6050,120.0,1.0,Urban,N
246,247,Male,No,2.0,Graduate,No,9703,112.0,1.0,Urban,Y
247,248,Male,No,1.0,Not Graduate,No,6608,137.0,1.0,Urban,Y
248,249,Male,No,1.0,Graduate,No,2882,123.0,1.0,Semiurban,Y
249,250,Male,No,0.0,Graduate,No,1809,90.0,1.0,Urban,Y
250,251,Male,No,0.0,Not Graduate,No,1668,201.0,0.0,Semiurban,N
251,252,Female,Yes,2.0,Graduate,No,3427,138.0,1.0,Urban,N
252,253,Male,Yes,0.0,Not Graduate,Yes,2583,104.0,1.0,Rural,Y
253,254,Male,No,1.0,Not Graduate,No,2661,279.0,1.0,Semiurban,Y
254,255,Male,Yes,0.0,Graduate,Yes,16250,192.0,0.0,Urban,N
255,256,Female,Yes,3.0,Graduate,No,3083,255.0,1.0,Rural,Y
256,257,Male,Yes,0.0,Not Graduate,No,6045,115.0,0.0,Rural,N
257,258,Male,No,3.0,Graduate,No,5250,94.0,1.0,Urban,N
258,259,Male,No,0.0,Graduate,No,14683,304.0,1.0,Rural,N
259,260,Male,No,3.0,Not Graduate,No,4931,128.0,NaN,Semiurban,N
260,261,Male,No,1.0,Graduate,No,6083,330.0,NaN,Urban,Y
261,262,Male,Yes,0.0,Graduate,No,2060,134.0,1.0,Semiurban,Y
262,263,Female,Yes,1.0,Graduate,No,3481,155.0,1.0,Semiurban,N
263,264,Female,Yes,0.0,Graduate,No,7200,120.0,1.0,Rural,Y
264,265,Male,Yes,0.0,Graduate,Yes,5166,128.0,1.0,Semiurban,Y
265,266,Male,Yes,0.0,Graduate,No,4095,151.0,1.0,Rural,Y
266,267,Male,No,2.0,Graduate,No,4708,150.0,1.0,Semiurban,Y
267,268,Male,No,3.0,Graduate,No,4333,160.0,0.0,Urban,Y
268,269,Female,Yes,0.0,Graduate,NaN,3418,135.0,1.0,Rural,N
269,270,Female,Yes,1.0,Graduate,No,2876,90.0,1.0,Urban,Y
270,271,Female,Yes,0.0,Graduate,No,3237,30.0,1.0,Urban,Y
271,272,Male,No,0.0,Graduate,No,11146,136.0,1.0,Urban,Y
272,273,Male,Yes,0.0,Graduate,No,2833,126.0,1.0,Rural,Y
273,274,Male,No,0.0,Graduate,No,2620,150.0,1.0,Semiurban,Y
274,275,Male,No,2.0,Graduate,No,3900,90.0,1.0,Semiurban,Y
275,276,Male,No,1.0,Graduate,No,2750,115.0,1.0,Semiurban,Y
276,277,Male,No,0.0,Graduate,No,3993,207.0,1.0,Semiurban,Y
277,278,Male,No,0.0,Graduate,No,3103,80.0,1.0,Urban,Y
278,279,Male,No,0.0,Graduate,No,14583,436.0,1.0,Semiurban,Y
279,280,Female,No,0.0,Not Graduate,No,4100,124.0,NaN,Rural,Y
280,281,Male,Yes,1.0,Not Graduate,Yes,4053,158.0,0.0,Urban,N
281,282,Male,No,0.0,Graduate,No,3927,112.0,1.0,Semiurban,Y
282,283,Male,No,2.0,Graduate,No,2301,78.0,1.0,Urban,Y
283,284,Female,Yes,0.0,Graduate,No,1811,54.0,1.0,Urban,Y
284,285,Male,No,0.0,Graduate,No,20667,NaN,1.0,Rural,N
285,286,Male,Yes,0.0,Graduate,No,3158,89.0,1.0,Rural,Y
286,287,Female,Yes,0.0,Graduate,Yes,2600,99.0,1.0,Semiurban,N
287,288,Male,No,0.0,Graduate,No,3704,120.0,1.0,Rural,Y
288,289,Female,Yes,0.0,Graduate,No,4124,115.0,1.0,Semiurban,Y
289,290,Male,Yes,0.0,Graduate,No,9508,187.0,1.0,Rural,Y
290,291,Male,No,0.0,Graduate,No,3075,139.0,1.0,Rural,Y
291,292,Male,No,2.0,Graduate,No,4400,127.0,0.0,Semiurban,N
292,293,Male,No,2.0,Graduate,No,3153,134.0,1.0,Urban,Y
293,294,Female,Yes,NaN,Graduate,No,5417,143.0,0.0,Urban,N
294,295,Male,No,0.0,Graduate,No,2383,172.0,1.0,Semiurban,Y
295,296,Male,No,3.0,Graduate,NaN,4416,110.0,1.0,Urban,Y
296,297,Male,No,1.0,Graduate,No,6875,200.0,1.0,Semiurban,Y
297,298,Female,No,1.0,Graduate,No,4666,135.0,1.0,Urban,Y
298,299,Female,Yes,0.0,Graduate,No,5000,151.0,1.0,Rural,N
299,300,Male,No,1.0,Graduate,No,2014,113.0,1.0,Urban,N
300,301,Male,No,0.0,Not Graduate,No,1800,93.0,0.0,Urban,N
301,302,Male,No,NaN,Not Graduate,No,2875,105.0,1.0,Semiurban,Y
302,303,Female,Yes,0.0,Graduate,No,5000,132.0,1.0,Rural,Y
303,304,Male,No,1.0,Graduate,No,1625,96.0,1.0,Urban,Y
304,305,Male,Yes,0.0,Graduate,No,4000,140.0,1.0,Rural,Y
305,306,Male,Yes,0.0,Not Graduate,No,2000,NaN,1.0,Urban,N
306,307,Female,Yes,0.0,Graduate,No,3762,135.0,1.0,Rural,Y
307,308,Female,Yes,0.0,Graduate,No,2400,104.0,0.0,Urban,N
308,309,Male,Yes,0.0,Graduate,No,20233,480.0,1.0,Rural,N
309,310,Male,No,2.0,Not Graduate,No,7667,185.0,NaN,Rural,Y
310,311,Female,Yes,0.0,Graduate,No,2917,84.0,1.0,Semiurban,Y
311,312,Male,Yes,0.0,Not Graduate,No,2927,111.0,1.0,Semiurban,Y
312,313,Female,Yes,0.0,Graduate,No,2507,56.0,1.0,Rural,Y
313,314,Male,No,2.0,Graduate,Yes,5746,144.0,NaN,Rural,Y
314,315,NaN,No,0.0,Graduate,No,2473,159.0,1.0,Rural,N
315,316,Male,No,1.0,Not Graduate,No,3399,111.0,1.0,Urban,Y
316,317,Male,No,2.0,Graduate,No,3717,120.0,1.0,Semiurban,Y
317,318,Male,No,0.0,Graduate,No,2058,88.0,NaN,Urban,Y
318,319,Female,Yes,1.0,Graduate,No,3541,112.0,NaN,Semiurban,Y
319,320,Male,No,1.0,Graduate,Yes,10000,155.0,1.0,Rural,N
320,321,Male,No,0.0,Graduate,No,2400,115.0,1.0,Semiurban,Y
321,322,Male,No,3.0,Graduate,No,4342,124.0,1.0,Semiurban,Y
322,323,Male,No,2.0,Not Graduate,No,3601,NaN,1.0,Rural,Y
323,324,Female,Yes,0.0,Graduate,No,3166,132.0,NaN,Rural,Y
324,325,Male,No,3.0,Graduate,No,15000,300.0,1.0,Rural,Y
325,326,Male,No,1.0,Graduate,Yes,8666,376.0,0.0,Rural,N
326,327,Male,Yes,0.0,Graduate,No,4917,130.0,0.0,Rural,Y
327,328,Male,No,0.0,Graduate,Yes,5818,184.0,1.0,Semiurban,Y
328,329,Female,No,0.0,Graduate,No,4333,110.0,1.0,Urban,N
329,330,Female,Yes,0.0,Graduate,No,2500,67.0,1.0,Urban,Y
330,331,Male,Yes,1.0,Graduate,No,4384,117.0,1.0,Urban,Y
331,332,Male,Yes,0.0,Graduate,No,2935,98.0,1.0,Semiurban,Y
332,333,Male,Yes,NaN,Graduate,No,2833,71.0,1.0,Urban,Y
333,334,Male,No,0.0,Graduate,NaN,63337,490.0,1.0,Urban,Y
334,335,NaN,No,1.0,Graduate,Yes,9833,182.0,1.0,Urban,Y
335,336,Male,No,NaN,Graduate,Yes,5503,70.0,1.0,Semiurban,Y
336,337,Male,No,1.0,Graduate,NaN,5250,160.0,1.0,Rural,Y
337,338,Male,No,2.0,Graduate,Yes,2500,176.0,1.0,Rural,Y
338,339,Female,Yes,3.0,Not Graduate,No,1830,NaN,0.0,Urban,N
339,340,Female,Yes,0.0,Graduate,No,4160,71.0,1.0,Semiurban,Y
340,341,Male,No,3.0,Not Graduate,No,2647,173.0,1.0,Rural,N
341,342,Female,Yes,0.0,Graduate,No,2378,46.0,1.0,Rural,N
342,343,Male,No,1.0,Not Graduate,No,4554,158.0,1.0,Urban,Y
343,344,Male,No,3.0,Not Graduate,No,3173,74.0,1.0,Semiurban,Y
344,345,Male,No,2.0,Graduate,NaN,2583,125.0,1.0,Rural,Y
345,346,Male,No,0.0,Graduate,No,2499,160.0,1.0,Semiurban,Y

In [37]:
dataset.sort_values(by=['Gender', 'Education' ], ascending=False)

,Serial_no,Gender,Python_exp,Experience_Years,Education,Internship,Score,Salary * 10E4,Offer_History,Location,Recruitment_Status
3,4,Male,No,0.0,Not Graduate,No,2583,120.0,1.0,Urban,Y
6,7,Male,No,0.0,Not Graduate,No,2333,95.0,1.0,Urban,Y
16,17,Male,Yes,1.0,Not Graduate,No,3596,100.0,NaN,Urban,Y
18,19,Male,No,0.0,Not Graduate,No,4887,133.0,1.0,Rural,N
20,21,Male,No,0.0,Not Graduate,No,7660,104.0,0.0,Urban,N
...,...,...,...,...,...,...,...,...,...,...,...
477,478,NaN,No,2.0,Graduate,No,2873,132.0,0.0,Semiurban,N
507,508,NaN,Yes,0.0,Graduate,No,3583,96.0,1.0,Urban,N
576,577,NaN,No,0.0,Graduate,No,3087,136.0,0.0,Semiurban,N
588,589,NaN,Yes,0.0,Graduate,No,4750,94.0,1.0,Semiurban,Y
592,593,NaN,Yes,3.0,Graduate,Yes,9357,292.0,1.0,Semiurban,Y